### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by CachCheng** [Zulko/moviepy#1028]
```
2019-10-17 19:11:31.000  ERROR 91383 --- [     MainThread] module.smart_crop           : Traceback (most recent call last):
  File "/Users/chenghong/AI/new/AI2Video/core/smart_crop.py", line 241, in crop
    video_clip.write_videofile(video_path + file_name, fps=fps, audio_codec="aac", threads=5)
  File "<decorator-gen-51>", line 2, in write_videofile
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 326, in write_videofile
    logger=logger)
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 216, in ffmpeg_write_video
    fps=fps, dtype="uint8"):
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/moviepy/Clip.py", line 476, in iter_frames
    if (dtype is not None) and (frame.dtype != dtype):
AttributeError: 'NoneType' object has no attribute 'dtype'

Exception ignored in: <function tqdm.__del__ at 0x112d63d08>
Traceback (most recent call last):
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 889, in __del__
    self.close()
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1095, in close
    self._decr_instances(self)
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 454, in _decr_instances
    cls.monitor.exit()
  File "/Users/chenghong/anaconda3/lib/python3.7/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/Users/chenghong/anaconda3/lib/python3.7/threading.py", line 1029, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```

### Specifications

  - Python Version:3.7
  - Moviepy Version:1.0.0
  - Platform Name:mac
  - Platform Version:

**Comment by tburrows13** [comment]
Sorry, you'll need to provide more code if you want this fixed.

**Comment by tburrows13** [comment]
This can only occur when your clip's `make_frame()` function returns `None`.
