### ISSUE TITLE
videoclip read video file enconter OSError: [Errno 14] Bad address

### ISSUE THREAD

**Issue by RaineyWu** [Zulko/moviepy#1035]
when use moviepy define a videoclip and read file,  enconter OSError: [Errno 14].

### the part of the code 

```
class Swap(object):
    def __init__(self, role_id):
        self.frames = 0
        self.role_id = role_id
        self.role_data_list = []
        self.swaper = None
        self.swaper = self.read_file()
    def convert(self, user_video, role_video, output, t0, randomseed, with_audio):
        self.output = output
        self.user_video = mpe.VideoFileClip(user_video)
        self.role_video = mpe.VideoFileClip(role_video)
        if(int(with_audio)):
            self.user_video.audio.write_audiofile('./'+t0+randomseed+'.mp3')
            role_clip = self.role_video.fl_image(lambda img: self.process_video(img))
            role_clip.write_videofile(self.output, audio='./'+t0+randomseed+'.mp3', audio_codec = 'aac')
            role_clip.reader.close()
            os.remove('./'+t0+randomseed+'.mp3')
        else:
            role_clip = self.role_video.fl_image(lambda img: self.process_video(img))
            role_clip.write_videofile(self.output, audio_codec = 'aac')
            role_clip.reader.close()
```

### the information of the bug return

```
Traceback (most recent call last):
  File "face_convert.py", line 134, in <module>
    convert(user_video='./test_data/test_user13.mp4', role_video=file_name1, role_id = role_id)
  File "face_convert.py", line 24, in convert
    swap.convert(user_video, role_video, output, t0, randomseed, with_audio)
  File "face_convert.py", line 38, in convert
    self.user_video = mpe.VideoFileClip(user_video)
  File "/usr/local/anaconda344/envs/facein927test/lib/python3.6/site-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "/usr/local/anaconda344/envs/facein927test/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "/usr/local/anaconda344/envs/facein927test/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 256, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "/usr/local/anaconda344/envs/facein927test/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/anaconda344/envs/facein927test/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 14] Bad address: '/home/acme-select/.imageio/ffmpeg/ffmpeg-linux64-v3.3.1'
```

### Specifications

  - Python Version: 3.6
  - Moviepy Version: 0.2.3.5 and 1.0.1(have tried both)
  - Imageio Version: 2.4.1

**Comment by tburrows13** [comment]
I would say that this is more of an issue with imageio and its installation of ffmpeg. Check whether the ffmpeg binary at `/home/acme-select/.imageio/ffmpeg/ffmpeg-linux64-v3.3.1` actually exists.

If you (or anyone else) is still having this issue, feel free to reopen this. For now, I will close it.
