### ISSUE TITLE
"AttributeError: 'str' object has no attribute 'copy'" Error 

### ISSUE THREAD

**Issue by Jayydenn** [Zulko/moviepy#1060]
I've been writing a program and I'm a beginner to python but got the hang of it quickly because I have a lot of experience with other languages. I've been getting an error and I have no clue how to fix it. 

It's a program that takes a video and puts the transcript through Cleverbot and makes video responses in between lines. It's part of a project I'm involved in with an aim of controlling a YouTube channel semi-automatically using Python.

_____________________________________________________________________________________________

The full code (it's all over the place, I know):

```
import time
import random
import datetime
import ffmpeg
import ffmpy
from moviepy.editor import *
from selenium import webdriver
import selenium.webdriver.support.ui as ui
from selenium.webdriver.common.keys import Keys
from gtts import gTTS
import os

project_id = random.randint(100000000, 999999999)
os.mkdir(str(project_id))

input_video = VideoFileClip("input.mp4")
game_footage = VideoFileClip("gameplay.mp4")
final_render = input_video.subclip(0, 1)
current_r = input_video.subclip(0, 1)
current_c = input_video.subclip(0, 1)
current_edited = input_video.subclip(0, 1)

browser = webdriver.Chrome("C:\\Users\\jdsee\\Pictures\\chromedriver_win32\\chromedriver.exe")
browser.get("https://www.cleverbot.com/")
input_box = browser.find_element_by_name("stimulus")

with open("venv/data.txt", "r") as my_file:
    data = my_file.readlines()

for line_number in range(0, 3):
    line_time_1 = line_number * 2
    line_string_1 = line_number * 2 + 1
    line_time = data[line_time_1]
    line_string = data[line_string_1]
    if line_number == 0:
        start_time_v = "0:00"
        end_time_v = data[2]
    else:
        start_time_v = data[line_number * 2]
        end_time_v = data[line_number * 2 + 2]
    time_string_s = "00:" + start_time_v.rstrip() + ",00"
    time_string_e = "00:" + start_time_v.rstrip() + ",00"
    ts1 = datetime.datetime.strptime(time_string_s, "%H:%M:%S,%f")
    s_seconds = 60 * ts1.minute + ts1.second
    ts2 = datetime.datetime.strptime(time_string_e, "%H:%M:%S,%f")
    e_seconds = 60 * ts2.minute + ts2.second
    print(line_number, line_time, line_string)
    time.sleep(2)
    input_box.send_keys(line_string)
    time.sleep(5)
    output_text_1 = browser.find_element_by_id("line1")
    output_text = output_text_1.text
    print(output_text)
    speech = gTTS(text=output_text, lang='en', slow=False)
    speech.save(str(project_id) + "/tts" + str(line_number) + ".mp3")
    current_edited = input_video.subclip(s_seconds, e_seconds)
    current_c = game_footage.subclip(0, 5).set_audio(str(project_id) + "/tts" + str(line_number) + ".mp3")
    current_r = input_video.subclip(0, 1)
    if line_number == 0:
        current_r = concatenate_videoclips([current_edited.set_start(0), current_c.set_start(0)])
    else:
        current_r_new = concatenate_videoclips([current_r.set_start(0), current_edited.set_start(0), current_c.set_start(0)])
        current_r = current_r_new
    final_render = current_r

final_render.write_videofile(project_id + "/output.mp4", codec="libx264", audio_codec="mp3")
print("rendered " + project_id)
```
________________________________________________________________________________________________
**Error:**
 
```
 Traceback (most recent call last):

  File "C:/Users/jdsee/PycharmProjects/testfirst/app.py", line 61, in <module>
    current_r = concatenate_videoclips([current_edited.set_start(0), current_c.set_start(0)])
  File "<C:\Users\jdsee\PycharmProjects\testfirst\venv\lib\site-packages\decorator.py:decorator-gen-15>", line 2, in set_start
  File "C:\Users\jdsee\PycharmProjects\testfirst\venv\lib\site-packages\moviepy\decorators.py", line 29, in apply_to_mask
    newclip = f(clip, *a, **k)
  File "<C:\Users\jdsee\PycharmProjects\testfirst\venv\lib\site-packages\decorator.py:decorator-gen-14>", line 2, in set_start
  File "C:\Users\jdsee\PycharmProjects\testfirst\venv\lib\site-packages\moviepy\decorators.py", line 43, in apply_to_audio
    newclip.audio = f(newclip.audio, *a, **k)
  File "<C:\Users\jdsee\PycharmProjects\testfirst\venv\lib\site-packages\decorator.py:decorator-gen-13>", line 2, in set_start
  File "C:\Users\jdsee\PycharmProjects\testfirst\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "<C:\Users\jdsee\PycharmProjects\testfirst\venv\lib\site-packages\decorator.py:decorator-gen-12>", line 2, in set_start
  File "C:\Users\jdsee\PycharmProjects\testfirst\venv\lib\site-packages\moviepy\decorators.py", line 13, in outplace
    newclip = clip.copy()
AttributeError: 'str' object has no attribute 'copy' 
```
________________________________________________________________________________________

Let me know if you found why this is, thanks!

(P.S. If you're going to run it, make sure you have a "data.txt" file in this format: 
"00:00
Insert Text
00:01
Example
00:02
Also make sure
00:03
There are at least 4 lines"
and 2 video files ("input.mp4" and "gameplay.mp4", can be anything)

**Comment by shin-illua** [comment]
It may have been 9 days have passed, but could you properly format the code? You know it's python and indentations are very important.

**Comment by tburrows13** [comment]
Your issue is that you are setting the audio of `current_c` to a string. You need to create an `AudioFileClip` from that string first.
