### ISSUE TITLE
TextClip filenotfounderror winerror2

### ISSUE THREAD

**Issue by jpinela** [Zulko/moviepy#1080]
Hello Everyone,

when running the following code, I get the following error:
```
>>> # Import everything needed to edit video clips
... from moviepy.editor import *
>>> # Load myHolidays.mp4 and select the subclip 00:00:50 - 00:00:60
... clip = VideoFileClip("daniela_luz01.mp4").subclip(50,60)
>>> # Reduce the audio volume (volume x 0.8)
... clip = clip.volumex(0.8)
>>> # Generate a text clip. You can customize the font, color, etc.
... txt_clip = TextClip("My Holidays 2013",fontsize=70,color='white')
Traceback (most recent call last):
  File "C:\Python\Python37\lib\site-packages\moviepy\video\VideoClip.py", line 1168, in __init__
    subprocess_call(cmd, logger=None)
  File "C:\Python\Python37\lib\site-packages\moviepy\tools.py", line 46, in subprocess_call
    proc = sp.Popen(cmd, **popen_params)
  File "C:\Python\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Python\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] O sistema não conseguiu localizar o ficheiro especificado

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Python\Python37\lib\site-packages\moviepy\video\VideoClip.py", line 1177, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

[WinError 2] O sistema não conseguiu localizar o ficheiro especificado.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the I
mageMagick binary in file conf.py, or that the path you specified is incorrect
```

I have googled to search for the solution.
I get a lot of config_defaults.py (file which I don't have) solutions, policy.xml (which I have everything commented out by default) and so forth.

But not even the following test works.
```
magick wizard: wizard.jpg
```
it doesn't give any errors, just doesn't do anything.

I am using python 3.7
windows 7 64bits
and moviepy D:\Programas2\ImageMagick-7.0.9-Q16

Any help is much apprecciated.
Thank you.

**Comment by jpinela** [comment]
update:

ok, the last part was my bad. this is working
`magick wizard.jpg win:`

but still getting the WinError 2 

:(

**Comment by jpinela** [comment]
and my PATH does include the imagemagick path.

**Comment by jpinela** [comment]
found the problem......
config_defaults.py was not supposed to be in the imagemagick folder.
it was in 
`C:\Python\Python37\Lib\site-packages\moviepy`
as described in
[https://github.com/Zulko/moviepy/issues/378]

;)

**Comment by tburrows13** [comment]
Sounds like you sorted it, well done!
