### ISSUE TITLE
not detecting ImageMagick  with moviepy

### ISSUE THREAD

**Issue by iPurya** [Zulko/moviepy#1093]
- Python Version: 3.6.8
  - Moviepy Version: 1.0.0
  - Platform Name: centos
  - Platform Version: 7

hi,
i install ImageMagick with :
`yum install ImageMagick`
and installed successfully...

buy when i use TextClip in my code i get this error :

Traceback (most recent call last):
  File "/root/test/lib/python3.6/site-packages/moviepy/video/VideoClip.py", line 1161, in __init__
    subprocess_call(cmd, logger=None)
  File "/root/test/lib/python3.6/site-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: convert: not authorized `@/tmp/tmpydiqizhm.txt' @ error/constitute.c/ReadImage/454.
convert: no images defined `PNG32:/tmp/tmpse3vs54o.png' @ error/convert.c/ConvertImageCommand/3046.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 7, in <module>
    txt_clip = ( TextClip("My Holidays 2013")
  File "/root/test/lib/python3.6/site-packages/moviepy/video/VideoClip.py", line 1170, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

convert: not authorized `@/tmp/tmpydiqizhm.txt' @ error/constitute.c/ReadImage/454.
convert: no images defined `PNG32:/tmp/tmpse3vs54o.png' @ error/convert.c/ConvertImageCommand/3046.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

**Comment by tburrows13** [comment]
Hello,
Does https://github.com/Zulko/moviepy/issues/401#issuecomment-278679961 solve your issue?

**Comment by keikoro** [comment]
Closing due to inactivity. Feel free to reopen and update us with more info if the problem persists.
