### ISSUE TITLE
I'm not able to use "CompositeVideoClip" with audio set to True 

### ISSUE THREAD

**Issue by AlanHJH** [Zulko/moviepy#1095]
**Hello guys**,

I'm building a script for automating my video editing process, it essentially gets a number of videos of a folder in this case **"videosBase"**, the videos are all **".mp4"**  and are numerated like **"1.mp4, 2.mp4, 3.mp4..."**, then it puts the videos in order inside the list **"videos"**_(this is done in the first **"while"**)_, next it puts a background image  on this clips because some of them are smaller than the final video format _(this is done in the first for loop with the function **"CompositeVideoClip"**)_ , and finally in the third step it  concatenate all the clips with the background and add the intro    
the code is below:
```
from moviepy.editor import *

def faz_videos(inicio, fim):
    counter  = inicio
    videos = []
    print("Comecando a listar os videos")
    while counter <= fim:
        videos.append(VideoFileClip("./videosBase/"+str(counter)+".mp4"))
        print("listando:"+str(counter))
        counter = counter + 1

    videos_com_fundo = []
    print("comecando a adicionar os fundos")
    for clip in videos:
        print("add fundo")
        videos_com_fundo.append(CompositeVideoClip([ImageClip("./sources/bgcomcor.png").resize((720,480)).set_duration(clip.duration).volumex(0), clip.set_position("center")]))
    print("finalizado add fundos")

    composicao_final = []
    intro = VideoFileClip("./intro/intro.mp4").resize((720,480))
    composicao_final.append(intro)
    print("iniciando composicao final")
    for clip_com_fundo in videos_com_fundo:
        composicao_final.append(clip_com_fundo)
        print("compos")

    print("iniciando concatenate")
    concatenate(composicao_final).write_videofile("new_clip.mp4",write_logfile=True )

faz_videos(1,3)
```
And when i compile the program i get this error:
```
Moviepy - Building video new_clip.mp4.
MoviePy - Writing audio in new_clipTEMP_MPY_wvf_snd.mp3
chunk:   7%|█████▋                                                                              | 281/4162 [00:00<00:05, 733.87it/s, now=None]Traceback (most recent call last):
  File "VideoManipulator.py", line 30, in <module>
    faz_videos(1,3)
  File "VideoManipulator.py", line 28, in faz_videos
    concatenate(composicao_final).write_videofile("new_clip.mp4",write_logfile=True )
  File "</home/alan/.local/lib/python3.7/site-packages/decorator.py:decorator-gen-51>", line 2, in write_videofile
  File "/usr/local/lib/python3.7/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "</home/alan/.local/lib/python3.7/site-packages/decorator.py:decorator-gen-50>", line 2, in write_videofile
  File "/usr/local/lib/python3.7/dist-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "</home/alan/.local/lib/python3.7/site-packages/decorator.py:decorator-gen-49>", line 2, in write_videofile
  File "/usr/local/lib/python3.7/dist-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/video/VideoClip.py", line 317, in write_videofile
    logger=logger)
  File "</home/alan/.local/lib/python3.7/site-packages/decorator.py:decorator-gen-73>", line 2, in write_audiofile
  File "/usr/local/lib/python3.7/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/AudioClip.py", line 209, in write_audiofile
    logger=logger)
  File "</home/alan/.local/lib/python3.7/site-packages/decorator.py:decorator-gen-70>", line 2, in ffmpeg_audiowrite
  File "/usr/local/lib/python3.7/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 169, in ffmpeg_audiowrite
    logger=logger):
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/AudioClip.py", line 85, in iter_chunks
    fps=fps, buffersize=chunksize)
  File "</home/alan/.local/lib/python3.7/site-packages/decorator.py:decorator-gen-72>", line 2, in to_soundarray
  File "/usr/local/lib/python3.7/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/AudioClip.py", line 126, in to_soundarray
    snd_array = self.get_frame(tt)
  File "</home/alan/.local/lib/python3.7/site-packages/decorator.py:decorator-gen-10>", line 2, in get_frame
  File "/usr/local/lib/python3.7/dist-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/AudioClip.py", line 296, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/AudioClip.py", line 297, in <listcomp>
    if (part is not False)]
  File "</home/alan/.local/lib/python3.7/site-packages/decorator.py:decorator-gen-10>", line 2, in get_frame
  File "/usr/local/lib/python3.7/dist-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/AudioClip.py", line 296, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/AudioClip.py", line 297, in <listcomp>
    if (part is not False)]
  File "</home/alan/.local/lib/python3.7/site-packages/decorator.py:decorator-gen-10>", line 2, in get_frame
  File "/usr/local/lib/python3.7/dist-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/io/AudioFileClip.py", line 78, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/io/readers.py", line 184, in get_frame
    self.buffer_around(fr_max)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/io/readers.py", line 238, in buffer_around
    array = self.read_chunk(chunksize)
  File "/usr/local/lib/python3.7/dist-packages/moviepy/audio/io/readers.py", line 112, in read_chunk
    s = self.proc.stdout.read(L)
AttributeError: 'NoneType' object has no attribute 'stdout'
```
The thing is that when i set the audio to "False" it works perfectly(with the CompositeVideoClip), it also work perfectly when i don't use the "CompositeVideoClip" function(with audio=True), so for example, this case is fine for me:
```
from moviepy.editor import *

def faz_videos(inicio, fim):
    counter  = inicio
    videos = []
    print("Comecando a listar os videos")
    while counter <= fim:
        videos.append(VideoFileClip("./videosBase/"+str(counter)+".mp4"))
        print("listando:"+str(counter))
        counter = counter + 1

    videos_com_fundo = []
    print("comecando a adicionar os fundos")
    for clip in videos:
        print("add fundo")
        videos_com_fundo.append(clip.set_position("center").resize((720,480)))
    print("finalizado add fundos")

    composicao_final = []
    intro = VideoFileClip("./intro/intro.mp4").resize((720,480))
    composicao_final.append(intro)
    print("iniciando composicao final")
    for clip_com_fundo in videos_com_fundo:
        composicao_final.append(clip_com_fundo)
        print("compos")

    print("iniciando concatenate")
    concatenate(composicao_final).write_videofile("new_clip.mp4",write_logfile=True )

faz_videos(1,3)
```
and also this case is fine:
```
from moviepy.editor import *

def faz_videos(inicio, fim):
    counter  = inicio
    videos = []
    print("Comecando a listar os videos")
    while counter <= fim:
        videos.append(VideoFileClip("./videosBase/"+str(counter)+".mp4"))
        print("listando:"+str(counter))
        counter = counter + 1

    videos_com_fundo = []
    print("comecando a adicionar os fundos")
    for clip in videos:
        print("add fundo")
        videos_com_fundo.append(CompositeVideoClip([ImageClip("./sources/bgcomcor.png").resize((720,480)).set_duration(clip.duration).volumex(0), clip.set_position("center")]))
    print("finalizado add fundos")

    composicao_final = []
    intro = VideoFileClip("./intro/intro.mp4").resize((720,480))
    composicao_final.append(intro)
    print("iniciando composicao final")
    for clip_com_fundo in videos_com_fundo:
        composicao_final.append(clip_com_fundo)
        print("compos")

    print("iniciando concatenate")
    concatenate(composicao_final).write_videofile("new_clip.mp4",audio=False)

faz_videos(1,3)
```
Below is the log file that is generated(new_clipTEMP_MPY_wvf_snd.mp3.log):
```
ffmpeg version 4.1.4-1build2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9 (Ubuntu 9.2.1-4ubuntu1)
  configuration: --prefix=/usr --extra-version=1build2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Guessed Channel Layout for Input Stream #0.0 : stereo
Input #0, s32le, from 'pipe:':
  Duration: N/A, bitrate: 2822 kb/s
    Stream #0:0: Audio: pcm_s32le, 44100 Hz, stereo, s32, 2822 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s32le (native) -> mp3 (libmp3lame))
Output #0, mp3, to 'new_clipTEMP_MPY_wvf_snd.mp3':
  Metadata:
    TSSE            : Lavf58.20.100
    Stream #0:0: Audio: mp3 (libmp3lame), 44100 Hz, stereo, s32p
    Metadata:
      encoder         : Lavc58.35.100 libmp3lame
size=     228kB time=00:00:14.52 bitrate= 128.4kbits/s speed=40.9x    
video:0kB audio:227kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.108676%
```

**Comment by tburrows13** [comment]
Fixed in #1185, MoviePy v1.0.3.
