### ISSUE TITLE
Image Magick can't be found

### ISSUE THREAD

**Issue by maikeeb** [Zulko/moviepy#1107]
I am trying to follow a tutorial I found on youtube and all this did for him was add a 3 second clip before the mp4 of a white background with red text of 'my movie' in the middle.

```
from moviepy.editor import *

movie = VideoFileClip("my_video.mp4")

title = TextClip("My Movie", color='red', size=(1920, 1080), bg_color='white', fontsize=30)
titleclip = title.set_duration(3)
render = concatenate_videoclips([titleclip, movie])
render.write_videofile('render.mp4', fps=30)

```
When I run this code it gets an error and this is the error message that I get in pycharm.

```
Traceback (most recent call last):
  File "\venv\lib\site-packages\moviepy\video\VideoClip.py", line 1168, in __init__
    subprocess_call(cmd, logger=None)
  File "\venv\lib\site-packages\moviepy\tools.py", line 46, in subprocess_call
    proc = sp.Popen(cmd, **popen_params)
  File "\Python\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "\Python\Python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/transition.py", line 5, in <module>
    title = TextClip("My Movie", color='red', size=(1920, 1080), bg_color='white', fontsize=30)
  File "\venv\lib\site-packages\moviepy\video\VideoClip.py", line 1177, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

[WinError 2] The system cannot find the file specified.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

Process finished with exit code 1


```

### Specifications

  - Python Version: 3.7
  - Moviepy Version:1.0.1
  - Platform Name: Windows

**Comment by mgaitan** [comment]
Have you installed ImageMagick and followed the instructions in the README?
Check this please,  https://github.com/Zulko/moviepy#optional-but-useful-dependencies

**Comment by maikeeb** [comment]
I followed the instructions until the point of finding the convert.exe file, I can't find it the image magickk folder in my program files.

**Comment by maikeeb** [comment]
I fixed the problem thanks for sending me the documentation.

I found out that the convert.exe file comes with the legacy utilities.
