### ISSUE TITLE
example "moving_letters.py" fails when changing color from "white" to "blue"

### ISSUE THREAD

**Issue by ghistes** [Zulko/moviepy#1117]
The example script "moving_letters.py" fails when the text-color is changed from "white" to "blue".

### Expected Behavior

The video is rendered with blue text.

### Actual Behavior

An exception is thrown:

```
Traceback (most recent call last):
  File "moving_letters.py", line 70, in <module>
    for funcpos in [vortex, cascade, arrive, vortexout]
  File "moving_letters.py", line 70, in <listcomp>
    for funcpos in [vortex, cascade, arrive, vortexout]
  File "/home/mh/pymods/moviepy/video/compositing/CompositeVideoClip.py", line 94, in __init__
    self.duration = max(ends)
ValueError: max() arg is an empty sequence
```

### Steps to Reproduce the Problem

In moving_letters.py change

```
txtClip = TextClip(                                                                                      
    "Cool effect", color="white", font="Amiri-Bold", kerning=5, fontsize=100                              
) 
```

to

```
txtClip = TextClip(                                                                                      
    "Cool effect", color="blue", font="Amiri-Bold", kerning=5, fontsize=100                              
) 
```

### Specifications

  - Python Version: 3.7.2
  - Moviepy Version: 1.0.1
  - Platform Name: Linux
  - Platform Version: Debian testing

**Comment by tburrows13** [comment]
Thank you for the bug report. I can confirm that it doesn't work for any colour other than "white". Investigating now...

**Comment by tburrows13** [comment]
Ok, the issue is in `segmenting.findObjects()`, which is used to detect the letters. If the letter colour is too close to the background colour then it cannot detect them, so it passes an empty list of clips to `CompositeVideoClip` in line 69, causing the crash. Setting `color="gray"` to TextClip works, because gray is sufficiently distinguishable from black (the background).

Seeing as `findObjects` just uses `scipy.ndimage.label`, there is nothing that we can do to improve the object detection, so you need to find a suitable color/background color combination that Scipy can detect objects on (use `TextClip.list('color')` for a list of available colors that ImageMagick can use - I know that `'lightblue'` works), or use a different approach such as creating each letter as a `TextClip` individually and then managing their animations yourself. (Let us know if you need help with that.

Good luck!

**Comment by ODtian** [comment]
@tburrows13 same issue, and i'm starting manage text by my self, It is annoing because of layout(wrap, align, etc.), is there any powerful way to calculate x and y ? I really need help with it!

**Comment by ODtian** [comment]
```
class Layout:
    def __init__(self, screen_size, space=(0, 0), align='center', inline='center', sticky=('center', 'center')):
        self.box = []
        self.max_width = 0
        self.max_height = {}
        self.align = align
        self.inline = inline
        self.space_x, self.space_y = space
        self.screen_size = screen_size
        self.sticky = sticky

    def add_box(self, size, row, col):
        if col+1 > len(self.box):
            self.box += [[] for _ in range(col+1-len(self.box))]
        if row+1 > len(self.box[col])-1:
            self.box[col] += [None for _ in range(row+1-len(self.box[col]))]
        self.box[col][row] = size
        self.max_width = self._get_max_width()
        self.max_height[str(col)] = self._get_max_height(col)
        return self

    def get_pos(self, row, col):
        w, h = self.box[col][row]
        max_width = self.max_width
        max_height = self.max_height[str(col)]
        total_width = sum(
            [l[0]+self.space_x for l in self.box[col]]) - self.space_x
        x = sum([l[0]+self.space_x for l in self.box[col][:row]])
        if self.align == 'right':
            x += max_width - total_width
        elif self.align == 'center':
            x += ((max_width - total_width) / 2)
        elif self.align == 'around':
            space = (max_width - total_width) / (len(self.box[col])*2)
            x += (space*(2*row-1))
        elif self.align == 'between':
            space = (max_width - total_width) / (len(self.box[col])-1)
            x += (space*(row-1))
        y = sum([self.max_height[str(i)] +
                 self.space_y for i in range(col)]) - self.space_y
        if self.inline == 'end':
            y += max_height - h
        elif self.align == 'center':
            y += ((max_height - h) / 2)
        return (x, y)

    def get_screenpos(self, row, col):
        x, y = self.get_pos(row, col)
        w, h = self.get_size()
        screen_x, screen_y = self.screen_size
        x_sticky, y_sticky = self.sticky

        if isinstance(x_sticky, str):
            if x_sticky == 'center':
                x += ((screen_x - w) / 2)
            elif x_sticky == 'right':
                x += screen_x - w
        elif isinstance(x_sticky, int):
            x += x_sticky
        if isinstance(y_sticky, str):
            if y_sticky == 'center':
                y += ((screen_y - h) / 2)
            elif y_sticky == 'bottom':
                y += screen_y - h
        elif isinstance(y_sticky, int):
            y += y_sticky
        return (x, y)

    def get_size(self):
        w = self.max_width
        h = sum([h+self.space_y for h in self.max_height.values()])\
            - self.space_y
        return (w, h)

    def _get_max_width(self):
        max_width = 0
        for col in self.box:
            width = sum([r[0]+self.space_x for r in col]) - self.space_x
            max_width = max(max_width, width)
        return max_width

    def _get_max_height(self, col):
        max_height = 0
        for r in self.box[col]:
            h = r[1]
            max_height = max(max_height, h)
        return max_height
```
it is what i'm working, a simple flex layout(maybe). Please tell me how this looks and how it works
