### ISSUE TITLE
NameError: global name 'clip' is not defined

### ISSUE THREAD

**Issue by tballas** [Zulko/moviepy#114]
Hello,
First I want to say Moviepy is freaking magic! Thank you for making it!

Platform: Windows 7 64bit, Python 2.7.9

Issue:

```python
Traceback (most recent call last):
  File "soccer_cuts.py", line 18, in <module>
    volumes = [volume(cut(i)) for i in range(0,int(clip.audio.duration-2))]
  File "soccer_cuts.py", line 16, in <lambda>
    cut = lambda i: clip.audio.subclip(i,i+1).to_soundarray(fps=22000)
  File "<string>", line 2, in to_soundarray
  File "C:\Python27\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "C:\Python27\lib\site-packages\moviepy\audio\AudioClip.py", line 116, in to_soundarray
    tt = np.arange(0,clip.duration, 1.0/fps)
NameError: global name 'clip' is not defined
```

"clip" was not capitalized in line 116 of C:\Python27\lib\site-packages\moviepy\audio\AudioClip.py

I edited that to be consistent with the rest of the file: I changed:
from:
```python
                tt = np.arange(0,clip.duration, 1.0/fps)
```
to:
```python
                tt = np.arange(0,Clip.duration, 1.0/fps)
```

which gave this on the output:

```python
Traceback (most recent call last):
  File "soccer_cuts.py", line 18, in <module>
    volumes = [volume(cut(i)) for i in range(0,int(inputvideoclip.audio.duration-2))]
  File "soccer_cuts.py", line 16, in <lambda>
    cut = lambda i: inputvideoclip.audio.subclip(i,i+1).to_soundarray(fps=22000)
  File "<string>", line 2, in to_soundarray
  File "C:\Python27\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "C:\Python27\lib\site-packages\moviepy\audio\AudioClip.py", line 116, in to_soundarray
    tt = np.arange(0,Clip.duration, 1.0/fps)
AttributeError: class Clip has no attribute 'duration'
```
I looked at the C:\Python27\lib\site-packages\moviepy\audio\AudioClip.py file closer and I changed:
from:
```python
                tt = np.arange(0,Clip.duration, 1.0/fps)
```
to:
```python
                tt = np.arange(0,self.duration, 1.0/fps)
```

and It works now!

Did I mention that Moviepy is AMAZING? :)

**Comment by Zulko** [comment]
Thanks for the bug report and for the fix !

I can't believe this bug hadn't been reported yet. I'll correct that.

**Comment by tballas** [comment]
No problem. Glad to help!

**Comment by Zulko** [comment]
Fixed. Thanks for this !
