### ISSUE TITLE
OSError - WinError 6 - Python 3.7.4 (32 bit)

### ISSUE THREAD

**Issue by Kaszanas** [Zulko/moviepy#1194]
### Expected Behavior
```
open_file = VideoFileClip('valid\path\to\file.mp4')
```

### Actual Behavior
Error which is shown below

### Steps to Reproduce the Problem
It is not clear on how to exactly reproduce that issue.
I am using a rapid succession of opening files to extract metadata from them and I am also closing them right after getting what I need with `open_file.close()` which should effectively free up resources.

### Stack Trace:
```
raised unexpected: OSError(9, 'Nieprawidłowe dojście', None, 6, None)
Traceback (most recent call last):
  File "c:\envs\audiovideopy\lib\site-packages\celery\app\trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "c:\envs\audiovideopy\lib\site-packages\celery\app\trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "Y:\Projects\AudioVideoPy\TheVi_Django\uploadapp\tasks\highlights_tasks\generate_highlights.py", line 181, in generate_highlights_celery_task
    is_generated=True).save()
  File "c:\envs\audiovideopy\lib\site-packages\django\db\models\base.py", line 746, in save
    force_update=force_update, update_fields=update_fields)
  File "c:\envs\audiovideopy\lib\site-packages\django\db\models\base.py", line 795, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "c:\envs\audiovideopy\lib\site-packages\django\dispatch\dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "c:\envs\audiovideopy\lib\site-packages\django\dispatch\dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "Y:\Projects\AudioVideoPy\TheVi_Django\uploadapp\receivers.py", line 51, in extract_video_metadata
    open_file = VideoFileClip(instance.file.path)
  File "c:\envs\audiovideopy\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "c:\envs\audiovideopy\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "c:\envs\audiovideopy\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 258, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "C:\Python\lib\subprocess.py", line 664, in __init__
    _cleanup()
  File "C:\Python\lib\subprocess.py", line 228, in _cleanup
    res = inst._internal_poll(_deadstate=sys.maxsize)
  File "C:\Python\lib\subprocess.py", line 1216, in _internal_poll
    if _WaitForSingleObject(self._handle, 0) == _WAIT_OBJECT_0:
OSError: [WinError 6] Nieprawidłowe dojście
```

### Specifications

  - Python Version: 3.7.4 (32 bit)
  - Moviepy Version: `moviepy==1.0.0` - as per requirements.txt
  - Platform Name: Windows

**Comment by tburrows13** [comment]
I think that you will find that this has been fixed in version 1.0.3. If not, then I'd like to know! If you were using v1.0.0 because of a critical bug in v1.0.1 and v1.0.2, then that was fixed in v1.0.3.

**Comment by Kaszanas** [comment]
@tburrows13 I had some issues with using newer version of moviepy (I don't know why) and so I haven't upgraded the package for some time.

I guess only way to know is to set up a whole new environment which will have the newest version of moviepy installed. (And hope not much changed between the stuff I use)

**Comment by tburrows13** [comment]
Yes, please do update, and if that gives you other problems, feel free to report them here, or chat on [Gitter](https://gitter.im/movie-py/Lobby).

**Comment by Kaszanas** [comment]
@tburrows13 I am closing this issue as it seems that updating to 1.0.3 fixed the problem.
If it behaves inconsistently in the future I will be sure to let You know!
