### ISSUE TITLE
make_loopable leading to preview clip:AttributeError: 'CompositeAudioClip' object has no attribute 'fps'

### ISSUE THREAD

**Issue by LaoYuanPython** [Zulko/moviepy#1247]
```
clip = VideoFileClip(r"F:\video\WinBasedWorkHard_src.mp4").subclip(0, 10)
newclip = clip.fx(vfx.make_loopable, 3).set_fps(clip.fps)
newclip.write_videofile(r"F:\video\WinBasedWorkHard_loopable.mp4", threads=8)
preview(newclip)
```

#### Expected Behavior
1.The newclip was saved and played accoording my mind;
2.The newclip  can be previewed.

#### Actual Behavior
1.The newclip was saved and played accoording my mind;
2.The newclip   previewed  fail,erro message as following:

```
Moviepy - video ready F:\video\WinBasedWorkHard_loopable.mp4
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "<decorator-gen-128>", line 2, in preview
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 56, in requires_duration
    return f(clip, *a, **k)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\audio\io\preview.py", line 48, in preview
    sndarray = clip.to_soundarray(tt, nbytes=nbytes, quantize=True)
  File "<decorator-gen-44>", line 2, in to_soundarray
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 56, in requires_duration
    return f(clip, *a, **k)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\audio\AudioClip.py", line 116, in to_soundarray
    fps = self.fps
AttributeError: 'CompositeAudioClip' object has no attribute 'fps'
```

#### Steps to Reproduce the Problem

excute the follwing scripts:
```
clip = VideoFileClip(r"F:\video\WinBasedWorkHard_src.mp4").subclip(0, 10)
newclip = clip.fx(vfx.make_loopable, 3).set_fps(clip.fps)
newclip.write_videofile(r"F:\video\WinBasedWorkHard_loopable.mp4", threads=8)
preview(newclip)
```

#### Specifications

  - Python Version:3.72
  - Moviepy Version:2.0.0.DEV1
  - Platform Name:windows
  - Platform Version:win7 64bit

**Comment by tburrows13** [comment]
This is a bug in CompositeAudioClip where the fps is not being set like it is in CompositeVideoClip. You could probably work around it by doing `newclip.audio = newclip.audio.set_fps(clip.audio.fps)`.

**Comment by LaoYuanPython** [comment]
Thanks very much!
