### ISSUE TITLE
TextClip.list can not decode error  reappeared in Chinese OS and moviepy2.0.0.dev1

### ISSUE THREAD

**Issue by LaoYuanPython** [Zulko/moviepy#1250]
```
 from  moviepy.editor import *
TextClip.search('gb', 'font')
```

#### Expected Behavior
list fonts

#### Actual Behavior
```
Traceback (most recent call last):
  File "F:/study/python/project/moviepyTest/moviepyTest.py", line 45, in <module>
    TextClip.search('gb', 'font')
  File "C:\Program Files\Python37\lib\site-packages\moviepy\video\VideoClip.py", line 1307, in search
    names_list = TextClip.list(arg)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\video\VideoClip.py", line 1283, in list
    result = process.communicate()[0]
  File "C:\Program Files\Python37\lib\subprocess.py", line 926, in communicate
    stdout = self.stdout.read()
  File "C:\Program Files\Python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 66845: invalid start byte
```

1.I query the reported bugs ,found[ #694](https://github.com/Zulko/moviepy/issues/694)、[#1119](https://github.com/Zulko/moviepy/pull/1119) had resolved this problem.The code is listed in ["Followup to TextClip.list() fix (#1119) (#1132)"](https://github.com/Zulko/moviepy/commit/02bcf1a00a912f184d46ea1589e8353d24cc1f0d) . 

2.And the scripts ran correctly  by moviepy1.0.3 .

3.It is recommended to use the following code to get coding type:
```
import locale

codingtype = locale.getdefaultlocale()[1]
```

#### Steps to Reproduce the Problem

execute the scrips in Chinese Windows OS.

#### Specifications

  - Python Version:3.72
  - Moviepy Version:2.0.0dev1
  - Platform Name:windows
  - Platform Version:win7 64bits

**Comment by LaoYuanPython** [comment]
And I had other two questions a few days ago：
1.[How to use manual_tracking and headblur? #1246](https://github.com/Zulko/moviepy/issues/1246)
2.[https://github.com/Zulko/moviepy/issues/1223](https://github.com/Zulko/moviepy/issues/1223)
Would you help me with them?

**Comment by tburrows13** [comment]
Hello, thanks for the report. Would you be able to add `errors="ignore"` to https://github.com/Zulko/moviepy/blob/02bcf1a00a912f184d46ea1589e8353d24cc1f0d/moviepy/video/VideoClip.py#L1239 and see if that fixes your problem?

**Comment by LaoYuanPython** [comment]
Thanks very much! I'm sorry that I've fallen back to version 1.0.3 because 2.0.0 dev1 is not mature yet.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
