### ISSUE TITLE
time_mirror output appeared OSError when access time is negative

### ISSUE THREAD

**Issue by LaoYuanPython** [Zulko/moviepy#1253]
```
if __name__=='__main__':
    clip = VideoFileClip(r"F:\video\WinBasedWorkHard_src.mp4", audio=True).fx(vfx.crop,0, 300, 540, 840)
    newclip = clip.fx(vfx.time_mirror)
    newclip.write_videofile(r"F:\video\WinBasedWorkHard_time_mirror.mp4", threads=8)
```

#### Expected Behavior
Output file success

#### Actual Behavior
```
Moviepy - Building video F:\video\WinBasedWorkHard_time_mirror.mp4.
MoviePy - Writing audio in WinBasedWorkHard_time_mirrorTEMP_MPY_wvf_snd.mp3
chunk:  98%|█████████▊| 1178/1208 [00:21<00:00, 49.13it/s, now=None]Traceback (most recent call last):
  File "F:/study/python/project/moviepyTest/moviepyTest.py", line 7, in <module>
    newclip.write_videofile(r"F:\video\WinBasedWorkHard_time_mirror.mp4", threads=8)
  File "<decorator-gen-61>", line 2, in write_videofile
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 56, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-60>", line 2, in write_videofile
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-59>", line 2, in write_videofile
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 24, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "<decorator-gen-58>", line 2, in write_videofile
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\video\VideoClip.py", line 337, in write_videofile
    logger=logger,
  File "<decorator-gen-47>", line 2, in write_audiofile
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 56, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-46>", line 2, in write_audiofile
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\audio\AudioClip.py", line 241, in write_audiofile
    logger=logger,
  File "<decorator-gen-9>", line 2, in ffmpeg_audiowrite
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 56, in requires_duration
    return f(clip, *a, **k)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\audio\io\ffmpeg_audiowriter.py", line 205, in ffmpeg_audiowrite
    chunksize=buffersize, quantize=True, nbytes=nbytes, fps=fps, logger=logger
  File "C:\Program Files\Python37\lib\site-packages\moviepy\audio\AudioClip.py", line 92, in iter_chunks
    tt, nbytes=nbytes, quantize=quantize, fps=fps, buffersize=chunksize
  File "<decorator-gen-44>", line 2, in to_soundarray
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 56, in requires_duration
    return f(clip, *a, **k)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\audio\AudioClip.py", line 139, in to_soundarray
    snd_array = self.get_frame(tt)
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\Clip.py", line 98, in get_frame
    return self.make_frame(t)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\Clip.py", line 141, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "C:\Program Files\Python37\lib\site-packages\moviepy\Clip.py", line 193, in <lambda>
    lambda gf, t: gf(t_func(t)), apply_to, keep_duration=keep_duration
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Program Files\Python37\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\Clip.py", line 98, in get_frame
    return self.make_frame(t)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 82, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "C:\Program Files\Python37\lib\site-packages\moviepy\audio\io\readers.py", line 185, in get_frame
    + "with clip duration=%f seconds, " % self.duration
OSError: Error in file F:\video\WinBasedWorkHard_src.mp4, Accessing time t=-0.00--0.05 seconds, with clip duration=54.750000 seconds, 
```

#### Steps to Reproduce the Problem

1.Excute the scripts
2.When modify"clip = VideoFileClip(r"F:\video\WinBasedWorkHard_src.mp4", audio=True).fx(vfx.crop,0, 300, 540, 840)"to"clip = VideoFileClip(r"F:\video\WinBasedWorkHard_src.mp4", audio=True).fx(vfx.crop,0, 300, 540, 840).subclip(0,3)",the last line of error message is "OSError: Error in file F:\video\WinBasedWorkHard_src.mp4, Accessing time t=-0.01--0.06 seconds, with clip duration=54.750000 seconds",why  duration=54.750000

I had searched history issues,but not found this error,perhaps is only appered in 2.0.0.dev1?

PS:
Some my issues like 1246,1223,1249 ，Would you like to help me? 
[WinBasedWorkHard_src.zip](https://github.com/Zulko/moviepy/files/4854845/WinBasedWorkHard_src.zip)

#### Specifications

  - Python Version:3.72
  - Moviepy Version:2.0.0.dev1
  - Platform Name:windows
  - Platform Version:win7 64bits

**Comment by tburrows13** [comment]
Thanks for the report. Unfortunately I have no time in the next couple of weeks to help you with your issues, but it is really useful to have them all reported so that I know what next to focus on fixing.

If you were interested, I'd encourage you to look at some of the source code for the problematic functions and try and work out yourself where and why they fail. Being able to fix bugs yourself will make it a lot easier to work with MoviePy :)

**Comment by LaoYuanPython** [comment]
Thank you very much！
I will take into account  your suggestion，but I also have some practical difficulties. First, I am not familiar with the theory of image and audio and video processing. At present, I am learning and testing the moviepy function while searching for relevant materials to understand the relevant functions and theories; Second, although I have spent a lot of time learning moviepy, I still have a lot of work to do. It can be said that the learning and verification of moviepy function takes up almost all my spare time; thirdly, I have not studied the operation of GitHub. I'll try to implement your suggestions in some specific functions, and do some work for the development of moviepy.

**Comment by rishabhvarshney14** [comment]
@tburrows13 in [time_mirror.py](https://github.com/Zulko/moviepy/blob/master/moviepy/video/fx/time_mirror.py) 
changing ```lambda t: clip.duration - t - 1``` to ```lambda t: clip.duration - t``` fixes this problem and results in expected video.

**Comment by tburrows13** [comment]
Interesting! Feel free to make a pull request with that change.

**Comment by bertiebaggio** [comment]
I believe the merge in #1356 to fix this may have caused a regression. I was unable to reverse an mp4, and got the error: `IOError((MoviePy error: failed to read the first fame of "` [sic]

Searching lead me here, and so I reverted the change made in that PR and MoviePy created a video file, although I think the timing is slightly off. That is:

 - `return clip.time_transform(lambda t: clip.duration - t - 1, keep_duration=True)` → creates file
 - `return clip.time_transform(lambda t: clip.duration - t, keep_duration=True)` → "error: failed to read the first fame of "

MoviePy was installed in a virtualenv via `pip install moviepy pygame scikit-image` on Arch. The code is functionally similar to original report: load clip, then apply time_mirror causes an error. I will try to create a synthetic MWE and update here.

Cheers

**Comment by tburrows13** [comment]
@bertiebaggio Nice. Ideally you should use BitmapClip to show reproductions, because then it should be very easy to work out exactly which frame should go where. See the examples in `tests/test_fx.py` for how it gets used.

**Comment by bertiebaggio** [comment]
Yup, my mistake! Apologies

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
