### ISSUE TITLE
OSError: MoviePy error: failed to read the first frame of video file...

### ISSUE THREAD

**Issue by Perzan** [Zulko/moviepy#1323]
#### Steps to Reproduce the Problem

```python
from moviepy.editor import VideoFileClip
from moviepy.video.fx.all import time_mirror

clip = VideoFileClip("original.mp4")

clip = clip.fx(time_mirror)

clip.write_videofile("reversed.mp4")
```

#### Expected Behavior
The source video will be reversed and saved to the specified destination.
According to https://zulko.github.io/moviepy/getting_started/effects.html:
```
More advanced and less common effects like loop (makes the clip play in a loop) or time_mirror (makes the clip play backwards) are placed in the special modules . . .
```

#### Actual Behavior
The following error shows in Command Prompt:

```
Traceback (most recent call last):
  File "reverse.py", line 6, in <module>
    clip = clip.fx(time_mirror)
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\Clip.py", line 212, in fx
    return func(self, *args, **kwargs)
  File "<decorator-gen-89>", line 2, in time_mirror
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-88>", line 2, in time_mirror
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\decorators.py", line 29, in apply_to_mask
    newclip = f(clip, *a, **k)
  File "<decorator-gen-87>", line 2, in time_mirror
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\decorators.py", line 41, in apply_to_audio
    newclip = f(clip, *a, **k)
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\video\fx\time_mirror.py", line 13, in time_mirror
    return self.fl_time(lambda t: self.duration - t, keep_duration=True)
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\Clip.py", line 187, in fl_time
    return self.fl(lambda gf, t: gf(t_func(t)), apply_to,
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\Clip.py", line 136, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-61>", line 2, in set_make_frame
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\video\VideoClip.py", line 644, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\Clip.py", line 187, in <lambda>
    return self.fl(lambda gf, t: gf(t_func(t)), apply_to,
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\video\io\VideoFileClip.py", line 113, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\video\io\ffmpeg_reader.py", line 184, in get_frame
    result = self.read_frame()
  File "C:\Users\<redacted>\AppData\Roaming\Python\Python38\site-packages\moviepy\video\io\ffmpeg_reader.py", line 133, in read_frame
    raise IOError(("MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file original.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
```

#### Specifications

  - Python Version: 3.8.2
  - Moviepy Version: 1.0.3
  - Platform Name: Windows 10 Pro
  - Platform Version: 1909

#### Files
Two files are compressed into [files.zip](https://github.com/Zulko/moviepy/files/5320843/files.zip):
- original.mp4
- reverse.mp4

#### Other Info
If you manage to reverse the video, I am sure you will find it amusing ;)

**Comment by tburrows13** [comment]
Should be fixed in #1220, which is released in v2.0.0.dev2.
