### ISSUE TITLE
Moviepy doesn't seem to load a GIF into memory as it should be.  Pygame Preview seems to affect the GIF in memory

### ISSUE THREAD

**Issue by OneWorld-github** [Zulko/moviepy#1501]
it appears that moviepy loads a gif into memory differently than how it is played.  And previewing the GIF using pygame affects how it is in memory !?! The code below loads a gif into memory, and then extracts frames from the video in memory in order to visualise this phenomenon.

This is the supplied GIF, and is how the video should look.
![funky_otters](https://user-images.githubusercontent.com/19984261/107528313-98179d80-6bb1-11eb-8f58-a07d9314d313.gif)

#### Expected Behavior
If we run the code below with the GIF file supplied and with the #video_clip.preview() uncommented we get these frames:
![otter_frame_0 5](https://user-images.githubusercontent.com/19984261/107529337-ae722900-6bb2-11eb-9daa-c6f402c5148f.png)![otter_frame_1 5](https://user-images.githubusercontent.com/19984261/107529339-af0abf80-6bb2-11eb-8ba2-1360833738b5.png)![otter_frame_2 5](https://user-images.githubusercontent.com/19984261/107529341-afa35600-6bb2-11eb-8041-1ef8d261bd8f.png)![otter_frame_3 5](https://user-images.githubusercontent.com/19984261/107529344-afa35600-6bb2-11eb-92dd-6742ed555e98.png)![otter_frame_4 5](https://user-images.githubusercontent.com/19984261/107529347-afa35600-6bb2-11eb-9995-106f6cadec5d.png)
The frames are all different which represents the dynamic video correctly.

#### Actual Behavior
If we run the code below as is with the GIF file supplied

We get these frames:
![otter_frame_0 5](https://user-images.githubusercontent.com/19984261/107529392-bb8f1800-6bb2-11eb-9921-bdc480066142.png)![otter_frame_1 5](https://user-images.githubusercontent.com/19984261/107529395-bc27ae80-6bb2-11eb-920b-8b4821157490.png)![otter_frame_2 5](https://user-images.githubusercontent.com/19984261/107529397-bc27ae80-6bb2-11eb-9b02-e5d1f14358c1.png)![otter_frame_3 5](https://user-images.githubusercontent.com/19984261/107529399-bcc04500-6bb2-11eb-8f5f-91f4892a8c2c.png)![otter_frame_4 5](https://user-images.githubusercontent.com/19984261/107529401-bcc04500-6bb2-11eb-966a-a3dae0aea3c7.png)
The frames all look the same, as if they represent a static video.  This is not correct.  These frames should all be different.

#### Steps to Reproduce the Problem
```
import os

import moviepy.editor as mped
from PIL import Image

video_clip = mped.VideoFileClip('funky_otters.gif')
#video_clip.preview()
times = [0.5, 1.5, 2.5, 3.5, 4.5]
for time in times:
    frame = video_clip.get_frame(time)
    pil_image = Image.fromarray(frame)
    #pil_image.show()
    os_cwd = os.getcwd()
    pil_image.save(os_cwd + '/otter_frame_{0}.png'.format(time))
```

#### Specifications

  - Python Version:  3.6.9
  - Moviepy Version: 1.0.0
  - Platform Name:  Ubuntu
  - Platform Version: 18.04

**Comment by tburrows13** [comment]
Hello, would you be able to test this with v2.0.0.dev2 please?

**Comment by OneWorld-github** [comment]
Successfully installed moviepy-2.0.0.dev2 numpy-1.19.5
When testing it with this version of moviepy I get the following error message:-

`/..../.pyenv/versions/psworker36/bin/python /..../PycharmProjects/Testing/pygame_preview/moviepy_pygame_preview.py
Traceback (most recent call last):
  File "/..../.pyenv/versions/psworker36/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 341, in ffmpeg_parse_infos
    match = re.findall("([0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9])", line)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/..../PycharmProjects/Testing/pygame_preview/moviepy_pygame_preview.py", line 6, in <module>
    video_clip = mped.VideoFileClip('funky_otters.gif')
  File "</..../.pyenv/versions/psworker36/lib/python3.6/site-packages/decorator.py:decorator-gen-88>", line 2, in __init__
  File "/..../.pyenv/versions/psworker36/lib/python3.6/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/..../.pyenv/versions/psworker36/lib/python3.6/site-packages/moviepy/video/io/VideoFileClip.py", line 109, in __init__
    fps_source=fps_source,
  File "/..../.pyenv/versions/psworker36/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 36, in __init__
    filename, decode_file, print_infos, check_duration, fps_source
  File "/..../.pyenv/versions/psworker36/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 345, in ffmpeg_parse_infos
    f"MoviePy error: failed to read the duration of file {filename}.\nHere are the file infos returned by ffmpeg:\n\n{infos}"
OSError: MoviePy error: failed to read the duration of file funky_otters.gif.
Here are the file infos returned by ffmpeg:

ffmpeg version 4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
  libpostproc    55.  3.100 / 55.  3.100
Input #0, gif, from 'funky_otters.gif':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: gif, bgra, 200x200, 25 fps, 25 tbr, 100 tbn, 100 tbc
At least one output file must be specified


Process finished with exit code 1
`

**Comment by tburrows13** [comment]
Hmm. #1466 reworked the metadata parsing, so that might have fixed your problem. You'd have to use the current master branch to test. If you try that, you'll need https://moviepy-tburrows13.readthedocs.io/en/improve-docs/updating_to_v2.html and #1170 to update your code.

**Comment by OneWorld-github** [comment]
Hmm, why do the images come out the same for each frame ?

I'm not sure the solutions you mentioned above would solve this same frame problem.  
The update suggested seems to be more related to solving the issue that pygame preview affects the clip.  I used pygame preview as a diagnostic tool, I didn't realise that it would change the clip.

**Comment by tburrows13** [comment]
Ok, what happens if instead of `video_clip.preview()` you do `video_clip.write_videofile("outfile.mp4")`? As you say, `preview()` is not supposed to change the clip, so presumably if it is, then `write_videofile` does as well. In fact, I remember an old issue with a similar problem. I'll dig it up, but I'm busy for the next hour or so.

**Comment by OneWorld-github** [comment]
the thing is that if we just do this...

```
import os
import moviepy.editor as mped
from PIL import Image

video_clip = mped.VideoFileClip('funky_otters.gif')
times = [0.5, 1.5, 2.5, 3.5, 4.5]
for time in times:
    frame = video_clip.get_frame(time)
    pil_image = Image.fromarray(frame)
    os_cwd = os.getcwd()
    pil_image.save(os_cwd + '/otter_frame_{0}.png'.format(time))
```

The frames should be different.  But they aren't different, they are all the same.

**Comment by OneWorld-github** [comment]
> Ok, what happens if instead of `video_clip.preview()` you do `video_clip.write_videofile("outfile.mp4")`? As you say, `preview()` is not supposed to change the clip, so presumably if it is, then `write_videofile` does as well. This sounds like #1029?

The same thing happens when I use

video_clip.write_videofile("outfile.mp4")

**Comment by OneWorld-github** [comment]
also if I run this...

`
import os
import moviepy.editor as mped
from PIL import Image

# video_clip = mped.VideoFileClip('funky_otters.gif')
# video_clip.write_videofile("outfile.mp4")
video_clip = mped.VideoFileClip('outfile.mp4')
times = [0.5, 1.5, 2.5, 3.5, 4.5]
for time in times:
    frame = video_clip.get_frame(time)
    pil_image = Image.fromarray(frame)
    #pil_image.show()
    os_cwd = os.getcwd()
    pil_image.save(os_cwd + '/otter_frame_{0}.png'.format(time))
`
all the frames come out identical

**Comment by tburrows13** [comment]
Ok, that sounds like we have a easily replicatable issue then! Would you be able to send funky_otters.gif please? I'll take a look later today.

PS You can use three backticks to format code :)

**Comment by OneWorld-github** [comment]
GIF is here again :-  
![funky_otters](https://user-images.githubusercontent.com/19984261/107537961-61468500-6bbb-11eb-863c-1b77743078a0.gif)

Right click and copy seems to download it for me.

**Comment by tburrows13** [comment]
Brilliant. Sorry I missed that you had already sent it :)
I can definitely replicate the issue

**Comment by OneWorld-github** [comment]
Excellent, thanks Thomas.  Would be interesting to see what the issue is.

**Comment by tburrows13** [comment]
Yeah, this is about as deep down as it goes. I've discovered that you can do `video_clip.reader.initialize(0.5)` to get it to work correctly (but getting the reader to initialise at `0` does not work). You can use that as a temporary workaround if you like.

**Comment by OneWorld-github** [comment]
wait, so you are saying that I can't extract the first frame, but I can extract the frame at above 0 seconds ?

**Comment by tburrows13** [comment]
By default, a clip's reader is initialised to 0, and for whatever reason, it then doesn't work with your get_frame() calls. If you manually initialise it to anything except 0 it appears to work. When you call `write_videofile` and then `get_frame()`, it gets reinitialised to something other than 0, which is why that worked as well.

This works:
```
video_clip = VideoFileClip('funky_otters.gif')
video_clip.reader.initialize(0.1)
times = [0.5, 1.5, 2.5, 3.5, 4.5]
for time in times:
    frame = video_clip.get_frame(time)
    pil_image = Image.fromarray(frame)
    #pil_image.show()
    os_cwd = os.getcwd()
    pil_image.save(os_cwd + '/otter_frame_{0}.png'.format(time))
```

**Comment by OneWorld-github** [comment]
I see, it works down as low as this...

video_clip.reader.initialize(0.05)

but if I use 0.04 it won't work.

**Comment by tburrows13** [comment]
That would be because fps = 25, and 1/fps = 0.04

**Comment by OneWorld-github** [comment]
ah so it can only initialise from the second frame !?

**Comment by tburrows13** [comment]
Actually it works with any initialisation value that isn't a multiple of 0.04. Curious...

**Comment by tburrows13** [comment]
And if you change `times = [0.5, 1.5, 2.4, 3.2, 4.8]` to include multiples of 0.04, then those frames are always wrong, no matter where you initialise it to...

**Comment by tburrows13** [comment]
Ok, this actually isn't that serious. There is some off-by-one-frame error from the ffmpeg command to start at a particular time-stamp (https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ffmpeg_reader.py#L82-L90), which is definitely unwanted behaviour, but it only presents itself as serious because the nature of the gif and the timestamps is that one frame off gives completely different frames.

I'm still trying to work out how to fix the issue.

**Comment by OneWorld-github** [comment]
I can't use video_clip.reader.initialize(0.5) for all media it seems.  Even some other GIFs have issues with this workaround.

AttributeError: 'CompositeVideoClip' object has no attribute 'reader'
AttributeError: 'FFMPEG_VideoReader' object has no attribute 'lastread'
AttributeError: 'FFMPEG_VideoReader' object has no attribute 'lastread'
AttributeError: 'ImageClip' object has no attribute 'reader'
AttributeError: 'ImageSequenceClip' object has no attribute 'reader'

So I can't actually use this.

**Comment by tburrows13** [comment]
You'll have to apply it to all VideoFileClips as soon as you create them, before you composite them. I can't see how the same error would occur in ImageClips? Please post the full code + error if you're still struggling

**Comment by OneWorld-github** [comment]
I'll see what I can do tomorrow.  It's late in the UK now.

**Comment by tburrows13** [comment]
Ok, here's what I've discovered.

Expected values:
t=0, frame index = 0
t = 1/fps, frame index = 1
t = x/fps, frame index = x
t = 1 (= fps/fps), frame index = fps

From my experimenting, `get_frame(1)` by default gives frame index 25, but 26 with `video_clip.reader.initialize(0.05)`. In this case, calling `initialize` gives the wrong result.
`get_frame(0.5)` by default gives frame index 12, but 13 with `video_clip.reader.initialize(0.05)`. In this case, calling `initialize` gives the wrong result.

I guess the case between 12 and 13 is debatable depending on whether you want to floor or ceil the calculated frame index of 12.5 (0.5 * 25). Either way, flooring is how it has always been done in MoviePy, and the case with t=1 demonstrates that floor vs ceil is not the problem here.

The problem is with [seeking to a specific timestamp in ffmpeg](https://github.com/Zulko/moviepy/blob/master/moviepy/video/io/ffmpeg_reader.py#L82-L90). Still investigating what can be done about it.

@OneWorld-github in summary, the output that you are getting with all identical frames is the correct one. You should be getting the frames at 0.52, 1.52 in order to get the output you want.

**Comment by OneWorld-github** [comment]
Well, in that case why would Gitlab Runner read the video as different frames ?

**Comment by tburrows13** [comment]
Not sure what you mean by that?

**Comment by OneWorld-github** [comment]
It makes no sense that all frames identical is a correct video.

**Comment by tburrows13** [comment]
Your gif:

0.5 sec image 1
0.5 sec image 2
0.5 sec image 1
0.5 sec image 3
0.5 sec image 1
etc

Due to the off-by-one error in moviepy, you are either getting the last frame of all of the 'image 1's or the first frame of the 'image 2/3/4...'s. Does that make sense?

**Comment by OneWorld-github** [comment]
It doesn't make sense yet.

are you saying that if I change my timings from
times = [0.5, 1.5, 2.5, 3.5, 4.5]
to
times = [0.4, 1.6, 2.4, 3.6, 4.6]
Then i would see different frames at those time points ?

**Comment by tburrows13** [comment]
Yes. As long as you don't have multiples of 0.5 in your times list, then you won't be a victim of this bug anymore and you'll get consistent results. Any timestamps between 0-0.5, 1-1.5, 2-2.5, 3-3.5 and 4-4.5 will be identical in this specific gif. If you pick a timestamp greater than 4.5 then you'll get a warning and it will repeat the last read frame.

**Comment by OneWorld-github** [comment]
I didn't get a warning with 4.6 !

**Comment by tburrows13** [comment]
Huh, I do. Maybe your warnings are hidden.

**Comment by tburrows13** [comment]
Ok. The issue is in moviepy's initialisation, when the start time for _initialisation_ does not correspond exactly to a frame time. With a 25fps video, in FFmpeg if you seek to <0.005s (5ms) then it returns the 1st frame (index=0). If you seek above between 5ms and 44ms you get the 2nd frame (index=1). MoviePy's code would always round down to the previous index time, so seeking to 40ms would floor to 40ms (correct), but seeking to anywhere between 5 and 39ms would floor to 0ms (incorrect).

A simple floor or ceil in MoviePy will never be 100% accurate (though a ceil would actually be much closer), so I'm going to try and work out how to work out exactly what FFmpeg is doing and replicate that in Python (or read it directly from FFmpeg).

**Comment by mondeja** [comment]
> Ok. The issue is in moviepy's initialisation, when the start time for initialisation does not correspond exactly to a frame time. With a 25fps video, in FFmpeg if you seek to <0.005s (5ms) then it returns the 1st frame (index=0). If you seek above between 5ms and 44ms you get the 2nd frame (index=1). MoviePy's code would always round down to the previous index time, so seeking to 40ms would floor to 40ms (correct), but seeking to anywhere between 5 and 39ms would floor to 0ms (incorrect).

I think that a lot of issues like this happen because users are not editing their videos using a seekable multimedia container like Matroska, so is something that we can't fix in moviepy, as this occurs at FFMPEG level. Take a look at [Seeking in FFMPEG](https://trac.ffmpeg.org/wiki/Seeking) or [this issue](https://trac.ffmpeg.org/ticket/5093) for further information about this.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
