### ISSUE TITLE
OSError: MoviePy error: failed to read the first frame of video with large files

### ISSUE THREAD

**Issue by josebenitezg** [Zulko/moviepy#1536]
Still facing the same error even if I make the upgrade.
When I trying to concatenate videos I am suceed with a small list of videos but when is bigger I face this error:

```
/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py:161: UserWarning: In file video.mkv, 921600 bytes wanted but 0 bytes read,at frame index 0 (out of a total 24 frames), at time 0.00/1.00 sec. Using the last valid frame instead.
  UserWarning,
Traceback (most recent call last):
  File "get_s3.py", line 113, in <module>
    clips.append(VideoFileClip(filename))
  File "<decorator-gen-88>", line 2, in __init__
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/video/io/VideoFileClip.py", line 109, in __init__
    fps_source=fps_source,
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 73, in __init__
    self.initialize()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 131, in initialize
    self.lastread = self.read_frame()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p37/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 166, in read_frame
    "MoviePy error: failed to read the first frame of "
OSError: MoviePy error: failed to read the first frame of video file video.mkv. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.`
```

Is a large list of videos that I am not able to concatenate but when I try other list (small one) I am able to do it.

#### Specifications

  - Python Version:  3.7.10
  - Moviepy Version: 2.0.0.dev2
  - Platform Name: Ubuntu
  - Platform Version: 18.04

**Comment by tburrows13** [comment]
You could try downloading the latest version of moviepy from GitHub. Are you able to upload the file that is causing the crash? You say it is 'bigger' but moviepy is reporting it as 1 second long (and 24 frames)... is that what you were expecting?

**Comment by josebenitezg** [comment]
Yes, that is because I have 190 files to cancatenate but even if I delete that file I still have the same issue

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
