### ISSUE TITLE
Cannot use monochrome images with ImageClip and CompositeVideoClip

### ISSUE THREAD

**Issue by fjahn** [Zulko/moviepy#1664]
This code composes a video by applying and image on top of another video:

```python
clip = VideoFileClip('video.mp4')
image = ImageClip('img.jpg', duration=1)
clip = CompositeVideoClip([clip, image])

clip.write_videofile('result.mp4')
```

### Expected Behavior

I would expect the video to be rendered correctly with all types of images.

### Actual Behavior

If `img.jpg` is a monochrome image, `write_videofile` crashes with the following error:

<details>
<summary>Stracktrace</summary>

```
File "./main.py", line 42, in <module>
  clip.write_videofile('result.mp4')
File "<decorator-gen-55>", line 2, in write_videofile
File "./venv/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
  return f(clip, *a, **k)
File "<decorator-gen-54>", line 2, in write_videofile
File "./venv/lib/python3.8/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
  return f(clip, *new_a, **new_kw)
File "<decorator-gen-53>", line 2, in write_videofile
File "./venv/lib/python3.8/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
  return f(clip, *a, **k)
File "./venv/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
  ffmpeg_write_video(self, filename, fps, codec,
File "./venv/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py", line 220, in ffmpeg_write_video
  for t,frame in clip.iter_frames(logger=logger, with_times=True,
File "./venv/lib/python3.8/site-packages/moviepy/Clip.py", line 472, in iter_frames
  frame = self.get_frame(t)
File "<decorator-gen-11>", line 2, in get_frame
File "./venv/lib/python3.8/site-packages/moviepy/decorators.py", line 89, in wrapper
  return f(*new_a, **new_kw)
File "./venv/lib/python3.8/site-packages/moviepy/Clip.py", line 93, in get_frame
  return self.make_frame(t)
File "./venv/lib/python3.8/site-packages/moviepy/video/compositing/CompositeVideoClip.py", line 111, in make_frame
  f = c.blit_on(f, t)
File "./venv/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 564, in blit_on
  return blit(img, picture, pos, mask=mask, ismask=self.ismask)
File "./venv/lib/python3.8/site-packages/moviepy/video/tools/drawing.py", line 41, in blit
  new_im2[yp1:yp2, xp1:xp2] = blitted
ValueError: could not broadcast input array from shape (400,400) into shape (400,400,3)
```
</details>

If `img.jpg` is a polychromatic (=regular) image, it works just fine.

### Steps to Reproduce the Problem

Here is the image I used for reproducing this:

<details>
<summary>Monocrome JPG</summary>

![img](https://user-images.githubusercontent.com/74260729/134482960-8cb42451-bd4d-4657-ba63-afba1f1a666d.jpg)
</details>

For comparison, this is a polychromatic image, which works just fine with the snippet:

<details>
<summary>Polychrome JPG</summary>

![regular-image](https://user-images.githubusercontent.com/74260729/134484388-4721dd45-6ef3-4f37-9869-71ac52241e68.jpg)
</details>

Here is a more complete code example that generates the base video using the image aswell (the first `write_videofile` works because the image is not composed with anything):

```python
from moviepy.editor import *

image = ImageClip('img.jpg', duration=1)
image.write_videofile('video.mp4', fps=30)

clip = VideoFileClip('video.mp4')
image = ImageClip('img.jpg', duration=1)
clip = CompositeVideoClip([clip, image])

clip.write_videofile('result.mp4')
```

### Hotfix

I have fixed the problem for me by hacking in an fx function that transforms the image for me:

```python
import numpy as np
from moviepy.editor import *


def normalize_image(clip):
    def f(get_frame, t):
        if f.normalized_frame is not None:
            return f.normalized_frame
        else:
            frame = get_frame(t)
            f.normalized_frame = normalize_frame(frame)
            return f.normalized_frame

    f.normalized_frame = None

    return clip.fl(f)


def normalize_frame(frame):
    shape = np.shape(frame)
    [dimensions, ] = np.shape(shape)

    if dimensions == 2:
        (height, width) = shape
        normalized_frame = np.zeros((height, width, 3))
        for y in range(height):
            for x in range(width):
                grey_value = frame[y][x]
                normalized_frame[y][x] = (grey_value, grey_value, grey_value)
        return normalized_frame
    else:
        return frame


image = ImageClip('img.jpg', duration=1)
image.write_videofile('video.mp4', fps=30)

clip = VideoFileClip('video.mp4')
image = ImageClip('img.jpg', duration=1).fx(normalize_image)
clip = CompositeVideoClip([clip, image])

clip.write_videofile('result.mp4')
```

This is, of course, very inefficient, but it fixes the issue for me.

### Specifications

  - Python Version: 3.8.2
  - Moviepy Version: 1.0.3
  - Platform Name: MacOS (M1)
  - Platform Version: 11.4

**Comment by abyesilyurt** [comment]
Can't reproduce on `master` branch.

**Comment by rfschubert** [comment]
I got the same behavior... I'm downloading a random pic from picsum.photos and when I use grayscale it raises this error:

```shell
Traceback (most recent call last):
  File "test.py", line 108, in <module>
    video_maker.make_video()
  File "test.py", line 86, in make_video
    self.generate_video(text, sequential_number)
  File "test.py", line 44, in generate_video
    videoclip.write_videofile("exemplo{}.mp4".format(sequential_number), fps=24)
  File "<decorator-gen-55>", line 2, in write_videofile
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 300, in write_videofile
    ffmpeg_write_video(self, filename, fps, codec,
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_writer.py", line 220, in ffmpeg_write_video
    for t,frame in clip.iter_frames(logger=logger, with_times=True,
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/Clip.py", line 472, in iter_frames
    frame = self.get_frame(t)
  File "<decorator-gen-11>", line 2, in get_frame
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/video/compositing/CompositeVideoClip.py", line 111, in make_frame
    f = c.blit_on(f, t)
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 564, in blit_on
    return blit(img, picture, pos, mask=mask, ismask=self.ismask)
  File "/Users/raphaelschubert/dev/temp/videos/venv/lib/python3.8/site-packages/moviepy/video/tools/drawing.py", line 41, in blit
    new_im2[yp1:yp2, xp1:xp2] = blitted
ValueError: could not broadcast input array from shape (1920,1080) into shape (1920,1080,3)
```

Using the fix above, worked, but yes, very inefficient

**Comment by antistv** [comment]
thx it solve problem

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
