### ISSUE TITLE
8 Bit Depth Images Can't be Cropped

### ISSUE THREAD

**Issue by DegenVideos** [Zulko/moviepy#1667]
#### Expected Behavior
I expect the image to be cropped.

#### Actual Behavior
Following error is thrown:
Traceback (most recent call last):
  File "E:\DegenVideos\Scripts\DegenVideo\VideoMaker.py", line 197, in <module>
    clipList = getImageClipList(ImageDir)
  File "E:\DegenVideos\Scripts\DegenVideo\VideoMaker.py", line 77, in getImageClipList
    clip = crop(clip, width=finalSize[0], height=finalSize[1], x_center=clip.size[0]/2, y_center=clip.size[1]/2)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\fx\crop.py", line 53, in crop
    return clip.fl_image(lambda pic: pic[int(y1) : int(y2), int(x1) : int(x2)], apply_to=["mask"])
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\VideoClip.py", line 490, in fl_image
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\Clip.py", line 136, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-61>", line 2, in set_make_frame
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\VideoClip.py", line 644, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\VideoClip.py", line 490, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 111, in make_frame
    f = c.blit_on(f, t)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\VideoClip.py", line 564, in blit_on
    return blit(img, picture, pos, mask=mask, ismask=self.ismask)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python39\lib\site-packages\moviepy\video\tools\drawing.py", line 41, in blit
    new_im2[yp1:yp2, xp1:xp2] = blitted
ValueError: could not broadcast input array from shape (1080,701) into shape (1080,701,3)

#### Steps to Reproduce the Problem

Input any image with a bit depth of 8. I used several files with a bit depth of 8 and those are the only files that errored out. They were also black and white, but other black and white images worked, however all files with a bit depth of 8 failed with the same error. Not sure why or how it is happening.

```
from moviepy import *

def getReflectedClip(clip, finalSize):
    # If the clip isn't the correct height, change it.
    if(clip.size[1] != finalSize[1]):
        clip = clip.resize(height=finalSize[1])
    # If the clip is less than the crop width, triple it and check again.
    if(clip.size[0] < finalSize[0]):
        reflectClip = clip.fx(vfx.mirror_x)
        clip = clips_array([[clip, clip, reflectClip]])
        return getReflectedClip(clip, finalSize)
    else:
        return clip

def getImageClipList(ImageDir):
    imageList = os.listdir(ImageDir)
    #imageList = imageList[0:60]
    random.shuffle(imageList)
    clipList = []
    for media in imageList:
        filePath = ImageDir + media
        print(filePath)
        if(isdir(filePath)):
            continue
        clip = ImageClip(img=filePath, duration=testDuration)
        
        # Resize, reflect, and crop clips to fill the horizontal black space.
        clip = getReflectedClip(clip, finalSize)
        # If the clip is too small, this will not work correctly.
        print(clip.size)
        clip = crop(clip, width=finalSize[0], x_center=clip.size[0]/2)
```

#### Specifications

  - Python Version: 3.9.7
  - Moviepy Version: 1.0.3
  - Platform Name: Windows
  - Platform Version: 10

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
