### ISSUE TITLE
Moviepy FFMpeg error

### ISSUE THREAD

**Issue by hackedXD** [Zulko/moviepy#1668]
While running Moviepy on FFMpeg, i get the following error
`Moviepy - Building video videos/tommyinnit: "I don't even write essays".mp4.
MoviePy - Writing audio in tommyinnit: "I don't even write essays"TEMP_MPY_wvf_snd.mp3
chunk:   0%|                                                                                             | 0/668 [00:00<?, ?it/s, now=None]Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 74, in write_frames
    self.proc.stdin.write(frames_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/maheshwari782532/Desktop/Youtube-Bot/bot.py", line 80, in <module>
    v.write_videofile("videos/" + clip["broadcaster_name"] + ": " + clip["title"] + ".mp4")
  File "<decorator-gen-55>", line 2, in write_videofile
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 293, in write_videofile
    self.audio.write_audiofile(audiofile, audio_fps,
  File "<decorator-gen-45>", line 2, in write_audiofile
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/AudioClip.py", line 206, in write_audiofile
    return ffmpeg_audiowrite(self, filename, fps, nbytes, buffersize,
  File "<decorator-gen-9>", line 2, in ffmpeg_audiowrite
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 170, in ffmpeg_audiowrite
    writer.write_frames(chunk)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 117, in write_frames
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file tommyinnit: "I don't even write essays"TEMP_MPY_wvf_snd.mp3:

b'tommyinnit: "I don\'t even write essays"TEMP_MPY_wvf_snd.mp3: Protocol not found\n'

In case it helps, make sure you are using a recent version of FFMPEG (the versions in the Ubuntu/Debian repos are deprecated).
Exception ignored in: <function FFMPEG_AudioWriter.__del__ at 0x7fa129cb0670>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 132, in __del__
    self.close()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 121, in close
    self.proc.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe`
how do i fix this?

**Comment by keikoro** [comment]
@hackedXD I'd ask you to reformat your issue so code (or command line output) are distinguishable from what you are asking (i.e. normal text).

**Comment by keikoro** [comment]
Feel free to reopen this issue (or ping me about reopening it) once it's reformatted.

**Comment by taraskuzyk** [comment]
Getting the same issue. Since OP didn't format, he was asking "how do i fix this?", everything else is an error stack.

```
Moviepy - Building video videos/tommyinnit: "I don't even write essays".mp4.
MoviePy - Writing audio in tommyinnit: "I don't even write essays"TEMP_MPY_wvf_snd.mp3
chunk: 0%| | 0/668 [00:00<?, ?it/s, now=None]Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 74, in write_frames
self.proc.stdin.write(frames_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/maheshwari782532/Desktop/Youtube-Bot/bot.py", line 80, in
v.write_videofile("videos/" + clip["broadcaster_name"] + ": " + clip["title"] + ".mp4")
File "", line 2, in write_videofile
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
return f(clip, *a, **k)
File "", line 2, in write_videofile
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/decorators.py", line 135, in use_clip_fps_by_default
return f(clip, *new_a, **new_kw)
File "", line 2, in write_videofile
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
return f(clip, *a, **k)
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/video/VideoClip.py", line 293, in write_videofile
self.audio.write_audiofile(audiofile, audio_fps,
File "", line 2, in write_audiofile
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
return f(clip, *a, **k)
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/AudioClip.py", line 206, in write_audiofile
return ffmpeg_audiowrite(self, filename, fps, nbytes, buffersize,
File "", line 2, in ffmpeg_audiowrite
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/decorators.py", line 54, in requires_duration
return f(clip, *a, **k)
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 170, in ffmpeg_audiowrite
writer.write_frames(chunk)
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 117, in write_frames
raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file tommyinnit: "I don't even write essays"TEMP_MPY_wvf_snd.mp3:

b'tommyinnit: "I don't even write essays"TEMP_MPY_wvf_snd.mp3: Protocol not found\n'

In case it helps, make sure you are using a recent version of FFMPEG (the versions in the Ubuntu/Debian repos are deprecated).
Exception ignored in: <function FFMPEG_AudioWriter.del at 0x7fa129cb0670>
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 132, in del
self.close()
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 121, in close
self.proc.stdin.close()
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by taraskuzyk** [comment]
Update: for me the issue was due to trying to save the audio into an mp4 file. I switched to mp3 and the issue got fixed. My understanding though was that mp4 is a valid format for an audio file?

**Comment by manfye** [comment]
@taraskuzyk  thank you very much, noob me!
