### ISSUE TITLE
Text in TextClip in multiple colors

### ISSUE THREAD

**Issue by przemeczek** [Zulko/moviepy#1747]
Is there a way to display a substring of the text specified in the TextClip constructor in a different color than the rest of the text?
To be clearer, what I want to achieve is this:
1. Say, I have this line of code in my script
txt_clip = TextClip("Text Test",font="Tahoma-Bold", fontsize=70,color='black',stroke_width=5)
2. I want "Text" to be black and "Test" to be red in the final clip. How can I accomplish this?

Thanks!

**Comment by keikoro** [comment]
See #1123 and #1228

**Comment by danilodavid521** [comment]
Say, I use this type of text clip to build movie generator using moviepy.

text = (TextClip(text_label, font_size=60, color='white', font="Arial-Bold")

But this error:

(venv) PS C:\Users\apple\Documents\SaaS\shiftzlanes-app\backend> python generate_video.py
Traceback (most recent call last):
  File "C:\Users\apple\Documents\SaaS\shiftzlanes-app\backend\venv\Lib\site-packages\moviepy\video\VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "C:\Users\apple\Documents\SaaS\shiftzlanes-app\backend\venv\Lib\site-packages\moviepy\tools.py", line 46, in subprocess_call
    proc = sp.Popen(cmd, **popen_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\Python311\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

  File "C:\Users\apple\Documents\SaaS\shiftzlanes-app\backend\generate_video.py", line 45, in <module>
    text = (TextClip(text_label, fontsize=60, color='white', font="Arial-Bold")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\apple\Documents\SaaS\shiftzlanes-app\backend\venv\Lib\site-packages\moviepy\video\VideoClip.py", line 1146, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

[WinError 2] The system cannot find the file specified.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

How to solve this?
Thanks.
