### ISSUE TITLE
OSError: [WinError 6] The handle is invalid

### ISSUE THREAD

**Issue by brisingre** [Zulko/moviepy#1749]
The much-discussed WinError 6 bug is still happening to me. All the threads about it say it's fixed in 1.0.3 and make a new thread if it is still happening, and sadly it is, so here's the new thread! I greatly appreciate any insight into how to work around this, right now my best idea is to see if it works on linux, since it seems to be a windows thing.

#### Expected Behavior
I'm only using two lines of code that interact with MoviePy. I'm not sure which one causes the crash but clipping a video is a pretty simple task. Seems like it should just work.

#### Actual Behavior
Sometimes clipping a video fails with this error. My program makes several clips from the same video and it always seems to fail on the same clip with the same start and end frames, so it isn't random -- but most clips are fine, this error only occurs for specific start and end frames on specific videos. Very odd!

```
Exception ignored in: <function FFMPEG_AudioReader.__del__ at 0x0000027CDD8D3B80>
Traceback (most recent call last):
  File "C:\Users\Lou\PycharmProjects\TvTools\venv\lib\site-packages\moviepy\audio\io\readers.py", line 254, in __del__
    self.close_proc()
  File "C:\Users\Lou\PycharmProjects\TvTools\venv\lib\site-packages\moviepy\audio\io\readers.py", line 149, in close_proc
    self.proc.terminate()
  File "C:\Users\Lou\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1553, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
```

#### Steps to Reproduce the Problem

```
from moviepy.editor import *

def write_clip(path, start, end):
	min_length = 5  # clips shorter than this won't get saved
	if end - start <= min_length:
		return
	video_path = path
	stem = Path(path).stem
	frame_rate = 23.976216
	start_time = start / frame_rate
	end_time = end / frame_rate

	video = VideoFileClip(video_path).subclip(start_time, end_time)
	video.write_videofile("{0} frames {1} to {2}.mp4".format(stem, start, end), fps=frame_rate)
```

This code will fail some of the time

#### Specifications

  - Python Version: 3.9.4
  - Moviepy Version: 1.0.3
  - Platform Name: Windows
  - Platform Version: 10 LTSC

**Comment by brisingre** [comment]
Can verify that it only happens on windows, if that is helpful. It seems like it might be happening as my program exits, and not actually immediately after a call to moviepy, but I am not 100% sure of that.

**Comment by Trolann** [comment]
I have the same behavior, same error traceback and very similar code to @brisingre. I run the same code on my Ubuntu system and it performs just fine. I also see it happened as MoviePy is finishing some kind of processing but it doesn't write the new video file.


Python Version: 3.10.2
Moviepy Version: 1.0.3
Platform Name: Windows
Platform Version: 10 LTSC

Traceback:
`Exception ignored in: <function FFMPEG_AudioReader.__del__ at 0x00000292C081D900>
Traceback (most recent call last):
  File "G:\My Drive\Code\sponsorblock-dl\venv\lib\site-packages\moviepy\audio\io\readers.py", line 254, in __del__
    self.close_proc()
  File "G:\My Drive\Code\sponsorblock-dl\venv\lib\site-packages\moviepy\audio\io\readers.py", line 149, in close_proc
    self.proc.terminate()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2544.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1573, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid`

Code:
`def process_video(video_location, block_list, video_title) -> None:
    """
    Processes a single video given a list of block Segments.
    :param video_title:
    :param video_location:
    :param block_list:
    :return:
    """
    clips = list()

    last_time = 0
    logging.info(f'Processing {len(block_list)} blocks for {video_title}')
    video_end = VideoFileClip(video_location).end # Need the overall video length

    for i, ad_read in enumerate(block_list): # For each block
        # Make the audio clip
        audio = AudioFileClip(video_location)
        audio = audio.cutout(int(ad_read.start), video_end)
        audio = audio.cutout(0, last_time)
        logging.info(f'Got audio starting at {last_time} until {ad_read.start}')

        # Make the video clip and then set hte audio to the previously extracted clip
        clip = VideoFileClip(video_location, audio=True).subclip(last_time, int(ad_read.start))
        clip = clip.set_audio(audio)
        logging.info(f'Got video starting at {last_time} until {ad_read.start}')

        # Prepare for next loop
        clips.append(clip)
        last_time = int(ad_read.end)

        logging.info(f'Block #{i + 1} completed, advancing...')

    # Create the chunk after the last block
    # Cutoff the start
    last_audio = AudioFileClip(video_location)
    audio = last_audio.cutout(0, last_time)

    # Create the video clip and add the audio
    last_clip = VideoFileClip(video_location).subclip(last_time, video_end)
    last_clip = last_clip.set_audio(audio)
    clips.append(last_clip)

    # Create the clip
    logging.info(f'Final clip for {video_title} created, creating video.')
    ad_free = concatenate_videoclips(clips)

    ad_free.write_videofile(f'ad_free_{video_title}', audio=True, fps=30, audio_codec='aac')
    logging.info(f'Processing done for {video_title}')`

**Comment by tenshiism** [comment]
Any solution?

**Comment by MrCasco** [comment]
Having the same problem by running this code
```python
def download_video(video_link, background_video_name, end_time) -> None:
    ydl_opts = {
        "format": "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best",
        "download_ranges": download_range_func(None, [(0, end_time)]),
        "outtmpl": "assets/bg",
    }
    with yt_dlp.YoutubeDL(ydl_opts) as dl:
        dl.download([video_link])
    return background_video_name
```
Everything was working well before I added the  `"download_ranges": download_range_func(None, [(0, end_time)])` line of code.

My output:
```
Exception ignored in: <function FFMPEG_AudioReader.__del__ at 0x0000022BFC679510>
Traceback (most recent call last):
  File "C:\Users\ernes\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\audio\io\readers.py", line 254, in __del__
    self.close_proc()
  File "C:\Users\ernes\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\audio\io\readers.py", line 149, in close_proc
    self.proc.terminate()
  File "C:\Users\ernes\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1589, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
```
Windows 11
Python 3.10.11
ffmpeg version N-114254-g030f4925b8-20240318

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
