### ISSUE TITLE
Moviepy cant play video when run through terminal

### ISSUE THREAD

**Issue by J4D3-UwU** [Zulko/moviepy#1750]
it works perfectly fine when i run it through any other code editor, but due to another package it needs to be run through terminal with sudo, but when i do so it errors out. 

#### Expected Behavior
play a video then close 

#### Actual Behavior
crashes and gets the following error code

```
pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
File "/home/pi/Desktop/video.py", line 14, in <module>
video = VideoFileClip("/home/pi/Display2/DisplayB/1s.mp4")
File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
fps_source=fps_source)
File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 36, in __init__
fps_source)
File "/usr/local/lib/python2.7/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 257, in ffmpeg_parse_infos
proc = sp.Popen(cmd, **popen_params)
File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
raise child_exception
OSError: [Errno 8] Exec format error
```

#### Steps to Reproduce the Problem

Run this code in terminal
```
import pygame
from moviepy.editor import VideoFileClip

Display = pygame.display.set_mode((500,300))

Display.fill((255,255,255))
video = VideoFileClip("/home/pi/Display2/DisplayB/1s.mp4")
video = video.without audio)
video.preview()
pygame.quit()
```

  - Python Version: 2.7
  - Moviepy Version: 1.0.3
  - Platform Name: Raspbian
  - Platform Version: 10

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
