### ISSUE TITLE
ImageMagick Installed and path added but getting Imagemagick not installed error 

### ISSUE THREAD

**Issue by Coder-dot-com** [Zulko/moviepy#1753]
New to movie.py and trying to get it to work, but keep getting this error. Can anyone help?

```
from moviepy.editor import *

video = VideoFileClip("/home/user/dev/MoviePy Learning/illuminated-road-junction-and-cars-traffic.mov").subclip(0,2)

# Make the text. Many more options are available.
txt_clip = ( TextClip("My Holidays 2013",fontsize=70,color='white')
             .set_position('center')
             .set_duration(1) )

result = CompositeVideoClip([video, txt_clip]) # Overlay text on video
result.write_videofile("myHolidays_edited.mov",fps=25)

```

#### Expected Behavior

The command to complete successfully

#### Actual Behavior
Receive this error

```
Traceback (most recent call last):
  File "/home/user/.local/share/virtualenvs/MoviePy_Learning-86rjnLdd/lib/python3.9/site-packages/moviepy/video/VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "/home/user/.local/share/virtualenvs/MoviePy_Learning-86rjnLdd/lib/python3.9/site-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: convert: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n022003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1986.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/737.
convert: no images defined `PNG32:/tmp/tmpb4gjxzjk.png' @ error/convert.c/ConvertImageCommand/3325.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/dev/MoviePy Learning/main.py", line 6, in <module>
    txt_clip = ( TextClip("My Holidays 2013",fontsize=70,color='white')
  File "/home/user/.local/share/virtualenvs/MoviePy_Learning-86rjnLdd/lib/python3.9/site-packages/moviepy/video/VideoClip.py", line 1146, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

convert: delegate library support not built-in '/usr/share/fonts/type1/gsfonts/n022003l.pfb' (Freetype) @ warning/annotate.c/RenderFreetype/1986.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/737.
convert: no images defined `PNG32:/tmp/tmpb4gjxzjk.png' @ error/convert.c/ConvertImageCommand/3325.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
```

#### Steps to Reproduce the Problem

Attempt to run the above code

**Comment by Coder-dot-com** [comment]
Finally fixed the problem. I had to change the policy of ImageMagick and comment out this policy:
```
<policy domain="path" rights="none" pattern="@*" />
```
 to

```
 <!-- <policy domain="path" rights="none" pattern="@*" /> -->.
```

**Comment by keikoro** [comment]
Thanks for the update with your solution, @Coder-dot-com!
