### ISSUE TITLE
nothing works, gets "NameError: name 'func' is not defined"

### ISSUE THREAD

**Issue by vincenzooo** [Zulko/moviepy#1764]
Any command fails with same error, I tried different examples and different files, as well as uninstalling and reinstalling moviepy and decorator, nothing worked.
VideoFileClip is created and can be accessed, but it fails when methods are called.
See below a minimalistic example from frame extraction example:

#### Expected Behavior

Extract a frame (or equivalent command to perform any operation on file).

#### Actual Behavior

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
d:\dati\ordine\programmazione\youtube\pytube.ipynb Cell 29' in <cell line: 1>()
----> [1](vscode-notebook-cell:/d%3A/dati/ordine/programmazione/youtube/pytube.ipynb#ch0000036?line=0) video.save_frame('prova.jpg')

File ~\anaconda3\envs\youtube\lib\site-packages\decorator.py:232, in decorate.<locals>.fun(*args, **kw)
    [230](file:///c%3A/Users/kovor/anaconda3/envs/youtube/lib/site-packages/decorator.py?line=229) if not kwsyntax:
    [231](file:///c%3A/Users/kovor/anaconda3/envs/youtube/lib/site-packages/decorator.py?line=230)     args, kw = fix(args, kw, sig)
--> [232](file:///c%3A/Users/kovor/anaconda3/envs/youtube/lib/site-packages/decorator.py?line=231) return caller(func, *(extras + args), **kw)

File ~\anaconda3\envs\youtube\lib\site-packages\moviepy\decorators.py:79, in preprocess_args.<locals>.wrapper(f, *a, **kw)
     [78](file:///c%3A/Users/kovor/anaconda3/envs/youtube/lib/site-packages/moviepy/decorators.py?line=77) def wrapper(f, *a, **kw):
---> [79](file:///c%3A/Users/kovor/anaconda3/envs/youtube/lib/site-packages/moviepy/decorators.py?line=78)     names = inspect.getfullargspec(func).args
     [80](file:///c%3A/Users/kovor/anaconda3/envs/youtube/lib/site-packages/moviepy/decorators.py?line=79)     new_a = [fun(arg) if (name in varnames) else arg
     [81](file:///c%3A/Users/kovor/anaconda3/envs/youtube/lib/site-packages/moviepy/decorators.py?line=80)              for (arg, name) in zip(a, names)]
     [82](file:///c%3A/Users/kovor/anaconda3/envs/youtube/lib/site-packages/moviepy/decorators.py?line=81)     new_kw = {k: fun(v) if k in varnames else v
     [83](file:///c%3A/Users/kovor/anaconda3/envs/youtube/lib/site-packages/moviepy/decorators.py?line=82)              for (k,v) in kw.items()}

NameError: name 'func' is not defined
```
#### Steps to Reproduce the Problem

```
from moviepy import *
from moviepy.editor import AudioFileClip, VideoFileClip
video = VideoFileClip(r"D:\dati\ordine\programmazione\youtube\salmon.mp4")

video.save_frame('prova.jpg')  #this fails with error shown above
```

#### Specifications

  - Python Version:  Python 3.10.4
  - Moviepy Version: 1.0.3
  - Platform Name:   Windows 10 Home
  - Platform Version: 10.0.19043 Build 19043

**Comment by vincenzooo** [comment]
It's now working!
I don't know what happened, I had been trying for several days and nothing was working.
Maybe uninstalilng and reinstalling worked after restarting the system.

**Comment by rloiselle** [comment]
I have the same issue with ImageClip methods. I need to resize and set duration of an ImageClip that I plan to overlay this onto a VideoFileClip using CompositeVideoClip. I made progress by using PIL methods to open my .png, resize, convert into numpy array, then create ImageClip. However, I still end up with the same error once I attempt to use the CompositeVideoClip method.

Python version  3.8.12
moviepy  1.0.3
imageio  2.19.0
imageio-ffmpeg  0.4.7
numpy  1.22.3
PIL  9.1.0
cv2  4.5.5
-------------------------------------------------------------------------------------------------------
	video = VideoFileClip(video_file)
	dur =video.duration
	size = video.size
	width,height = size
	print("width: ",width,"height: ",height)

	clipNm = os.path.join(AUVASSETS,'usgs_watermark.png')

	im = Image.open(clipNm)
	print(im.format, im.size,im.mode)
	im2 = im.resize((width,height))
	print(im2.size)
	print("im2 type: ",type(im2))

	im3 = np.array(im2)
	print("im3 type: ", type(im3))

	clip = ImageClip(im3,duration=dur)

	print(type(clip))
	w_clip,h_clip = clip.size
	print("clip size: ", w_clip,h_clip)

	video_watermarked = CompositeVideoClip([video, clip])

------------------------------------------------------------------------------------------------------
width:  1080 height:  572
PNG (1920, 1080) RGBA
(1080, 572)
im2 type:  <class 'PIL.Image.Image'>
im3 type:  <class 'numpy.ndarray'>
<class 'moviepy.video.VideoClip.ImageClip'>
clip size:  1080 572
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rloiselle\gitProjects\auv\GobyBot\unpack\unpackBagFunctions.py", line 868, in AUV_bag_unpack_video_charts
    add_USGS_reqs(videoName,videoName2)
  File "C:\Users\rloiselle\gitProjects\auv\GobyBot\video\videoFunctions.py", line 402, in add_USGS_reqs
    video_watermarked = CompositeVideoClip([video, clip])
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 97, in __init__
    maskclips = [(c.mask if (c.mask is not None) else
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 98, in <listcomp>
    c.add_mask().mask).set_position(c.pos)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\video\VideoClip.py", line 578, in add_mask
    return self.set_mask(mask.set_duration(self.duration))
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\decorators.py", line 29, in apply_to_mask
    newclip = f(clip, *a, **k)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\decorators.py", line 41, in apply_to_audio
    newclip = f(clip, *a, **k)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\decorators.py", line 79, in wrapper
    names = inspect.getfullargspec(func).args
NameError: name 'func' is not defined

**Comment by keikoro** [comment]
@rloiselle Please format your console output, provide info on your setup as per our issue template and specify how your issue relates to that of OP. Ending up with the same error message is not sufficient if you didn't arrive at the error in similar ways.

**Comment by keikoro** [comment]
I'm closing this for now as OP solved their problem but we don't know what the fix (or actual issue was), so there's nothing to go on with regard to labelling the issue.

**Comment by vincenzooo** [comment]
I don't know if this was really what solved the issue, because it was a delayed effect at restart and I had tried several things, but maybe it was removing and reinstalling, as indicated at the end of this thread: https://github.com/Zulko/moviepy/issues/1625#issuecomment-973056577

**Comment by rloiselle** [comment]
Tried restarting. Next will try unistall and reinstall. I created a new issue. Hopefully, correctly this time: #1765

**Comment by wasdee** [comment]
for my setup,
installation from conda forge will result in this error.

    # conda install -c conda-forge moviepy # not working 
    pip install moviepy

after uninstall and install from pip the issue solved
