### ISSUE TITLE
CompositeVideoClip- NameError: name 'func' is not defined

### ISSUE THREAD

**Issue by rloiselle** [Zulko/moviepy#1766]
Potentially related to #1765. Traceback is different so I am adding this issue. 

#### Expected Behavior
Create video composite from imageClip and videoFileClip

#### Actual Behavior
 NameError: name 'func' is not defined.

```
Traceback (most recent call last):
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\rloiselle\gitProjects\auv\GobyBot\unpack\unpackBagFunctions.py", line 869, in AUV_bag_unpack_video_charts
    add_USGS_reqs(videoName,videoName2)
  File "C:\Users\rloiselle\gitProjects\auv\GobyBot\video\videoFunctions.py", line 404, in add_USGS_reqs
    video_watermarked = CompositeVideoClip([video, clip])
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 97, in __init__
    maskclips = [(c.mask if (c.mask is not None) else
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 98, in <listcomp>
    c.add_mask().mask).set_position(c.pos)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\video\VideoClip.py", line 578, in add_mask
    return self.set_mask(mask.set_duration(self.duration))
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\decorators.py", line 29, in apply_to_mask
    newclip = f(clip, *a, **k)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\decorators.py", line 41, in apply_to_audio
    newclip = f(clip, *a, **k)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "C:\Users\rloiselle\Anaconda3\envs\ros_env\lib\site-packages\moviepy\decorators.py", line 79, in wrapper
    names = inspect.getfullargspec(func).args
NameError: name 'func' is not defined
```

#### Steps to Reproduce the Problem

```
video = VideoFileClip(os.path.abspath(video_file))
dur =video.duration

im3 = "path_to_PNG"
clip = ImageClip(im3,duration=dur)

video_watermarked = CompositeVideoClip([video, clip])
```
#### Specifications

- Python Version: 3.8.12
- Moviepy Version: 1.0.3
- Platform Name: Windows 10 Enterprise
- Platform Version: 21H2 build 19044.1645

**Comment by furas** [comment]
this is the same problem as in your previous issue #1765 - in `moviepy\decorators.py`
