### ISSUE TITLE
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)

### ISSUE THREAD

**Issue by Vamashi** [Zulko/moviepy#1844]
```
# Import everything needed to edit video clips 
from moviepy.editor import *
    
# loading video dsa gfg intro video 
clip = VideoFileClip("workingwith.mp4") 
    
# clipping of the video  
# getting video for only starting 10 seconds 
clip = clip.subclip(0, 10) 
    
# Reduce the audio volume (volume x 0.8) 
clip = clip.volumex(0.8) 
    
# Generate a text clip 
txt_clip = TextClip("HIMARS NEWS", fontsize = 75, color = 'black') 
    
# setting position of text in the center and duration will be 10 seconds 
txt_clip = txt_clip.set_pos('center').set_duration(10) 
    
# Overlay the text clip on the first video clip 
video = CompositeVideoClip([clip, txt_clip]) 
    
# showing video 
video.ipython_display(width = 280) 
```
-->

#### Expected Behavior
Moviepy - Building video __temp__.mp4.
Moviepy - Writing video __temp__.mp4

                                                                                                                       
Moviepy - Done !
Moviepy - video ready __temp__.mp4

#### Actual Behavior
Traceback (most recent call last):
  File "C:\Users\vlad\Downloads\ватермарк\main.py", line 2, in <module>
    from moviepy.editor import *
  File "C:\Users\vlad\AppData\Local\Programs\Python\Python310\lib\site-packages\moviepy\editor.py", line 24, in <module>
    import imageio
  File "C:\Users\vlad\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\__init__.py", line 24, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "C:\Users\vlad\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\core\__init__.py", line 10, in <module>
    from .util import Image, Array, Dict, asarray, image_as_uint, urlopen
  File "C:\Users\vlad\AppData\Local\Programs\Python\Python310\lib\site-packages\imageio\core\util.py", line 10, in <module>
    import numpy as np
  File "C:\Users\vlad\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\__init__.py", line 151, in <module>
    from . import random
  File "C:\Users\vlad\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\random\__init__.py", line 180, in <module>
    from . import _pickle
  File "C:\Users\vlad\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\random\_pickle.py", line 1, in <module>
    from .mtrand import RandomState
  File "mtrand.pyx", line 4651, in init numpy.random.mtrand
  File "mtrand.pyx", line 182, in numpy.random.mtrand.RandomState.__init__
  File "_mt19937.pyx", line 129, in numpy.random._mt19937.MT19937.__init__
  File "bit_generator.pyx", line 517, in numpy.random.bit_generator.BitGenerator.__init__
  File "bit_generator.pyx", line 296, in numpy.random.bit_generator.SeedSequence.__init__
  File "C:\Users\Владик\AppData\Local\Programs\Python\Python310\lib\random.py", line 769, in getrandbits
    x = int.from_bytes(_urandom(numbytes))
TypeError: from_bytes() missing required argument 'byteorder' (pos 2)

#### Steps to Reproduce the Problem

Just run program

#### Specifications

  - Python Version: 22.2.2 3.10
  - Moviepy Version: 1.0.3
  - Platform Name: Windows
  - Platform Version: 10

**Comment by Vamashi** [comment]
> Could you please try with the current master (the last version on PyPI is not super current) and let us know if the problem persists? Thank you.

Tried to delete current moviepy and install from github, not helped.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
