### ISSUE TITLE
Issue with ImageMagick even if I installed it and change its policy

### ISSUE THREAD

**Issue by ThomasMargnac** [Zulko/moviepy#1846]
Hi everyone,

I am currently using moviepy on a project. So basically, in my project I have a video file and I add audio file and text to it. But I want to dockerize this project and when I do it, there is a problem with ImageMagick. Of course, I already commented the line containing ```<policy domain="path" rights="none" pattern="@*" />```. I also modified a bit ```config.py``` to create a ```check()``` function (not included in this post) to verify that ImageMagick is detected and it is actually detected by moviepy! So I really don't know how to solve this issue, if you have an idea please don't hesitate to answer!

#### Expected Behavior

No error

#### Actual Behavior

Getting

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/moviepy/video/VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "/usr/local/lib/python3.9/site-packages/moviepy/tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: convert-im6.q16: unable to read font `Courier' @ warning/annotate.c/RenderType/949.
convert-im6.q16: unable to read font `Courier' @ error/annotate.c/RenderFreetype/1396.
convert-im6.q16: no images defined `PNG32:/tmp/tmpb8r57z6f.png' @ error/convert.c/ConvertImageCommand/3229.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/app/src/test.py", line 4, in <module>
    text = TextClip("Test", fontsize = 40, color='white', stroke_color='black')
  File "/usr/local/lib/python3.9/site-packages/moviepy/video/VideoClip.py", line 1146, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

convert-im6.q16: unable to read font `Courier' @ warning/annotate.c/RenderType/949.
convert-im6.q16: unable to read font `Courier' @ error/annotate.c/RenderFreetype/1396.
convert-im6.q16: no images defined `PNG32:/tmp/tmpb8r57z6f.png' @ error/convert.c/ConvertImageCommand/3229.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
```
#### Steps to Reproduce the Problem

I set up this simple Python Script and DockerFile which recreate my issue

My file ```test.py```:
```
from moviepy.editor import TextClip

if __name__ == "__main__":
    text = TextClip("Test", fontsize = 40, color='white', stroke_color='black')
```

My ```Dockerfile```:
```
FROM python:3.9
RUN apt update && \
    apt-get install ffmpeg imagemagick -y && \
    sed -i -e '73d;91d' /etc/ImageMagick-6/policy.xml
RUN pip install moviepy==1.0.3
WORKDIR /usr/app/src
COPY . .
ENTRYPOINT ["python3", "test.py"]
```

#### Specifications

  - Python Version: 3.9
  - Moviepy Version: 1.0.3
  - Platform Name: Python 3.9 Docker Official Image
  - Platform Version: ///

**Comment by demirdegerli** [comment]
I'm getting the exact same error with same specifications but my Python version is 3.10.

TextClip occurs the error.

**Comment by putzmarcos** [comment]
I'm dealing with this exactly problem, tried almost everything I could do in my end (modifying the xml file, building the library instead of using pip) and no lucky here.  

@ThomasMargnac do you figure out some solution?

**Comment by ThomasMargnac** [comment]
Unfortunately, even if I looked and adapted the [Dockerfile](https://github.com/Zulko/moviepy/blob/858bb81fba7e09f1f562283ed6d1394db883b6c7/Dockerfile) nothing has worked...

**Comment by cal-overflow** [comment]
I'm also experiencing this issue.... \
For now I'm going to be a little hacky and build transparent images containing text (using python PIL) and then display those `ImageClip`'s, since the `ImageClip` seems to be working fine.

Hopefully that helps anyone else who faces this until it's fixed.

**Comment by rs-people-solutions** [comment]
600+ days later same issue here.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
