### ISSUE TITLE
Unable to choose random file for moviepy

### ISSUE THREAD

**Issue by papioswald** [Zulko/moviepy#1850]
I am unable to choose a file out of my 2 folders, when I try to run the code, I get this error out of my console

```
Traceback (most recent call last):
  File "d:\111111\project\edit.py", line 13, in <module>
    clip1 = VideoClip(random1).set_duration(2)
  File "D:\111111\installation\python\lib\site-packages\moviepy\video\VideoClip.py", line 86, in __init__
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-11>", line 2, in get_frame
  File "D:\111111\installation\python\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "D:\111111\installation\python\lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
TypeError: '_io.TextIOWrapper' object is not callable
PS D:\111111\project> 
```

These are the lines of code that cause the error.

```
videodir = os.listdir("media/videos")
imagedir = os.listdir("media/images")

random1 = open("media/videos/" + random.choice(videodir))
random2 = open("media/images/" + random.choice(imagedir))
random3 = open("media/images/" + random.choice(imagedir))

media = []
clip1 = VideoClip(random1).set_duration(2)
clip2 = ImageClip(random2).fx(vfx.fadein, 0.3).set_duration(2)
clip3 = ImageClip(random3).fx(vfx.fadein, 0.3).set_duration(5)
```
clip1 is unable to process the random1 variable, and I assume that clip2 and 3 cant either. I have tried putting the random files through range(len()), yet i still get an error. should I still use the range(len()) or another method.

**Comment by papioswald** [comment]
i put the object instead of the file name.
