### ISSUE TITLE
Moviepy installation keep getting failed

### ISSUE THREAD

**Issue by killuazoldyckreal** [Zulko/moviepy#1857]
#### Expected Behavior
Installing moviepy

#### Actual Behavior
Not getting installed
Keep ending like this:
```
C:\Users\Dell>pip install moviepy
Collecting moviepy
  Using cached moviepy-1.0.3.tar.gz (388 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2851, in get_entry_map
          ep_map = self._ep_map
        File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2813, in __getattr__
          raise AttributeError(attr)
      AttributeError: _ep_map

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Dell\AppData\Local\Temp\pip-install-i4yprb1o\moviepy_ce51e997662d432eacab4acbb75f1234\setup.py", line 110, in <module>
          setup(
        File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 152, in setup
          _install_setup_requires(attrs)
        File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 142, in _install_setup_requires
          dist = MinimalDistribution(attrs)
        File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\__init__.py", line 134, in __init__
          distutils.core.Distribution.__init__(self, filtered)
        File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py", line 451, in __init__
          for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
        File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 641, in <genexpr>
          for entry in dist.get_entry_map(group).values()
        File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2853, in get_entry_map
          ep_map = self._ep_map = EntryPoint.parse_map(
        File "C:\Users\Dell\AppData\Local\Programs\Python\Python39\lib\site-packages\pkg_resources\__init__.py", line 2538, in parse_map
          raise ValueError("Entry points must be listed in groups")
      ValueError: Entry points must be listed in groups
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

#### Steps to Reproduce the Problem

```
pip install moviepy 
```
```
pip install ez_setup 
```
I downloaded the source zip and after I tried running 
```
python setup.py install 
```
It too yields the same problem

#### Specifications

  - Python Version: Python 3.9.11
  - Moviepy Version: Installing via pip, should be the latest version
  - Platform Name: Win 10 Education
  - Platform Version: 21H2

**Comment by keikoro** [comment]
When we ask for platform in our issue templates, we mean the OS (+ version no.) you are using!

**Comment by alexonpeace** [comment]
I have the exact same issue
Platform Name: Unraid(Docker)
Platform Version: 5.19.17-Unraid

**Comment by killuazoldyckreal** [comment]
Corrected my platform name and version
