### ISSUE TITLE
MoviePy doesn't handle mkv files.

### ISSUE THREAD

**Issue by TheHimanshuRastogi** [Zulko/moviepy#1888]
I tried opening a mkv file to horizontally flip it using this code.

```
import moviepy.editor as mpy

clip = mpy.VideoFileClip("hit.mkv")

flipped_clip = clip.fx(mpy.vfx.mirror_x)

colored_clip = flipped_clip.fx(mpy.vfx.colorx, 1.2)

colored_clip.write_videofile("output.mkv")
```

But it shows me KeyError & ValueError.

```
c:/Users/Ait/OneDrive/Documents/moviepy/flip/flip.py 
Traceback (most recent call last):
  File "C:\Users\Ait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\moviepy\video\VideoClip.py", line 262, in write_videofile
    codec = extensions_dict[ext]['codec'][0]
KeyError: 'mkv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Ait\OneDrive\Documents\moviepy\flip\flip.py", line 13, in <module>
    colored_clip.write_videofile("output.mkv")
  File "<decorator-gen-55>", line 2, in write_videofile 
  File "C:\Users\Ait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-54>", line 2, in write_videofile 
  File "C:\Users\Ait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\moviepy\decorators.py", line 135, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-53>", line 2, in write_videofile 
  File "C:\Users\Ait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "C:\Users\Ait\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\moviepy\video\VideoClip.py", line 264, in write_videofile
    raise ValueError("MoviePy couldn't find the codec associated "
ValueError: MoviePy couldn't find the codec associated with the filename. Provide the 'codec' parameter in write_videofile.
PS C:\Users\Ait\OneDrive\Documents\moviepy\flip> 
```

Please fix this issue or if it's not an issue, add mkv file support too.

**Comment by kifuan** [comment]
You can use `ffmpeg` to convert your file to supported formats like mp4 first.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
