### ISSUE TITLE
Mitigating Memory Limitations

### ISSUE THREAD

**Issue by buckeye17** [Zulko/moviepy#1901]
I'm attempted to build a video file from a list images, but it seems my RAM is insufficient.  I am getting the same error on my personal Windows 10 laptop and on Google Colab.  Are there any mitigations I can take?

```
from moviepy.editor import AudioFileClip
from moviepy.editor import ImageClip, concatenate_videoclips

FPS = 10
audioclip = AudioFileClip(audio_path)
clips = [ImageClip(img).set_duration(1/FPS) for img in frame_img_ls]
concat_clip = concatenate_videoclips(clips, method="compose")
concat_clip.set_audio(audioclip).write_videofile("results/test.mp4", fps=FPS)
```

#### Expected Behavior
Successful generation of a movie file.

#### Actual Behavior
```
Traceback (most recent call last):
  File "c:\Users\adiad\Documents\GitHub\demucs\app.py", line 277, in <module>
    clips = [ImageClip(img).set_duration(2) for img in frame_img_ls]
  File "c:\Users\adiad\Documents\GitHub\demucs\app.py", line 277, in <listcomp>
    clips = [ImageClip(img).set_duration(2) for img in frame_img_ls]
  File "C:\Users\adiad\Anaconda3\envs\demucs\lib\site-packages\moviepy\video\VideoClip.py", line 889, in __init__
    img = imread(img)
  File "C:\Users\adiad\Anaconda3\envs\demucs\lib\site-packages\imageio\__init__.py", line 97, in imread
    return imread_v2(uri, format=format, **kwargs)
  File "C:\Users\adiad\Anaconda3\envs\demucs\lib\site-packages\imageio\v2.py", line 227, in imread
    result = file.read(index=0, **kwargs)
  File "C:\Users\adiad\Anaconda3\envs\demucs\lib\site-packages\imageio\core\legacy_plugin_wrapper.py", line 148, in read        
    return reader.get_data(index)
  File "C:\Users\adiad\Anaconda3\envs\demucs\lib\site-packages\imageio\core\format.py", line 435, in get_data
    im, meta = self._get_data(index, **kwargs)
  File "C:\Users\adiad\Anaconda3\envs\demucs\lib\site-packages\imageio\plugins\pillow_legacy.py", line 480, in _get_data        
    im, info = PillowFormat.Reader._get_data(self, index)
  File "C:\Users\adiad\Anaconda3\envs\demucs\lib\site-packages\imageio\plugins\pillow_legacy.py", line 343, in _get_data
    im = pil_get_frame(self._im, **self._kwargs)
  File "C:\Users\adiad\Anaconda3\envs\demucs\lib\site-packages\imageio\plugins\pillow_legacy.py", line 781, in pil_get_frame    
    frame = np.array(frame, dtype=dtype)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 5.93 MiB for an array with shape (1080, 1920, 3) and data type uint8
```

#### Specifications

  - Python Version: 3.9.15
  - Moviepy Version: 1.0.3
  - Platform Name: Windows & Google Colab
  - Platform Version: Windows 10

**Comment by pavanyogi** [comment]
we are also getting the similar error during video write process:
```bash
Processed clip: C:\Users\pavan\Downloads\difficult-word-in-hindi\english-hindi-beginner-words-translated\135_3_2.png (Index: 567)
Traceback (most recent call last):
  File "C:\Users\pavan\Downloads\difficult-word-in-hindi\create_video_with_audio_from_images-working-sync-audio-pass6.py", line 99, in <module>
    temp_clip = concatenate_videoclips(audio_video_clips, method="compose")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Roaming\Python\Python311\site-packages\moviepy\video\compositing\concatenate.py", line 98, in concatenate_videoclips
    result = CompositeVideoClip( [c.set_start(t).set_position('center')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Roaming\Python\Python311\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 102, in __init__
    self.mask = CompositeVideoClip(maskclips,self.size, ismask=True,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Roaming\Python\Python311\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 79, in __init__
    self.bg = ColorClip(size, color=self.bg_color)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pavan\AppData\Roaming\Python\Python311\site-packages\moviepy\video\VideoClip.py", line 1014, in __init__
    ImageClip.__init__(self, np.tile(color, w * h).reshape(shape),
                             ^^^^^^^^^^^^^^^^^^^^^
  File "<__array_function__ internals>", line 180, in tile
  File "C:\Users\pavan\AppData\Roaming\Python\Python311\site-packages\numpy\lib\shape_base.py", line 1278, in tile
    c = c.reshape(-1, n).repeat(nrep, 0)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 15.8 MiB for an array with shape (2073600, 1) and data type float64
PS C:\Users\pavan\Downloads\difficult-word-in-hindi>
```

**Comment by pavanyogi** [comment]
I believe, the optimization/fixes would go around these lines in the below files:
```bash
moviepy\video\compositing\concatenate.py", line 98
moviepy\video\compositing\CompositeVideoClip.py", line 102
moviepy\video\VideoClip.py", line 1014```

**Comment by FujiwaraChoki** [comment]
Same error...

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
