### ISSUE TITLE
ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by Ymajine** [Zulko/moviepy#1915]
i have this error and i don't how to resolve it , help me plz !
`Keeping intervals: []
Traceback (most recent call last):
  File "/home/ymajine/Bureau/2023/autocut/test2.py", line 84, in <module>
    main()
  File "/home/ymajine/Bureau/2023/autocut/test2.py", line 70, in main
    edited_video = concatenate_videoclips([vid.subclip(max(start, 0), end) for [start, end] in intervals_to_keep])
  File "/usr/local/lib/python3.10/dist-packages/moviepy/video/compositing/concatenate.py", line 75, in concatenate_videoclips
    w = max(r[0] for r in sizes)
ValueError: max() arg is an empty sequence`

**Comment by keikoro** [comment]
Please always include your specs like we ask for in our issue templates (MoviePy version, platform used etc.) as well as code samples for reproducability and complete logs for errors where applicable, thank you.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
