### ISSUE TITLE
ValueError: cannot reshape array of size 777600 into shape (720,1080,5)

### ISSUE THREAD

**Issue by samuelbraun04** [Zulko/moviepy#1920]
The following lines:
```
currentImageClip = ImageClip(r'path/to/image')
imageClipWithCaption = CompositeVideoClip([ColorClip(size=(1080, 720), color='black'), currentImageClip])
```
gives me the following error:
```
Traceback (most recent call last):
  File "C:\Users\samlb\Documents\folder\pythonFile.py", line 140, in makeVideo
    imageClipWithCaption = CompositeVideoClip([ColorClip(size=(1080, 720), color='black'), currentImageClip])
  File "C:\Users\samlb\AppData\Roaming\Python\Python39\site-packages\moviepy\video\VideoClip.py", line 1157, in __init__
    np.tile(color, w * h).reshape(shape), is_mask=is_mask, duration=duration
ValueError: cannot reshape array of size 777600 into shape (720,1080,5)
```
How can I avoid this error? Does it have something to do with the type of image I'm trying to composite?

This is the image I'm using (.png):

![16763856438648417](https://user-images.githubusercontent.com/90664891/218770737-8b352ee2-c0d4-4d7d-9b18-3f80b87a0ea7.png)

#### Specifications

  - Python Version: 3.9.13
  - MoviePy Version: 2.0.0.dev2-
  - Platform Name: Windows
  - Platform Version: 10

**Comment by keikoro** [comment]
@stef405 Generally, any issue is up for grabs, but best to check older open PRs first to avoid potential duplication of efforts. Open issues regarding the v2 release are also worth a look because parts of the codebase are being rewritten.

**Comment by stef405** [comment]
@keikoro  Is there a seperate github repository for v2 release?

**Comment by stef405** [comment]
So far, I have pulled a recent version of the repository, and used the same snippet code and image in the original post, but no errors popped up. I don't know if this is specifically a problem with older versions of Windows, which may or may not be relevant for project maintenance going forward

**Comment by s-2ndd** [comment]
Update: Was able to recreate error on v2, and will continue to figure out this bug

**Comment by stef405** [comment]
Update: Was able to reproduce bug, and will work on trying to figure it out

**Comment by stef405** [comment]
I dealt with this bug in a Pull Request that sends a different error message. In short, the error occurs because a Color Clip cannot be created with a string 'black'. According to the Color Clip documentation at [https://zulko.github.io/moviepy/ref/VideoClip/VideoClip.html#colorclip](url), color must be RGB tuple (or no object) if isMask is false or a float if isMask is true.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
