### ISSUE TITLE
Error when using TextClip

### ISSUE THREAD

**Issue by Mwexim** [Zulko/moviepy#1951]
#### Expected Behavior
The program should start and create the proper text clips.

#### Actual Behavior
I get a weird error. I already changed the ImageMagick path inside the `config_defaults.py` file.

```bash
Traceback (most recent call last):
  File "PATHTOPROJECT\venv\Lib\site-packages\moviepy\video\VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "PATHTOPROJECT\venv\Lib\site-packages\moviepy\tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: magick.exe: label expected `@USER\AppData\Local\Temp\tmpmo5dmg7y.txt' @ error/annotate.c/GetMultilineTypeMetrics/797.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "PATHTOPROJECT\main.py", line 55, in <module>
    lyric_clips.append(TextClip(last_lyric, fontsize=40, color="white")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATHTOPROJECT\venv\Lib\site-packages\moviepy\video\VideoClip.py", line 1146, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

magick.exe: label expected `@USER\AppData\Local\Temp\tmpmo5dmg7y.txt' @ error/annotate.c/GetMultilineTypeMetrics/797.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
```

#### Steps to Reproduce the Problem

The following code was used when the issue occurred, though I don't think it is the source of the issue at hand. If I comment out everything that has to do with the `TextClip` class, it works fine. So it is a ImageMagick issue I think. I tried everything already and searched online for an answer, but I could not find a solution to my problem.
```py
from moviepy.editor import *

# Start the creation of the video clip
video = VideoFileClip("resources/song.mp4").subclip(0, 30)

# Open the file and read the lines
file = open("resources/lyrics.parol", "r")

# Compose the lyric video
lyric_clips = []
last_timestamp = -1
last_lyric = ""
for line in file.readlines():
    line = line.strip()

    parameters = enclosed_text(line, "(", ")")
    timestamp = int(parameters)
    lyric = line[len(parameters) + 1:]

    if last_timestamp != -1:
        lyric_clips.append(TextClip(lyric, fontsize=40, color="white")
                           .with_position("center")
                           .with_duration(timestamp - last_timestamp))
        last_timestamp, last_lyric = timestamp, lyric
lyric_clips.append(TextClip(last_lyric, fontsize=40, color="white")
                   .with_position("center")
                   .with_duration(video.duration - last_timestamp))
print(lyric_clips)

result = CompositeVideoClip([video] + lyric_clips)
result.write_videofile("resources/lyrics.mp4", fps=30)
```

#### Specifications

  - Python Version: 3.11
  - MoviePy Version: 1.0.3
  - Platform Name: Windows
  - Platform Version: 10

**Comment by KMiNT21** [comment]
I believe the issue lies within your code, specifically in the TextClip function calls where the lyric or last_lyric parameter is being used. If the text parameter is an empty string, it will result in the same error being raised.

**Comment by Mwexim** [comment]
> I believe the issue lies within your code, specifically in the TextClip function calls where the lyric or last_lyric parameter is being used. If the text parameter is an empty string, it will result in the same error being raised.

You were right, thanks for the advise! I feel the error should be more descriptive though.
