### ISSUE TITLE
PermissionError: [Errno 13] Permission denied 

### ISSUE THREAD

**Issue by Beggining2Code** [Zulko/moviepy#1985]
#### Expected Behavior
Run the program 

#### Actual Behavior
When it comes to "Finding a spot in the backgrounds audio to chop," the program bugs out. 

Here is the error I receive: 
```
 Sorry, something went wrong with this version! Try again, and feel free to report this issue at GitHub or the Discord community.                                                                         
 Version: 3.2                                                                                                                                                                                             
 Error: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ffmpeg'                                                                            
 Config: {'allow_nsfw': True, 'theme': 'dark', 'times_to_run': 1, 'opacity': 0.9, 'storymode': False, 'storymodemethod': 1, 'storymode_max_length': 1000, 'resolution_w': 1080, 'resolution_h': 1920,     
 'zoom': 1.0, 'background': {'background_video': 'minecraft', 'background_audio': 'lofi', 'background_audio_volume': 0.15, 'enable_extra_audio': False, 'background_thumbnail': False,                    
 'background_thumbnail_font_family': 'arial', 'background_thumbnail_font_size': 96, 'background_thumbnail_font_color': '255,255,255'}, 'tts': {'voice_choice': 'streamlabspolly', 'random_voice': True,   
 'elevenlabs_voice_name': 'Adam', 'elevenlabs_api_key': 'REDACTED', 'aws_polly_voice': 'Matthew', 'streamlabs_polly_voice': 'Matthew', 'tiktok_voice': 'en_us_001', 'tiktok_sessionid': 'REDACTED',       
 'python_voice': '1', 'py_voice_num': '2', 'no_emojis': False}}                                                                                                                                           
Traceback (most recent call last):
  File "/Users/pythontesting/Desktop/RedditVideoMakerBot-3.2/main.py", line 134, in <module>
    raise err
  File "/Users/pythontesting/Desktop/RedditVideoMakerBot-3.2/main.py", line 116, in <module>
    run_many(config["settings"]["times_to_run"])
  File "/Users/pythontesting/Desktop/RedditVideoMakerBot-3.2/main.py", line 71, in run_many
    main()
  File "/Users/pythontesting/Desktop/RedditVideoMakerBot-3.2/main.py", line 62, in main
    chop_background(bg_config, length, reddit_object)
  File "/Users/pythontesting/Desktop/RedditVideoMakerBot-3.2/video_creation/background.py", line 142, in chop_background
    background_audio = AudioFileClip(f"assets/backgrounds/audio/{audio_choice}")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/audio/io/AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/audio/io/readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/moviepy/video/io/ffmpeg_reader.py", line 257, in ffmpeg_parse_infos
    proc = sp.Popen(cmd, **popen_params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/ffmpeg'
```

#### Steps to Reproduce the Problem

Run the program (I was using ```sudo python3 main.py``` since I'm on a Mac) 

#### Specifications

  - Python Version: 3.10.9
  - MoviePy Version: 1.0.3
  - Platform Name: M1 Macbook Pro 
  - Platform Version: Ventura 13.3.1

**Comment by keikoro** [comment]
Please always include code samples for reproducability. Thank you.

**Comment by DevMMI** [comment]
@Beggining2Code did you end up solving this? I ran into the same issue.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
