### ISSUE TITLE
TextClip.list('color') fails

### ISSUE THREAD

**Issue by ZdenekM** [Zulko/moviepy#200]
``` python
>>> from moviepy.editor import TextClip
>>> TextClip.list("color")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/VideoClip.py", line 1179, in list
    return [l.split(" ")[1] for l in lines[2:]]
IndexError: list index out of range
```

**Comment by baileyspace** [comment]
+1

**Comment by derblub** [comment]
+1

**Comment by lanewinfield** [comment]
+1

**Comment by earney** [comment]
this has been fixed with a recent Pull request.
