### ISSUE TITLE
Failed to batch create multiple VideoFileClip

### ISSUE THREAD

**Issue by maty974** [Zulko/moviepy#202]
Hi,

I've a little problem with `VideoFileClip`, I want to batch create a certain amount of `VideoFileClip`
from a list of file path, and then concatenate all Clip with the command `concatenate_videoclips(clip_list, method="chain")`

Here is a brief code example:

```
all_clip_path=["/some/file/path.mov","/some/file/path.mov","/some/file/path.mov","/some/file/path.mov","/some/file/path.mov"]
clip_list=[]
for clip_path in all_clip_path:
    clip=VideoFileClip(clip_path)
    clip_list.append(clip)
    print clip,clip_path
```

And here is the output of the code:

```
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7f44cc0b55f0> //NWAVE/PROJECTS/SOB/EDIT/RUSH/100_MOM/100_MOM_2_PREV/preview_shot_split/maty/splits/100_0010_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7f44cc0b5368> //NWAVE/PROJECTS/SOB/EDIT/RUSH/100_MOM/100_MOM_2_PREV/preview_shot_split/maty/splits/100_0020_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7f44cc0b5128> //NWAVE/PROJECTS/SOB/EDIT/RUSH/100_MOM/100_MOM_2_PREV/preview_shot_split/maty/splits/100_0030_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7f44cc0b56c8> //NWAVE/PROJECTS/SOB/EDIT/RUSH/100_MOM/100_MOM_2_PREV/preview_shot_split/maty/splits/100_0040_prev_split.mov
Traceback (most recent call last):
  File "/test_moviepy/test.py", line 351, in <module>
    splitter.split_all_shots(concatenate_after=True,concatenate_only=True)
  File "/test_moviepy/test.py", line 299, in split_all_shots
    concatenate_all_shots()
  File "/test_moviepy/test.py", line 339, in concatenate_all_shots
    clip=VideoFileClip(clip_path)
  File "/external/libraries/moviepy/0.2.2.11/common/moviepy/video/io/VideoFileClip.py", line 55, in __init__
    reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt)
  File "/external/libraries/moviepy/0.2.2.11/common/moviepy/video/io/ffmpeg_reader.py", line 56, in __init__
    self.lastread = self.read_frame()
  File "/external/libraries/moviepy/0.2.2.11/common/moviepy/video/io/ffmpeg_reader.py", line 125, in read_frame
    self.filename))
IOError: MoviePy error: failed to read the first frame of video file /test/splits/test_050_prev_split.mov. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
Exception AttributeError: "VideoFileClip instance has no attribute 'reader'" in <bound method VideoFileClip.__del__ of <moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7f44cc0b5878>> ignored
[Finished in 4.5s with exit code 1]
```

Another strange thing is if I remove the line `clip_list.append(clip)` everything is working but I want to get all `VideoFileClip` into a list to be able to use it in `concatenate_videoclips()`, here is the output:

```
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e5f0> /test/splits/test_010_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e368> /test/splits/test_020_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e5f0> /test/splits/test_030_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e368> /test/splits/test_040_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e5f0> /test/splits/test_050_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e368> /test/splits/test_060_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e5f0> /test/splits/test_070_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e368> /test/splits/test_080_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e5f0> /test/splits/test_090_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e368> /test/splits/test_100_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e5f0> /test/splits/test_110_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e368> /test/splits/test_120_prev_split.mov
<moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x7fdca333e5f0> /test/splits/test_130_prev_split.mov
```

Thanks for your help Zulko

**Comment by maty974** [comment]
Strange, I've run the code today and it has worked only one time, I was able to write `VideoFileClip` list with `concatenate_videoclips()`.

Now its not working anymore for no reason :(

**Comment by keikoro** [comment]
As this is a very old issue, I'm wondering if the problem still persists or if we can close it? @maty974
