### ISSUE TITLE
Can't save gif

### ISSUE THREAD

**Issue by NiKiTjAOFF** [Zulko/moviepy#2122]
After I use these lines of code:
```
from moviepy.editor import VideoFileClip
video_path = SOURCE_DIRECTORY_PATH + "\\" + video_name_with_extension
gif_path = SOURCE_DIRECTORY_PATH + "\\" + video_name + ".gif"
clip = VideoFileClip(video_path)
clip.write_gif(gif_path)
```
It proceeds the mp4 video, saves gif with 0 bytes and continueing to save something somewhere, so taht after 30s my disk space is shortened for 1gb. After I restart my pc the space's restored to as it was before.

VideoFileClip actually contains video.

After I interrupt execution I get:
```
Exception ignored in: <function LegacyWriter.__del__ at 0x0000021F60F273A0>
Traceback (most recent call last):
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\imageio\v2.py", line 200, in __del__
    self.close()
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\imageio\v2.py", line 190, in close
    self.instance.close()
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\imageio\plugins\pillow.py", line 144, in close
    self._flush_writer()
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\imageio\plugins\pillow.py", line 485, in _flush_writer
    primary_image.save(self._request.get_file(), **self.save_args)
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\Image.py", line 2439, in save
    save_handler(self, fp, filename)
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\GifImagePlugin.py", line 704, in _save_all
    _save(im, fp, filename, save_all=True)
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\GifImagePlugin.py", line 715, in _save
    if not save_all or not _write_multiple_frames(im, fp, palette):
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\GifImagePlugin.py", line 602, in _write_multiple_frames
    im_frame = _normalize_mode(im_frame.copy())
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\GifImagePlugin.py", line 492, in _normalize_mode
    im = im.convert("P", palette=Image.Palette.ADAPTIVE)
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\Image.py", line 1029, in convert
    im = self.im.quantize(colors)
KeyboardInterrupt:
Exception ignored in: <function PluginV3.__del__ at 0x0000021F60F0F160>
Traceback (most recent call last):
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\imageio\core\v3_plugin_api.py", line 370, in __del__
    self.close()
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\imageio\plugins\pillow.py", line 144, in close
    self._flush_writer()
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\imageio\plugins\pillow.py", line 485, in _flush_writer
    primary_image.save(self._request.get_file(), **self.save_args)
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\Image.py", line 2439, in save
    save_handler(self, fp, filename)
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\GifImagePlugin.py", line 704, in _save_all
    _save(im, fp, filename, save_all=True)
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\GifImagePlugin.py", line 715, in _save
    if not save_all or not _write_multiple_frames(im, fp, palette):
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\GifImagePlugin.py", line 602, in _write_multiple_frames
    im_frame = _normalize_mode(im_frame.copy())
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\GifImagePlugin.py", line 492, in _normalize_mode
    im = im.convert("P", palette=Image.Palette.ADAPTIVE)
  File "C:\Users\nikit\Всякое\MyProjects\converter\convert\lib\site-packages\PIL\Image.py", line 1029, in convert
    im = self.im.quantize(colors)
KeyboardInterrupt:
```
pls help, I followed tutorial how to convert mp4 to gif and this happened

**Comment by keikoro** [comment]
Please always include your specs like we ask for in our issue templates – MoviePy version, platform used etc. – to help pinpoint what causes your problem, thanks.

**Comment by NiKiTjAOFF** [comment]
> Please always include your specs like we ask for in our issue templates – MoviePy version, platform used etc. – to help pinpoint what causes your problem, thanks.

The're already in there

**Comment by NiKiTjAOFF** [comment]
After I ran the following code on collab:
```
from moviepy.editor import *
clip =VideoFileClip("2024-02-25 23-53-31.mp4")
clip.write_gif("2024-02-25 23-53-31.gif")
```

It gave me this warn:
MoviePy - Building file 2024-02-25 23-53-31.gif with imageio.
t: 100%|█████████▉| 2322/2324 [00:09<00:00, 277.26it/s, now=None]WARNING:py.warnings:/usr/local/lib/python3.10/dist-packages/moviepy/video/io/ffmpeg_reader.py:123: UserWarning: Warning: in file 2024-02-25 23-53-31.mp4, 691200 bytes wanted but 0 bytes read,at frame 2323/2324, at time 38.72/38.72 sec. Using the last valid frame instead.
  warnings.warn("Warning: in file %s, "%(self.filename)+

**Comment by NiKiTjAOFF** [comment]
Problem resolved. I downloaded ffmpeg.exe, added it to PATH. pip installed ffmpy 
Code:
```
import ffmpy
from typing import List
import os

def list_image_files(directory: str) -> List[str]:
    image_extensions = [".mp4"]
    image_files = [f for f in os.listdir(directory) if os.path.splitext(f)[1].lower() in image_extensions]
    return image_files

SOURCE_DIRECTORY_PATH = r"videos"
list = list_image_files(SOURCE_DIRECTORY_PATH)
print(list)
for video_name_with_extension in list:
    video_name = video_name_with_extension.split('.')[0]
    video_path = SOURCE_DIRECTORY_PATH + "\\" + video_name_with_extension
    gif_path = SOURCE_DIRECTORY_PATH + "\\" + video_name + ".gif"
    print(video_path)
    print(gif_path)
    ff = ffmpy.FFmpeg(
        inputs = {video_path : None},
	    outputs = {gif_path : None})
    ff.run()
```

**Comment by keikoro** [comment]
> They're already in there

Thanks, I didn't see that because I scan for them at the bottom of an issue when I tag it.

> Problem solved. 

If this means this issue is solved, please don't forget to close it. Thank you.
