### ISSUE TITLE
ImageMagick Binary Not Found

### ISSUE THREAD

**Issue by TheCaptainCodes** [Zulko/moviepy#2167]
### **What to do for windows?**

I have even changed the file path in **`config_details.py`**
`IMAGEMAGICK_BINARY = os.getenv('IMAGEMAGICK_BINARY', 'C:\Program Files\ImageMagick-7.1.1-31-Q16\magick.exe')`

I even tried:
`from moviepy.config import change_settings`
`change_settings({"IMAGEMAGICK_BINARY": r"C:\Program Files\ImageMagick\\convert.exe"})`

### **What to do now? I get the same error every time:**
Traceback (most recent call last):
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\video\VideoClip.py", line 1137, in __init__
    subprocess_call(cmd, logger=None)
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\tools.py", line 54, in subprocess_call
    raise IOError(err.decode('utf8'))
OSError: magick.exe: label expected `@C:\Users\LENOVO\AppData\Local\Temp\tmpusxywjtr.txt' @ error/annotate.c/GetMultilineTypeMetrics/804.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\Fatin\autoyt_vidmaker\main.py", line 31, in <module>
    makeFinalVideo(story, "./assets/temp/mp3/text_audio.mp3", "./assets/temp/images/antique shop.png", "./assets/temp/video/final_video.mp4")
  File "F:\Fatin\autoyt_vidmaker\final_video.py", line 14, in makeFinalVideo
    captions_clip = VideoClip(make_frame, duration=len(words))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\video\VideoClip.py", line 86, in __init__
    self.size = self.get_frame(0).shape[:2][::-1]
                ^^^^^^^^^^^^^^^^^
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\Clip.py", line 93, in get_frame
    return self.make_frame(t)
           ^^^^^^^^^^^^^^^^^^
  File "F:\Fatin\autoyt_vidmaker\final_video.py", line 12, in make_frame
    return TextClip(caption, fontsize=24, color='white').set_pos('center').set_duration(1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\moviepy\video\VideoClip.py", line 1146, in __init__
    raise IOError(error)
OSError: MoviePy Error: creation of None failed because of the following error:

magick.exe: label expected `@C:\Users\LENOVO\AppData\Local\Temp\tmpusxywjtr.txt' @ error/annotate.c/GetMultilineTypeMetrics/804.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect

_Originally posted by @TheCaptainCodes in https://github.com/Zulko/moviepy/issues/1966#issuecomment-2081525335_

**Comment by arielomdotcom** [comment]
Please provide the module Version, python version, etc.

**Comment by TheCaptainCodes** [comment]
> Please provide the module Version, python version, etc.

Everything's up-to-date

**Comment by ruangustavo** [comment]
Can you check if you have `convert.exe` installed?

I was experiencing the same problem, but I noticed that in the latest versions of ImageMagick `convert.exe` is deprecated and not installed by default

**Comment by antonpetrov145** [comment]
did you try setting the `IMAGEMAGICK_BINARY` variable in `.env` file?

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
