### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get_frame', reported by AudioFileClip.to_soundarray()

### ISSUE THREAD

**Issue by YAO-Shuyang** [Zulko/moviepy#2181]
#### Expected Behavior
Sound has been converted to numpy array

#### Actual Behavior
Traceback (most recent call last):
  File "c:\ProgramData\anaconda3\envs\replaypy\Lib\site-packages\replay\preprocess\frequency.py", line 29, in <module>
    audio = read_audio(dir_name)
  File "c:\ProgramData\anaconda3\envs\replaypy\Lib\site-packages\replay\preprocess\frequency.py", line 19, in read_audio
    audio_array = audio.to_soundarray()
  File "<decorator-gen-43>", line 2, in to_soundarray
  File "C:\ProgramData\anaconda3\envs\replaypy\lib\site-packages\moviepy\decorators.py", line 56, in requires_duration
    return f(clip, *a, **k)
  File "C:\ProgramData\anaconda3\envs\replaypy\lib\site-packages\moviepy\audio\AudioClip.py", line 122, in to_soundarray
    tuple(
  File "C:\ProgramData\anaconda3\envs\replaypy\lib\site-packages\moviepy\audio\AudioClip.py", line 90, in iter_chunks
    yield self.to_soundarray(
  File "<decorator-gen-43>", line 2, in to_soundarray
  File "C:\ProgramData\anaconda3\envs\replaypy\lib\site-packages\moviepy\decorators.py", line 56, in requires_duration
    return f(clip, *a, **k)
  File "C:\ProgramData\anaconda3\envs\replaypy\lib\site-packages\moviepy\audio\AudioClip.py", line 140, in to_soundarray
    snd_array = self.get_frame(tt)
  File "<decorator-gen-11>", line 2, in get_frame
  File "C:\ProgramData\anaconda3\envs\replaypy\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\ProgramData\anaconda3\envs\replaypy\lib\site-packages\moviepy\Clip.py", line 98, in get_frame
    return self.make_frame(t)
  File "C:\ProgramData\anaconda3\envs\replaypy\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 88, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)

#### Steps to Reproduce the Problem
Properteis of the audio of my video: 44.1 KHz sampling rate, 2 channels. 
AudioFileClip.to_soundarray() function did not work properly here...

  - Python Version: 3.10.14
  - MoviePy Version: 1.0.2, 1.0.3, 2.0.0dev2
  - Platform Name: Windows 10 Pro for Workstations
  - Platform Version: 22H2
![屏幕截图 2024-05-27 154841](https://github.com/Zulko/moviepy/assets/71874748/24033f34-138d-4d71-84de-d15866729481)

**Comment by YAO-Shuyang** [comment]
ummm...When I restarted my device, this error did not appear again. It now works.

**Comment by YAO-Shuyang** [comment]
umm...When I restarted my device, this error did not appear. It now works.
