### ISSUE TITLE
Unable to run moviepy on debian 10

### ISSUE THREAD

**Issue by belalsalih** [Zulko/moviepy#2189]
I am trying to run some processing on video uploaded by users using azure functions(python), my code runs perfectly on local pc(macOS) however it is not running at all once deployed on kubernetes.
logging into the pod and running: 'from moviepy.editor import *' will result in the following error:

```
>>> from moviepy.editor import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/moviepy/editor.py", line 36, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python3.9/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.audio.io.AudioFileClip import AudioFileClip
  File "/usr/local/lib/python3.9/site-packages/moviepy/audio/io/AudioFileClip.py", line 3, in <module>
    from moviepy.audio.AudioClip import AudioClip
  File "/usr/local/lib/python3.9/site-packages/moviepy/audio/AudioClip.py", line 7, in <module>
    from moviepy.audio.io.ffmpeg_audiowriter import ffmpeg_audiowrite
  File "/usr/local/lib/python3.9/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 7, in <module>
    from moviepy.config import get_setting
  File "/usr/local/lib/python3.9/site-packages/moviepy/config.py", line 36, in <module>
    FFMPEG_BINARY = get_exe()
  File "/usr/local/lib/python3.9/site-packages/imageio/plugins/ffmpeg.py", line 173, in get_exe
    return imageio_ffmpeg.get_ffmpeg_exe()
  File "/usr/local/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 28, in get_ffmpeg_exe
    exe = _get_ffmpeg_exe()
  File "/usr/local/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 44, in _get_ffmpeg_exe
    exe = os.path.join(_get_bin_dir(), FNAME_PER_PLATFORM.get(plat, ""))
  File "/usr/local/lib/python3.9/site-packages/imageio_ffmpeg/_utils.py", line 69, in _get_bin_dir
    ref = importlib.resources.files("imageio_ffmpeg.binaries") / "__init__.py"
  File "/usr/local/lib/python3.9/importlib/resources.py", line 147, in files
    return _common.from_package(_get_package(package))
  File "/usr/local/lib/python3.9/importlib/_common.py", line 14, in from_package
    return fallback_resources(package.__spec__)
  File "/usr/local/lib/python3.9/importlib/_common.py", line 18, in fallback_resources
    package_directory = pathlib.Path(spec.origin).parent
  File "/usr/local/lib/python3.9/pathlib.py", line 1082, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/local/lib/python3.9/pathlib.py", line 707, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/local/lib/python3.9/pathlib.py", line 691, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```
  - azure base image: FROM mcr.microsoft.com/azure-functions/python:3.0-python3.9
  - Python Version: 3.9.17
  - MoviePy Version: 1.0.3
  - Platform Name: linux (debian)
  - Platform Version: 10
pip list:
```
Package                        Version
------------------------------ -----------
azure-cognitiveservices-speech 1.37.0
azure-common                   1.1.28
azure-core                     1.30.1
azure-functions                1.19.0
azure-servicebus               7.1.0
azure-storage-blob             12.20.0
certifi                        2024.6.2
cffi                           1.16.0
charset-normalizer             3.3.2
cryptography                   42.0.7
decorator                      4.4.2
ffmpeg                         1.4
idna                           3.7
imageio                        2.34.1
imageio-ffmpeg                 0.5.0
isodate                        0.6.1
moviepy                        1.0.3
msrest                         0.7.1
numpy                          1.26.4
oauthlib                       3.2.2
opencv-python                  4.9.0.80
pillow                         10.3.0
pip                            23.0.1
proglog                        0.1.10
pycparser                      2.22
pyodbc                         5.1.0
python-dateutil                2.9.0.post0
requests                       2.32.3
requests-oauthlib              2.0.0
setuptools                     58.1.0
six                            1.16.0
tqdm                           4.66.4
typing_extensions              4.12.1
uamqp                          1.6.9
urllib3                        2.2.1
wheel                          0.40.0
```

thanks.

**Comment by antonpetrov145** [comment]
Same issue found on garuda linux
```
moviepy==1.0.3
```

As a workaround I changed  
```
FFMPEG_BINARY = os.getenv('FFMPEG_BINARY', 'ffmpeg-imageio')
```
to
```
FFMPEG_BINARY = os.getenv('FFMPEG_BINARY', 'auto-detect')
```
in `/venv/lib/python3.9/site-packages/moviepy/config_defaults.py`

and error is not present

**Comment by belalsalih** [comment]
since we are using azure devops to build/deploy the code, updating 'config_defaults.py' is not an option.
setting up an env variable 'FFMPEG_BINARY=/usr/bin/ffmpeg' as per your suggestion fixed the issue.

thanks alot for the help.

**Comment by antonpetrov145** [comment]
awesome

**Comment by studioj** [comment]
this is also happening on windows. A temporary fix could be to lock 
> imageio-ffmpeg<0.5

**Comment by antonpetrov145** [comment]
@keikoro if user doesn't set the `FFMPEG_BINARY` variable the default is `ffmpeg-imageio`
`FFMPEG_BINARY = os.getenv("FFMPEG_BINARY", "ffmpeg-imageio")`
but then
```
if FFMPEG_BINARY == "ffmpeg-imageio":
    from imageio.plugins.ffmpeg import get_exe

    FFMPEG_BINARY = get_exe()
```
my suggestion is to set the default to `auto-detect` then if user wants to use `ffmpeg-imageio` it can be set with ENV variable. With this the risk of the above error will be much lower IMO.

I tried both my suggestions - set to `auto-detect` and set env variable, both work. The question is - do we want to let users set the ENV or we can set to `auto-detect` by default in the code and have `ffmpeg-imageio` as option not relying on `imageio-ffmpeg`.

**Comment by keikoro** [comment]
Changing a default which a) has been in place for a long term, b) is documented and c) can very easily be circumvented by users may make sense in the long term but, as said elsewhere, would need discussing in one of the threads about the future of the project.

It's not something I'd be comfortable taking responsibility for _at this point_, with the project being kind of in limbo/awaiting review.

**Comment by antonpetrov145** [comment]
@keikoro good, I was confused by the naming of the function, I checked the code for them and yes - my mistake, I will close this PR.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
