### ISSUE TITLE
on_color fails with TypeError when given a col_opacity parameter

### ISSUE THREAD

**Issue by chunder** [Zulko/moviepy#25]
Here's a simple python script that shows the issue:

```
from moviepy.editor import *
txt= TextClip('Hello, world!')
this_works= txt.on_color()
this_fails= txt.on_color(col_opacity= 0.5)
```

That last statement throws the following error:

```
Traceback (most recent call last):
  File "./tmp.py", line 8, in <module>
    this_fails= txt.on_color(col_opacity= 0.5)
  File "/Users/chunder/py-projects/moviepy/lib/python2.6/site-packages/moviepy-0.2.1.6.93-py2.6.egg/moviepy/video/VideoClip.py", line 497, in on_color
    colorclip = colorclip.set_opacity(col_opacity)
  File "/Users/chunder/py-projects/moviepy/lib/python2.6/site-packages/moviepy-0.2.1.6.93-py2.6.egg/moviepy/video/VideoClip.py", line 533, in set_opacity
    newclip = newclip.add_mask()
  File "/Users/chunder/py-projects/moviepy/lib/python2.6/site-packages/moviepy-0.2.1.6.93-py2.6.egg/moviepy/video/VideoClip.py", line 472, in add_mask
    return self.set_mask( mask.set_duration(self.duration))
  File "<string>", line 2, in set_duration
  File "/Users/chunder/py-projects/moviepy/lib/python2.6/site-packages/moviepy-0.2.1.6.93-py2.6.egg/moviepy/decorators.py", line 12, in apply_to_mask
    newclip = f(clip, *a, **k)
  File "<string>", line 2, in set_duration
  File "/Users/chunder/py-projects/moviepy/lib/python2.6/site-packages/moviepy-0.2.1.6.93-py2.6.egg/moviepy/decorators.py", line 22, in apply_to_audio
    newclip = f(clip, *a, **k)
  File "<string>", line 2, in set_duration
  File "/Users/chunder/py-projects/moviepy/lib/python2.6/site-packages/moviepy-0.2.1.6.93-py2.6.egg/moviepy/decorators.py", line 71, in time_can_be_tuple
    return f(clip, *a, **k)
  File "/Users/chunder/py-projects/moviepy/lib/python2.6/site-packages/moviepy-0.2.1.6.93-py2.6.egg/moviepy/Clip.py", line 195, in set_duration
    newclip.end = newclip.start + t
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'
```

Here's my environment:

```
$ pip freeze
PIL==1.1.7
decorator==3.4.0
moviepy==0.2.1.6.93
numpy==1.8.0
wsgiref==0.1.2
```

**Comment by jitendra-koodo** [comment]
How to make "black" background disappear? How can I get full white text and remaining area should have full opacity green background? Not able to get this effect, maybe some specific type of blending is needed?
