### ISSUE TITLE
nvenc encoder nvidia

### ISSUE THREAD

**Issue by fortunto2** [Zulko/moviepy#264]
Hi don't support render with nvenc encoder

`[MoviePy] Writing video /ubuntu/conv/149557/film/24029/baaadhon.mp4
  0%|          | 0/1181 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.2.11-py3.4.egg/moviepy/video/io/ffmpeg_writer.py", line 137, in write_frame
    self.proc.stdin.write(img_array.tostring())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./1job.py", line 210, in <module>
    duration = template.fast.render(allParam, data)
  File "/ubuntu/newconv/template/fast.py", line 396, in render
    ffmpeg_params=ffmpeg_params, write_logfile=True)    
  File "<decorator-gen-51>", line 2, in write_videofile
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.2.11-py3.4.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.2.11-py3.4.egg/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.2.11-py3.4.egg/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.2.11-py3.4.egg/moviepy/video/VideoClip.py", line 338, in write_videofile
    ffmpeg_params=ffmpeg_params)
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.2.11-py3.4.egg/moviepy/video/io/ffmpeg_writer.py", line 216, in ffmpeg_write_video
    writer.write_frame(frame)
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.2.11-py3.4.egg/moviepy/video/io/ffmpeg_writer.py", line 139, in write_frame
    ffmpeg_error = self.proc.stderr.read()
AttributeError: 'NoneType' object has no attribute 'read'`

`    final.write_videofile(urlfilm, fps=30,
                        audio_bitrate="128k", bitrate=bitrate,codec='nvenc',
                        ffmpeg_params=ffmpeg_params, write_logfile=True)    
`

**Comment by fortunto2** [comment]
hm...
moviepy, using not my installed version ffmpeg
in system 2.8.6
in moviepy 2.4.2

where i can change path?

**Comment by Zulko** [comment]
```
from moviepy.config import change_settings
change_settings({"FFMPEG_BINARY":"ffmpeg"})
```

**Comment by fortunto2** [comment]
cool, thank you)) now work!

**Comment by sircambridge** [comment]
this worked for me too!
