### ISSUE TITLE
zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by fortunto2** [Zulko/moviepy#269]
hi, a common mistake in the files when creating audio. 
I add to the video, a music mp3 track.
What could be the problem?

`[MoviePy] Writing audio in baaadmot_15-19-1-1TEMP_MPY_wvf_snd.mp3
 38%|███▊      | 2045/5356 [00:03<00:05, 646.43it/s]----------
zero-size array to reduction operation minimum which has no identity
----------
Traceback (most recent call last):
  File "./render_last.py", line 318, in renderJob
    duration = template.fast2.render(allParam, data, concatPath)
  File "/ubuntu/newconv/template/fast2.py", line 301, in render
    ffmpeg_params=ffmpeg_params, threads=8, write_logfile=True)
  File "<string>", line 2, in write_videofile
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<string>", line 2, in write_videofile
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<string>", line 2, in write_videofile
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/video/VideoClip.py", line 330, in write_videofile
    verbose=verbose)
  File "<string>", line 2, in write_audiofile
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/AudioClip.py", line 204, in write_audiofile
    verbose=verbose, ffmpeg_params=ffmpeg_params)
  File "<string>", line 2, in ffmpeg_audiowrite
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/io/ffmpeg_audiowriter.py", line 161, in ffmpeg_audiowrite
    nbytes= nbytes, fps=fps):
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/tqdm/_tqdm.py", line 459, in __iter__
    for obj in iterable:
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/AudioClip.py", line 81, in generator
    buffersize=chunksize)
  File "<string>", line 2, in to_soundarray
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/AudioClip.py", line 127, in to_soundarray
    snd_array = self.get_frame(tt)
  File "<string>", line 2, in get_frame
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/AudioClip.py", line 293, in make_frame
    if (part is not False) ]
  File "<string>", line 2, in get_frame
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/fx/audio_fadeout.py", line 11, in fading
    gft = gf(t)
  File "<string>", line 2, in get_frame
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/fx/volumex.py", line 18, in <lambda>
    return clip.fl(lambda gf, t: factor * gf(t),
  File "<string>", line 2, in get_frame
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/io/AudioFileClip.py", line 71, in <lambda>
    self.make_frame =  lambda t: reader.get_frame(t)
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/audio/io/readers.py", line 173, in get_frame
    fr_min, fr_max = frames.min(), frames.max()
  File "/home/ubuntu/anaconda/lib/python2.7/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity
`

**Comment by Zulko** [comment]
Please post the code that ptoduces the error

**Comment by fortunto2** [comment]
I'm sorry, I have solved the problem. It was in my code, I added a short music by mistake
