### ISSUE TITLE
fine resolution subclips and scene randomization 

### ISSUE THREAD

**Issue by dmoracze** [Zulko/moviepy#290]
Hello,

I have a 13-minute long video clip and I am using subclip to splice the video into scenes based on timings in a .csv. Then, I am randomizing the scene order and assembling a new clip. Please note that I am new to python and even newer to moviepy.

Here is the construction of my .csv:
00:00:32.18,00:00:52.10,1
00:00:52.11,00:00:56.09,2
00:00:56.10,00:00:58.15,3
00:00:58.16,00:01:05.16,4
00:01:05.17,00:01:16.04,5

where column  1 is onset, column 2 is offset, and column 3 is scene number.

Here is my code:

```
import csv
import numpy as np
from moviepy.editor import *

f = open('scenecuts.csv')
csv_f = csv.reader(f)

scenes = []
ons = []
offs = []
for row in csv_f:
    ons.append(row[0])
    offs.append(row[1])
    scenes.append(row[2])

r_scene = scenes
np.random.seed(1000)
np.random.shuffle(r_scene)
r_scene = map(int, r_scene)

clip = VideoFileClip("myvideo.m4v")

temp = []
for row in r_scene:
    print(row)
    temp.append(clip.subclip(ons[row-1], offs[row-1]))

catclip = concatenate_videoclips(temp)
catclip_resize = catclip.resize((1024,576))
catclip_resize.write_videofile("random_video.mp4")
```

I have a couple of questions about the behavior of subclip and concatenate_videoclips:

1) What string format is subclip expecting? The examples in the documentation only provides cutting at the second level, but I need to have a fine resolution at the frame level. There is a line in the documentation that says, 

"Returns a clip playing the content of the current clip between times t_start and t_end, which can be expressed in seconds (15.35), in (min, sec), in (hour, min, sec), or as a string: ‘01:03:05.35’."

My .csv is providing strings similar to the latter example in the above sentence, however, I am not sure whether subclip is expecting the last number to be in frame. milliseconds, or centiseconds. It would be ideal for me to provide the video frame at which I can cut the clip and subclip would cut the video and audio at the exact same spot. Is this possible? Or do I have to provide millisecond or centisecond resolution?

2) I get inconsistent errors when I run the above code. The error appears to be in the line where subclip is called, but it is weirdly inconsistent. Sometimes it will fail during the first clip, sometimes it will make it about halfway through the clips and fail, or sometimes the whole thing will work. Here are my errors:

```
Traceback (most recent call last):

  File "<ipython-input-1-5a2e5f7899ee>", line 1, in <module>
    runfile('/Users/Dustin/Desktop/randomize_movie.py', wdir='/Users/Dustin/Desktop')

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 699, in runfile
    execfile(filename, namespace)

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 81, in execfile
    builtins.execfile(filename, *where)

  File "/Users/Dustin/Desktop/randomize_movie.py", line 29, in <module>
    temp.append(clip.subclip(ons[row-1], offs[row-1]))

  File "<decorator-gen-161>", line 2, in subclip

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)

  File "<decorator-gen-160>", line 2, in subclip

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/decorators.py", line 29, in apply_to_mask
    newclip = f(clip, *a, **k)

  File "<decorator-gen-159>", line 2, in subclip

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/decorators.py", line 41, in apply_to_audio
    newclip = f(clip, *a, **k)

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/Clip.py", line 387, in subclip
    newclip = self.fl_time(lambda t: t + t_start, apply_to=[])

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/Clip.py", line 189, in fl_time
    keep_duration=keep_duration)

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/Clip.py", line 136, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))

  File "<decorator-gen-179>", line 2, in set_make_frame

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/decorators.py", line 14, in outplace
    f(newclip, *a, **k)

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/video/VideoClip.py", line 654, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]

  File "<decorator-gen-136>", line 2, in get_frame

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/Clip.py", line 188, in <lambda>
    return self.fl(lambda gf, t: gf(t_func(t)), apply_to,

  File "<decorator-gen-136>", line 2, in get_frame

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/video/io/VideoFileClip.py", line 74, in <lambda>
    self.make_frame = lambda t: reader.get_frame(t)

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 159, in get_frame
    self.initialize(t)

  File "/Users/Dustin/anaconda/lib/python2.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 87, in initialize
    self.proc = sp.Popen(cmd, **popen_params)

  File "/Users/Dustin/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)

  File "/Users/Dustin/anaconda/lib/python2.7/subprocess.py", line 1316, in _execute_child
    data = _eintr_retry_call(os.read, errpipe_read, 1048576)

  File "/Users/Dustin/anaconda/lib/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)

OSError: [Errno 22] Invalid argument
```

It appears to be an error in subprocess, but I can't find a solution.

3) Once I have randomized my clip order using the above code (say I have 32 scenes) and wrote to a new video file, there are issues with the audio. It begins fine, but about half way through the new video file, it sounds as though multiple audio tracks become overdubbed and I can hear two tracks at once. This behavior does not make sense to me because I thought that subclip would splice the video and audio at the same place and concatenate_videoclips just concatenates them together. How can the audio   become mixed and how could I correct this?

Thanks!

**Comment by dmoracze** [comment]
Of my 3 questions, I have some new information.

For question 2:
I am running the code in Spyder, but when I run the script from a terminal or from Sublime Text, the code "works". I do not get the above error. However, this brings me to question 3:

I am still having overdub audio problems. It sounds like 2 audio tracks are overlaid on one another. What is weird is that when I divide the clip up (based on the timing in the CSV), and reassemble it in order (not randomized), I don't have audio problems. There is something about randomizing the order that is causing this.

**Comment by pydo** [comment]
1. subclip appears to expect an int and expresses those values as seconds

2. Are you running different python interpreters? Maybe the one in spyder is not the same as the one you run from the cmdline.

**Comment by kerstin** [comment]
Statements like

> What string format is subclip expecting?

and

> subclip appears to expect an int and expresses those values as seconds

make me think this isn't documented well (enough)

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
