### ISSUE TITLE
WindowsError: [Error 5] Access is denied

### ISSUE THREAD

**Issue by ghost** [Zulko/moviepy#294]
Windows 10

https://paste.pound-python.org/show/ERVVxg7SfuxhTY7NMO4f/

this is my first bug report ever.

python 2.7
## pip install moviepy

```
from moviepy.editor import *
test = VideoFileClip('test.mp4')
```
---
```
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    test = VideoFileClip('test.mp4')
  File "C:\Python27\lib\site-packages\moviepy\video\io\VideoFileClip.py", line 55, in **init**
    reader = FFMPEG_VideoReader(filename, pix_fmt=pix_fmt)
  File "C:\Python27\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 32, in **init**
    infos = ffmpeg_parse_infos(filename, print_infos, check_duration)
  File "C:\Python27\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 240, in ffmpeg_parse_infos
    proc.terminate()
  File "C:\Python27\lib\subprocess.py", line 1002, in terminate
    _subprocess.TerminateProcess(self._handle, 1)
WindowsError: [Error 5] Access is denied
Exception AttributeError: "VideoFileClip instance has no attribute 'reader'" in <bound method VideoFileClip.__del__ of <
moviepy.video.io.VideoFileClip.VideoFileClip instance at 0x0000000002178AC8>> ignored
```

**Comment by hxhjx** [comment]
this error is related to some library changes.

when i copy my whole pyhton folder over to the not working maschines, it works

**Comment by earney** [comment]
@hxhjx ..  we think we have this fixed.. Can you try getting the code from the repo and trying again?

**Comment by tburrows13** [comment]
Closing as I'm pretty sure this is fixed, and is an old issue.
