### ISSUE TITLE
Writing video works fine in Django without Celery but getting WindowsError: [Error 5] Access is denied with Celery

### ISSUE THREAD

**Issue by JMIdeaMaker** [Zulko/moviepy#298]
As the title says I am having some permission problems in celery. Does anyone have any pointers?

```
[2016-06-04 22:25:04,924: ERROR/MainProcess] Task engine.tasks.MyWriteVideoTask[b3fb6d
7c-06e8-4b67-9ba3-eba784a66952] raised unexpected: WindowsError(5, 'Access is denied')
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\celery\app\trace.py", line 240, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "c:\python27\lib\site-packages\celery\app\trace.py", line 438, in **protected_ca
ll**
    return self.run(_args, *_kwargs)
  File "c:\python27\lib\site-packages\jobtastic\task.py", line 362, in run
    task_result = self.calculate_result(_args, *_kwargs)
  File "c:\Users\Mike\projects\myproject-master-folder\myproject\engine\tasks.p
y", line 75, in calculate_result
    cc.write_videofile(vn_full_path,fps=24)
  File "<decorator-gen-51>", line 2, in write_videofile
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\decorators.py"
, line 54, in requires_duration
    return f(clip, _a, *_k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\decorators.py"
, line 137, in use_clip_fps_by_default
    return f(clip, _new_a, *_new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\decorators.py"
, line 22, in convert_masks_to_RGB
    return f(clip, _a, *_k)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\video\VideoCli
p.py", line 330, in write_videofile
    verbose=verbose)
  File "<decorator-gen-73>", line 2, in write_audiofile
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\decorators.py"
, line 54, in requires_duration
    return f(clip, _a, *_k)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\AudioCli
p.py", line 204, in write_audiofile
    verbose=verbose, ffmpeg_params=ffmpeg_params)
  File "<decorator-gen-70>", line 2, in ffmpeg_audiowrite
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\decorators.py"
, line 54, in requires_duration
    return f(clip, _a, *_k)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\io\ffmpe
g_audiowriter.py", line 161, in ffmpeg_audiowrite
    nbytes= nbytes, fps=fps):
  File "c:\python27\lib\site-packages\tqdm_tqdm.py", line 579, in **iter**
    for obj in iterable:
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\AudioCli
p.py", line 81, in generator
    buffersize=chunksize)
  File "<decorator-gen-72>", line 2, in to_soundarray
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\decorators.py"
, line 54, in requires_duration
    return f(clip, _a, *_k)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\AudioCli
p.py", line 127, in to_soundarray
    snd_array = self.get_frame(tt)
  File "<decorator-gen-14>", line 2, in get_frame
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\decorators.py"
, line 89, in wrapper
    return f(_new_a, *_new_kw)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\Clip.py", line
 95, in get_frame
    return self.make_frame(t)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\AudioCli
p.py", line 293, in make_frame
    if (part is not False) ]
  File "<decorator-gen-14>", line 2, in get_frame
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\decorators.py"
, line 89, in wrapper
    return f(_new_a, *_new_kw)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\Clip.py", line
 95, in get_frame
    return self.make_frame(t)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\io\Audio
FileClip.py", line 71, in <lambda>
    self.make_frame =  lambda t: reader.get_frame(t)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\io\reade
rs.py", line 182, in get_frame
    self.buffer_around(fr_max)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\io\reade
rs.py", line 230, in buffer_around
    self.seek(new_bufferstart)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\io\reade
rs.py", line 140, in seek
    self.initialize(t)
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\io\reade
rs.py", line 77, in initialize
    self.close_proc() # if any
  File "c:\python27\lib\site-packages\moviepy-0.2.2.11-py2.7.egg\moviepy\audio\io\reade
rs.py", line 151, in close_proc
    self.proc.terminate()
  File "c:\python27\lib\subprocess.py", line 1019, in terminate
    _subprocess.TerminateProcess(self._handle, 1)
WindowsError: [Error 5] Access is denied
```

**Comment by kerstin** [comment]
@audioburn did you manage to solve your issue?
