### ISSUE TITLE
Attribute Error (Raspberry Pi)

### ISSUE THREAD

**Issue by Gloin1313** [Zulko/moviepy#332]
```
from moviepy.editor import *
clip = ImageClip("picture.jpg")
```

The above code outputs the following error:

```
AttributeError: 'module' object has no attribute 'find_loader'
```

I am running this with Python 3.2 on Raspian Wheezy (RPi 2).
What is wrong?

**Comment by Gloin1313** [comment]
A more complete error message:
Traceback (most recent call last):
  File "/home/pi/qfp/moviepytest.py", line 3, in <module>
    clip = ImageClip("pic1.jpg")
  File "/usr/local/lib/python3.2/dist-packages/moviepy/video/VideoClip.py", line 895, in __init__
    img = imread(img)
  File "/usr/local/lib/python3.2/dist-packages/imageio/core/functions.py", line 185, in imread
    reader = read(uri, format, 'i', **kwargs)
  File "/usr/local/lib/python3.2/dist-packages/imageio/core/functions.py", line 105, in get_reader
    format = formats.search_read_format(request)
  File "/usr/local/lib/python3.2/dist-packages/imageio/core/format.py", line 601, in search_read_format
    if format.can_read(request):
  File "/usr/local/lib/python3.2/dist-packages/imageio/core/format.py", line 178, in can_read
    return self._can_read(request)
  File "/usr/local/lib/python3.2/dist-packages/imageio/plugins/simpleitk.py", line 61, in _can_read
    if has_module('SimpleITK'):
  File "/usr/local/lib/python3.2/dist-packages/imageio/core/util.py", line 539, in has_module
    return importlib.find_loader(module_name) is not None
AttributeError: 'module' object has no attribute 'find_loader'

**Comment by earney** [comment]
@Gloin1313 .. are you still having this issue?

**Comment by Gloin1313** [comment]
See #333
