### ISSUE TITLE
crossfadeout "Attribute 'duration' not set"

### ISSUE THREAD

**Issue by groundflyer** [Zulko/moviepy#354]
When trying to crossfadeout a clip with defined duration `ValueError: Attribute 'duration' not set ` raised.

**Comment by kerstin** [comment]
@groundflyer Does the bug persist on your end, using the current version of MoviePy? It might have been fixed with changes recently made to the code base, just wondering if you can still reproduce it (and how).

**Comment by groundflyer** [comment]
@kerstin @earney 
I just tested the master branch with such a snippet:
```python
from moviepy import editor

clip = editor.ImageClip("comp/title_end.jpg")

clip.duration = 10
crosstime = 1

caption = editor.TextClip("test text", font="Liberation-Sans-Bold", color='white', stroke_color='gray', stroke_width=2, method='caption', size=(1280, 720), fontsize=60, align='South-East')
caption.duration = clip.duration
fadecaption = caption.crossfadein(crosstime).crossfadeout(crosstime)
ret = editor.CompositeVideoClip([clip, fadecaption])
```
and still getting the same error.
```
Traceback (most recent call last):
  File "test_crossfade_out.py", line 10, in <module>
    fadecaption = caption.crossfadein(crosstime).crossfadeout(crosstime)
  File "<decorator-gen-81>", line 2, in crossfadeout
  File "/home/toster/.local/lib64/python3.4/site-packages/moviepy-0.2.2.13-py3.4.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-80>", line 2, in crossfadeout
  File "/home/toster/.local/lib64/python3.4/site-packages/moviepy-0.2.2.13-py3.4.egg/moviepy/decorators.py", line 104, in add_mask_if_none
    return f(clip, *a, **k)
  File "/home/toster/.local/lib64/python3.4/site-packages/moviepy-0.2.2.13-py3.4.egg/moviepy/video/compositing/transitions.py", line 29, in crossfadeout
    newclip.mask = clip.mask.fx(fadeout, duration)
  File "/home/toster/.local/lib64/python3.4/site-packages/moviepy-0.2.2.13-py3.4.egg/moviepy/Clip.py", line 215, in fx
    return func(self, *args, **kwargs)
  File "<decorator-gen-78>", line 2, in fadeout
  File "/home/toster/.local/lib64/python3.4/site-packages/moviepy-0.2.2.13-py3.4.egg/moviepy/decorators.py", line 52, in requires_duration
    raise ValueError("Attribute 'duration' not set")
ValueError: Attribute 'duration' not set
```

**Comment by earney** [comment]
I believe there is an issue where duration is not being set correctly, with clips and masks.  I hint at this in PR 435.  This maybe an issue that @zulko will need to look into.
