### ISSUE TITLE
Bug in write_gif

### ISSUE THREAD

**Issue by virtualritz** [Zulko/moviepy#359]
The `opt` parameter, which steers the selection of the palette quantization method for imageio, is erroneously passed to `write_gif_with_tempfiles` and in there being forwarded to the `-layers` parameter of ImageMagick's `convert` tool, causing the latter to fail:

```
[MoviePy] Building file EYED0229/00002532_00002729.gif
----------------------------------------
[MoviePy] Generating GIF frames...
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 59/59 [00:36<00:00,  1.60it/s]
[MoviePy] Optimizing GIF with ImageMagick...
[MoviePy] Running:
>>> convert -delay 3 -dispose 1 -loop 0 EYED0229/00002532_00002729_GIFTEMP*.png -coalesce -layers wu -fuzz 00% -colors 256 EYED0229/00002532_00002729.gif
[MoviePy] This command returned an error !Traceback (most recent call last):
  File "/Users/moeller/code/makegifs.py", line 49, in <module>
    clip.subclip(start, end).write_gif(file_name, program='ImageMagick', tempfiles=True, verbose=True, colors=256, fuzz=0 )
  File "<decorator-gen-56>", line 2, in write_gif
  File "/Library/Python/2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-55>", line 2, in write_gif
  File "/Library/Python/2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/Library/Python/2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/video/VideoClip.py", line 468, in write_gif
    loop=loop, dispose=dispose, colors=colors)
  File "<decorator-gen-10>", line 2, in write_gif_with_tempfiles
  File "/Library/Python/2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-9>", line 2, in write_gif_with_tempfiles
  File "/Library/Python/2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "/Library/Python/2.7/site-packages/moviepy-0.2.2.11-py2.7.egg/moviepy/video/io/gif_writers.py", line 94, in write_gif_with_tempfiles
    raise IOError(error)
IOError: MoviePy Error: creation of EYED0229/00002532_00002729.gif failed because of the following error:

convert: UnrecognizedLayerMethod `wu' @ error/convert.c/ConvertImageCommand/1962.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py.

```

**Comment by mehmetkose** [comment]
+1

**Comment by earney** [comment]
pull request #471 should fix this issue.

**Comment by earney** [comment]
this has been fixed in the repo.

**Comment by ashbeats** [comment]
Is the PIP repo updated?

**Comment by earney** [comment]
I think it has been 2 or 3 weeks since it has been updated.
