### ISSUE TITLE
Can not load the fonts

### ISSUE THREAD

**Issue by Netherdrake** [Zulko/moviepy#36]
Hi,

I can't get the TextClip to work, since any font I tried errors out. I'm on MacOS 10.9.2.

```
~ % python
Python 2.7.6 (default, Apr  9 2014, 11:48:52) 
[GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from moviepy.editor import *
>>> txt = TextClip("V. Zulkoninov - Ukulele Sonata", font='Arial-regular')

MoviePy: WARNING !
   The following command returned an error:
convert: unable to read font `Arial-regular' @ warning/annotate.c/RenderType/871.
convert: unable to read font `Arial-regular' @ error/annotate.c/RenderFreetype/1126.
convert: Postscript delegate failed `/var/tmp/magick-687910PjuTb0L0M2g': No such file or directory @ error/ps.c/ReadPSImage/840.
convert: unable to read font `Arial-regular' @ warning/annotate.c/RenderType/871.
convert: unable to read font `Arial-regular' @ error/annotate.c/RenderFreetype/1126.
convert: Postscript delegate failed `/var/tmp/magick-687918Bk0Mx9P3V8w': No such file or directory @ error/ps.c/ReadPSImage/840.
convert: no images defined `PNG32:/var/folders/lf/myf7bjr57_jg7_5c4014bh640000gn/T/tmpGNVPDe.png' @ error/convert.c/ConvertImageCommand/3150.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/moviepy/video/VideoClip.py", line 1078, in __init__
    subprocess_call(cmd, verbose=False )
  File "/usr/local/lib/python2.7/site-packages/moviepy/tools.py", line 34, in subprocess_call
    raise IOError
IOError
>>> 
```

**Comment by subcontrabass** [comment]
Thanks Netherdrake! Worked great.
