### ISSUE TITLE
It makes pygame crash

### ISSUE THREAD

**Issue by Netherdrake** [Zulko/moviepy#37]
```
Python 2.7.6 (default, Feb 26 2014, 12:07:17) 
[GCC 4.8.2 20140206 (prerelease)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from moviepy.editor import *
>>> backgroundClip = ColorClip((1280,720))
>>> backgroundClip.set_duration(2).preview
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 2, in preview
  File "/usr/lib/python2.7/site-packages/moviepy/decorators.py", line 60, in requires_duration
    return f(clip, *a, **k)
  File "/usr/lib/python2.7/site-packages/moviepy/video/io/preview.py", line 94, in preview
    imdisplay(img, screen)
  File "/usr/lib/python2.7/site-packages/moviepy/video/io/preview.py", line 13, in imdisplay
    a = pg.surfarray.make_surface(imarray.swapaxes(0, 1))
  File "/usr/lib/python2.7/site-packages/pygame/surfarray.py", line 243, in make_surface
    return numpysf.make_surface (array)
  File "/usr/lib/python2.7/site-packages/pygame/_numpysurfarray.py", line 368, in make_surface
    blit_array (surface, array)
  File "/usr/lib/python2.7/site-packages/pygame/_numpysurfarray.py", line 437, in blit_array
    surface.get_buffer ().write (data, 0)
IndexError: bytes to write exceed buffer size
>>> 
```

```
~ % pacman -Q python2-pygame
python2-pygame 1.9.1-8
~ % 
```

**Comment by chankim** [comment]
Hi, It's a very old post, but, how did you solve it? (from https://bugs.launchpad.net/ubuntu/+source/pygame/+bug/1336214 someone says, it was solved in pygame 1.9.3 but I'm using 1.9.1 like you. on ubunt 16.04).
