### ISSUE TITLE
TextClip.list('color') failed to return color list

### ISSUE THREAD

**Issue by liketemple** [Zulko/moviepy#371]
```
>>> editor.TextClip.list('color')
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-c289bccc81e5>", line 1, in <module>
    editor.TextClip.list('color')
  File "/usr/local/lib/python3.5/site-packages/moviepy/video/VideoClip.py", line 1179, in list
    return [l.split(" ")[1] for l in lines[2:]]
  File "/usr/local/lib/python3.5/site-packages/moviepy/video/VideoClip.py", line 1179, in <listcomp>
    return [l.split(" ")[1] for l in lines[2:]]
TypeError: a bytes-like object is required, not 'str'
```

It seems the imageMagick return a binary str.

**Comment by dermusikman** [comment]
I have this same issue with font:
```
>>> TextClip.list('font')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/moviepy/video/VideoClip.py", line 1177, in list
    return [l[8:] for l in lines if l.startswith("  Font:")]
  File "/usr/lib/python3.5/site-packages/moviepy/video/VideoClip.py", line 1177, in <listcomp>
    return [l[8:] for l in lines if l.startswith("  Font:")]
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```

**Comment by Gloin1313** [comment]
Is this related to http://stackoverflow.com/questions/42298261/no-available-fonts-in-moviepy? Running the exact same command.

**Comment by dermusikman** [comment]
I've never seen the function work, so I can't speak to the relevancy of the StackOverflow issue.

**Comment by kerstin** [comment]
There seems to be a(n untested) PR for the fonts-related issue. #306

**Comment by earney** [comment]
PR #306 has been merged, so closing this issue.
