### ISSUE TITLE
moviepy not able to find installed ffmpeg    bug?

### ISSUE THREAD

**Issue by arnieadm35** [Zulko/moviepy#396]
This is the error I'm getting running the cool text example:

[MoviePy] Writing video ../../coolTextEffects.avi 0%| | 0/501 [00:00<?, ?it/s] Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 137, in write_frame self.proc.stdin.write(img_array.tostring()) BrokenPipeError: [Errno 32] Broken pipe
During handling of the above exception, another exception occurred:
Traceback (most recent call last): File "testmovie.py", line 64, in <module> final_clip.write_videofile('../../coolTextEffects.avi',fps=25,codec='png') File "<decorator-gen-51>", line 2, in write_videofile File "/usr/local/lib/python3.5/dist-packages/moviepy/decorators.py", line 54, in requires_duration return f(clip, a, *k) File "<decorator-gen-50>", line 2, in write_videofile File "/usr/local/lib/python3.5/dist-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default return f(clip, new_a, *new_kw) File "<decorator-gen-49>", line 2, in write_videofile File "/usr/local/lib/python3.5/dist-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB return f(clip, a, *k) File "/usr/local/lib/python3.5/dist-packages/moviepy/video/VideoClip.py", line 338, in write_videofile ffmpeg_params=ffmpeg_params) File "/usr/local/lib/python3.5/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 216, in ffmpeg_write_video writer.write_frame(frame) File "/usr/local/lib/python3.5/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 144, in write_frame if "Unknown encoder" in ffmpeg_error: TypeError: a bytes-like object is required, not 'str'
commenteditsharesavehidedeletensfwspoiler

**Comment by earney** [comment]
see issue 401 for a fix for this problem.

**Comment by earney** [comment]
this should be resolved with the new version 0.2.2.13.  Should we close this issue?

**Comment by Gloin1313** [comment]
Yes
