### ISSUE TITLE
when I from moviepy.editor import *,  There cause exception,That's why.......

### ISSUE THREAD

**Issue by linzhi** [Zulko/moviepy#436]
>>> from moviepy.editor import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/moviepy/editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python2.7/site-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/usr/local/lib/python2.7/site-packages/moviepy/video/VideoClip.py", line 20, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "/usr/local/lib/python2.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 19, in <module>
    from moviepy.config import get_setting
  File "/usr/local/lib/python2.7/site-packages/moviepy/config.py", line 38, in <module>
    FFMPEG_BINARY = get_exe()
  File "/usr/local/lib/python2.7/site-packages/imageio/plugins/ffmpeg.py", line 86, in get_exe
    raise NeedDownloadError('Need ffmpeg exe. '
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download it by calling:
  imageio.plugins.ffmpeg.download()

**Comment by linzhi** [comment]
Sorry, I had solve it, It caused by that I don't install ffmpeg in my MAC OS
