### ISSUE TITLE
Sierra OSX cannot install moviepy

### ISSUE THREAD

**Issue by jovendor** [Zulko/moviepy#555]
I am in MacOS Sierra 10.12.4 running python 2.7.10. and tried different ways installing it wit several errors for example:

`pip install moviepy`

```shell
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: `'/Library/Python/2.7/site-packages/decorator.py'`
```
Is there any way I can fix that error please?

**Comment by mbeacom** [comment]
This is due to a permission issue with your python environment.  It appears `decorator` has already been installed and the user you're attempting to `pip install moviepy` from doesn't have access to the previously installed global dependency.

I recommend you use a virtual environment or the docker image provided.

Example with virtualenv:
```
$ uname -mrs
Darwin 16.6.0 x86_64

$ sudo pip install virtualenv

$ virtualenv -p python2 moviepy2
Running virtualenv with interpreter /usr/local/bin/python2
New python executable in /Users/markbeacom/.virtualenv/moviepy2/bin/python2.7
Also creating executable in /Users/markbeacom/.virtualenv/moviepy2/bin/python
Installing setuptools, pip, wheel...done.

$ workon moviepy2

moviepy2> $ pip freeze
appdirs==1.4.3
packaging==16.8
pyparsing==2.2.0
six==1.10.0

moviepy2> $ python --version
Python 2.7.13

moviepy2> $ pip install moviepy
Collecting moviepy
  Using cached moviepy-0.2.3.2-py2.py3-none-any.whl
Collecting imageio==2.1.2 (from moviepy)
Collecting tqdm==4.11.2 (from moviepy)
  Using cached tqdm-4.11.2-py2.py3-none-any.whl
Collecting numpy (from moviepy)
  Using cached numpy-1.12.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting decorator==4.0.11 (from moviepy)
  Using cached decorator-4.0.11-py2.py3-none-any.whl
Collecting pillow (from imageio==2.1.2->moviepy)
  Using cached Pillow-4.1.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Collecting olefile (from pillow->imageio==2.1.2->moviepy)
Installing collected packages: olefile, pillow, numpy, imageio, tqdm, decorator, moviepy
Successfully installed decorator-4.0.11 imageio-2.1.2 moviepy-0.2.3.2 numpy-1.12.1 olefile-0.44 pillow-4.1.0 tqdm-4.11.2

moviepy2> $ pip freeze
appdirs==1.4.3
decorator==4.0.11
imageio==2.1.2
moviepy==0.2.3.2
numpy==1.12.1
olefile==0.44
packaging==16.8
Pillow==4.1.0
pyparsing==2.2.0
six==1.10.0
tqdm==4.11.2
```

Or follow the [docker example](http://zulko.github.io/moviepy/docker.html)

**Comment by jovendor** [comment]
Is it possible to install additional Python for example Python3 so that I have it separated from the existing in OS X and then install moviepy? I tried with a correctly working Python 3.6 but when I tried installing moviepy to this version it keeps looking automatically for the one in OS X photon 2.7.

**Comment by earney** [comment]
@jovendor   see @mbeacom 's example of using virtualenv.  that should give you what you want.

**Comment by jovendor** [comment]
Thanks for your help. I installed with virtualenv and it is working good!

**Comment by mbeacom** [comment]
@jovendor You can create an additional virtual environment to use Python 3, as @earney stated.

`virtualenv -p python3 moviepy3` should do it. 

_Note: `python3` in the above case is the python3 executable, typically syslinked to `python3`_

Closing this per your above message.

Thanks for using moviepy!
