### ISSUE TITLE
FFMPEG binary not found.

### ISSUE THREAD

**Issue by rajasimon** [Zulko/moviepy#60]
I installed numpy using sudo. After i run the example it's throws below error.

root@ri-desktop:~/studio/master/moviepy-master/moviepy-master/examples# python         example_with_sound.py 
Traceback (most recent call last):
  File "example_with_sound.py", line 8, in <module>
    from moviepy.editor import *
  File "/usr/local/lib/python2.7/dist-packages/moviepy-0.2.1.8.09-py2.7.egg/moviepy/editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python2.7/dist-packages/moviepy-0.2.1.8.09-py2.7.egg/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/usr/local/lib/python2.7/dist-packages/moviepy-0.2.1.8.09-py2.7.egg/moviepy/video/VideoClip.py", line 21, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "/usr/local/lib/python2.7/dist-packages/moviepy-0.2.1.8.09-py2.7.egg/moviepy/video/io/ffmpeg_writer.py", line 19, in <module>
    from moviepy.conf import FFMPEG_BINARY
  File "/usr/local/lib/python2.7/dist-packages/moviepy-0.2.1.8.09-py2.7.egg/moviepy/conf.py", line 61, in <module>
    raise IOError("FFMPEG binary not found. Try installing MoviePy"
IOError: FFMPEG binary not found. Try installing MoviePy manually and specify the path to the binary in the file conf.py'

**Comment by Zulko** [comment]
I'm closing this as old (MoviePy now relies on ImageIO for ffmpeg)

**Comment by harsh1795** [comment]
Hey i installed MoviePy on my ubuntu computer but when i run this:
from moviepy.editor import *
Imageio: 'ffmpeg.linux64' was not found on your computer; downloading it now.

But it doesn't download. I downloaded manually "ffmpeg.linux64" , now i m not sure where to place it. Can you please help.
