### ISSUE TITLE
line 54, in requires_duration return

### ISSUE THREAD

**Issue by KeesvanUnen** [Zulko/moviepy#601]
When I try the next example:

```
import numpy as np
import gizeh
import moviepy.editor as mpy

W,H = 128, 128
duration = 2
ncircles = 20

def make_frame(t):


	surface = gizeh.Surface(W,H)

	for i in range(ncircles):
		angle = 2 * np.pi * (1.0*i/ncircles+t/duration)
		center = W * (0.5 + gizeh.polar2cart(0.1, angle))
		circle = gizeh.circle (r = W * (1.0 - 1.0 * i/ncircles),
				       xy = center, fill = (i%2, i%2, i%2))
		circle.draw(surface)

	return surface.get_npimage()

clip = mpy.VideoClip(make_frame, duration = duration)
clip.write_gif("circles.gif", fps=15, opt="OptimizePlus", fuzz=10)
```

I receive the following errors:

```
  0%|          | 0/31 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "gizehtest.py", line 24, in <module>
    clip.write_gif("circles.gif", fps=15, opt="OptimizePlus", fuzz=10)
  File "<decorator-gen-56>", line 2, in write_gif
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.3.2-py3.4.egg/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-55>", line 2, in write_gif
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.3.2-py3.4.egg/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.3.2-py3.4.egg/moviepy/video/VideoClip.py", line 475, in write_gif
    verbose=verbose, colors=colors)
  File "/usr/local/lib/python3.4/dist-packages/moviepy-0.2.3.2-py3.4.egg/moviepy/video/io/gif_writers.py", line 288, in write_gif_with_image_io
    writer.append_data(frame)
  File "/usr/local/lib/python3.4/dist-packages/imageio-2.1.2-py3.4.egg/imageio/core/format.py", line 481, in append_data
    return self._append_data(im, total_meta)
  File "/usr/local/lib/python3.4/dist-packages/imageio-2.1.2-py3.4.egg/imageio/plugins/pillowmulti.py", line 101, in _append_data
    self._writer.add_image(im, duration, dispose)
  File "/usr/local/lib/python3.4/dist-packages/imageio-2.1.2-py3.4.egg/imageio/plugins/pillowmulti.py", line 146, in add_image
    self.opt_palette_size)
  File "/usr/local/lib/python3.4/dist-packages/imageio-2.1.2-py3.4.egg/imageio/plugins/pillowmulti.py", line 332, in converToPIL
    im_pil = ndarray_to_pil(im, 'gif')
  File "/usr/local/lib/python3.4/dist-packages/imageio-2.1.2-py3.4.egg/imageio/plugins/pillow.py", line 483, in ndarray_to_pil
    array_buffer = arr.tobytes()
AttributeError: 'numpy.ndarray' object has no attribute 'tobytes'
```

Is there somebody who can help me?
Thanks,
Kees

**Comment by Gloin1313** [comment]
Can you try replacing the call tobytes with tostring?

**Comment by Gloin1313** [comment]
Actually #499 is the same problem. Try upgrading numpy with 'pip install numpy --upgrade--'

**Comment by KeesvanUnen** [comment]
Hi Gloin1313,

Thanks for your response. I replaced the tobytes with tostrings. When I try to upgrade numpy the message 'importerror: no module named 'pkg_resources' appears. The same message appears when I use 'sudo pip install numpy'.

**Comment by Gloin1313** [comment]
@KeesvanUnen does that error occur when you try to do anything with pip? Does [this](https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources) help?

**Comment by KeesvanUnen** [comment]
Thanks Gloin1313. After installing Python 3.6 the problem seems to be resolved.
