### ISSUE TITLE
clips from gif  to composite getting audio composite error

### ISSUE THREAD

**Issue by carsonDB** [Zulko/moviepy#620]
I get a clip from a gif. And slip it into two parts. The second one is set a audio (mp3).
```python
entire_clip = VideoFileClip('examples/xxx.gif')
audio = AudioFileClip('materials/xxx.mp3')
clip1 = entire_clip.subclip(0, 0.8)
clip2 = entire_clip.subclip(0.8, entire_clip.duration)

clip2 = clip2.set_audio(audio)
final_clip = CompositeVideoClip([clip1, clip2])
final_clip.preview(fps=10)
```
My computer is Ubuntu 16.04.
Results are:
> Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "<decorator-gen-210>", line 2, in preview
  File "/usr/local/lib/python2.7/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/usr/local/lib/python2.7/dist-packages/moviepy/audio/io/preview.py", line 49, in preview
    sndarray = clip.to_soundarray(tt,nbytes=nbytes, quantize=True)
  File "<decorator-gen-72>", line 2, in to_soundarray
  File "/usr/local/lib/python2.7/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/usr/local/lib/python2.7/dist-packages/moviepy/audio/AudioClip.py", line 107, in to_soundarray
    fps = self.fps
AttributeError: CompositeAudioClip instance has no attribute 'fps'

I don't know where is the cause. How can I solve this problem? Thx.

**Comment by alexzach** [comment]
It actually looks like CompositeAudioClips doesn't set the fps of the output clip.
It's a bug in moviepy, as the philosophy of moviepy is to let the end user not to bother about fps.

You can manually set the fps after the compositing made:
`final_clip.audio = final_clip.audio.set_fps(the_right_audio_fps)`
or on the other hand you can assign the audio after CompositingVideo: `final_clip = CompositeVideoClip([clip1, clip2]).set_audio(audio)`.

**Comment by keikoro** [comment]
This is a very old issue which hasn't seen any updates in years, so it's dubious/impossible to tell if it's still relevant.

Closing for this reason, but do report back if the issue persists when you try with the latest master (_not_ the last PyPI release).
