### ISSUE TITLE
freeze when reading video clip

### ISSUE THREAD

**Issue by magicknight** [Zulko/moviepy#647]
Hi, this program freezed when reading a flv format video. there is no error throw,  no exit or printing information, just freeze. 

```
Traceback (most recent call last):
  File "./youtube.py", line 114, in <module>
    video_process(video_file, output=output_video)
  File "./youtube.py", line 89, in video_process
    clip = VideoFileClip(mp4_file)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/io/VideoFileClip.py", line 111, in __init__
    nbytes = audio_nbytes)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/audio/io/AudioFileClip.py", line 63, in __init__
    buffersize=buffersize)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/audio/io/readers.py", line 64, in __init__
    self.buffer_around(1)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/audio/io/readers.py", line 242, in buffer_around
    self.buffer =  self.read_chunk(self.buffersize)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/audio/io/readers.py", line 114, in read_chunk
    s = self.proc.stdout.read(L)
KeyboardInterrupt
Exception ignored in: <bound method Cursor.__del__ of <pymongo.cursor.Cursor object at 0x7f9d0e3f9198>>
Traceback (most recent call last):
  File "/home/bbbb/.local/lib/python3.5/site-packages/pymongo/cursor.py", line 215, in __del__
  File "/home/bbbb/.local/lib/python3.5/site-packages/pymongo/cursor.py", line 277, in __die
  File "/home/bbbb/.local/lib/python3.5/site-packages/pymongo/mongo_client.py", line 910, in close_cursor
  File "/home/bbbb/.local/lib/python3.5/site-packages/pymongo/cursor_manager.py", line 56, in close
AttributeError: 'NoneType' object has no attribute 'kill_cursors'
```

**Comment by keikoro** [comment]
As this issue is quite old and no code was included which could help with debugging, I'm closing this.
