### ISSUE TITLE
version 0.2.3.2 TypeError: must be str, not bytes

### ISSUE THREAD

**Issue by Goddard** [Zulko/moviepy#650]
```
~/anaconda3/lib/python3.6/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py in write_frames(self, frames_array)
     89             error = (str(err)+ ("\n\nMoviePy error: FFMPEG encountered "
     90                      "the following error while writing file %s:"%self.filename
---> 91                      + "\n\n"+ffmpeg_error))
     92 
     93             if b"Unknown encoder" in ffmpeg_error:

TypeError: must be str, not bytes

ffmpeg version 3.3.3 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 4.8.2 (GCC) 20140120 (Red Hat 4.8.2-15)
  configuration: --prefix=/home/irenicus/anaconda3 --disable-doc --enable-shared --enable-static --extra-cflags='-Wall -g -m64 -pipe -O3 -march=x86-64 -fPIC -I/home/irenicus/anaconda3/include' --extra-cxxflags='=-Wall -g -m64 -pipe -O3 -march=x86-64 -fPIC' --extra-libs='-L/home/irenicus/anaconda3/lib -lz' --enable-pic --enable-version3 --enable-hardcoded-tables --enable-avresample
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
Hyper fast Audio and Video encoder
```

**Comment by adcrn** [comment]
I'm running into the same issue.

```
Traceback (most recent call last):
  File "/Users/adcrn/homebrew/lib/python3.6/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 84, in write_frames
    self.proc.stdin.write(frames_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

'''During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 46, in <module>
    audio_op.audio_extraction(p.filename, p.audio_dest)
  File "/Users/adcrn/projects/transcript-helper/stuff/audio_op.py", line 22, in audio_extraction
    progress_bar=False)
  File "<decorator-gen-73>", line 2, in write_audiofile
  File "/Users/adcrn/homebrew/lib/python3.6/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/Users/adcrn/homebrew/lib/python3.6/site-packages/moviepy/audio/AudioClip.py", line 208, in write_audiofile
    progress_bar=progress_bar)
  File "<decorator-gen-70>", line 2, in ffmpeg_audiowrite
  File "/Users/adcrn/homebrew/lib/python3.6/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/Users/adcrn/homebrew/lib/python3.6/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 162, in ffmpeg_audiowrite
    writer.write_frames(chunk)
  File "/Users/adcrn/homebrew/lib/python3.6/site-packages/moviepy/audio/io/ffmpeg_audiowriter.py", line 91, in write_frames
    + "\n\n"+ffmpeg_error))
TypeError: must be str, not bytes

```

**Comment by Goddard** [comment]
I think this project is abandoned.  

I just switched to opencv.

**Comment by tburrows13** [comment]
I realise this is quite late, but what happens if you put a `str()` round `ffmpeg_error`? So it will look like `"\n\n"+str(ffmpeg_error)))`.  Presumably you'll get a more helpful error now.
