### ISSUE TITLE
Audio error

### ISSUE THREAD

**Issue by Dnomin** [Zulko/moviepy#675]
trying change audio in video, try 2 different audios, the same errors.
`from moviepy.editor import *

clip = VideoFileClip("cat.mp4").subclip(10,20)
audio = AudioFileClip("ariya.mp3").subclip(20,30)

new_clip = clip.set_audio(audio)

new_clip.write_videofile("cat_1.mp4")`

error:
`Traceback (most recent call last):
  File "/home/dnomin/.local/lib/python3.5/site-packages/moviepy/video/io/ffmpeg_reader.py", line 283, in ffmpeg_parse_infos
    line = [l for l in lines if keyword in l][0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)
  File "/usr/lib/python3/dist-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)
  File "/home/dnomin/Документы/cat.py", line 4, in <module>
    audio = AudioFileClip("ariya.mp3").subclip(20,30)
  File "/home/dnomin/.local/lib/python3.5/site-packages/moviepy/audio/io/AudioFileClip.py", line 63, in __init__
    buffersize=buffersize)
  File "/home/dnomin/.local/lib/python3.5/site-packages/moviepy/audio/io/readers.py", line 50, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "/home/dnomin/.local/lib/python3.5/site-packages/moviepy/video/io/ffmpeg_reader.py", line 289, in ffmpeg_parse_infos
    filename, infos))
OSError: MoviePy error: failed to read the duration of file ariya.mp3.
Here are the file infos returned by ffmpeg:

ffmpeg version 3.2.4-1build2 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 6.3.0 (Ubuntu 6.3.0-8ubuntu1) 20170221
  configuration: --prefix=/usr --extra-version=1build2 --toolchain=hardened --libdir=/usr/lib/i386-linux-gnu --incdir=/usr/include/i386-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libebur128 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 34.101 / 55. 34.101
  libavcodec     57. 64.101 / 57. 64.101
  libavformat    57. 56.101 / 57. 56.101
  libavdevice    57.  1.100 / 57.  1.100
  libavfilter     6. 65.100 /  6. 65.100
  libavresample   3.  1.  0 /  3.  1.  0
  libswscale      4.  2.100 /  4.  2.100
  libswresample   2.  3.100 /  2.  3.100
  libpostproc    54.  1.100 / 54.  1.100
[mp3 @ 0x80f9f680] Format mp3 detected only with low score of 1, misdetection possible!
[mp3 @ 0x80f9f680] Failed to read frame size: Could not seek to 1026.
ariya.mp3: Invalid argument`

**Comment by Dnomin** [comment]
idk why, but it seems like mp3 copied with errors from downloads to documents. Issued closed.
