### ISSUE TITLE
Error - The handle is invalid - Windows Only

### ISSUE THREAD

**Issue by SelfnessAid** [Zulko/moviepy#697]
I am getting follow error when run python script on windows10.
```
Process Process-3:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Work\Me\SnapVideo\snapvideo.py", line 63, in split_videofile
    video.audio.reader.close()
AttributeError: 'FFMPEG_AudioReader' object has no attribute 'close'
 84%|████████▍ | 634/751 [00:56<00:04, 26.57it/s]Exception ignored in: <bound method FFMPEG_AudioReader.__del__ of <moviepy.audio.io.readers.FFMPEG_AudioReader object at 0x05F91090>>
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\audio\io\readers.py", line 248, in __del__
    self.close_proc()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\audio\io\readers.py", line 147, in close_proc
    self.proc.terminate()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python36-32\lib\subprocess.py", line 1139, in terminate
    _winapi.TerminateProcess(self._handle, 1)
OSError: [WinError 6] The handle is invalid
```

But this script works well on MacOS.
Here is my code clip.
```
def split_videofile(filename, clip_start, clip_end, num):
    try:
        video = VideoFileClip("./resources/videos/origin/" + filename).subclip(clip_start, clip_end).resize((640, 360))
        filename, file_extension = os.path.splitext(filename)
        video.write_videofile("./resources/videos/origin/" + filename + "_split_" + str(num) + file_extension, fps=25)
        video.reader.close()
        video.audio.reader.close()
    except IOError as e:
        print(e.strerror)
    finally:
        pool_sema.release()
```

Please help me.
It seems be related with MoviePy package.
thanks.

**Comment by balvinderz** [comment]
How did you resolve this issue ?
