### ISSUE TITLE
documentation example gives error: 'AudioClip' object has no attribute 'fps'

### ISSUE THREAD

**Issue by tommy-mor** [Zulko/moviepy#755]
This is an example from the docs

```
import numpy as np
from moviepy.editor import *
make_frame = lambda t : 2*[ np.sin(404 * 2 * np.pi * t) ]
clip = AudioClip(make_frame, duration=5)
clip.preview()
```

gives this error:

>Traceback (most recent call last):
>  File "/Users/tommy/programming/video/bug.py", line 5, in <module>
>    clip.preview()
>  File "<decorator-gen-99>", line 2, in preview
>  File "/usr/local/lib/python3.6/site-packages/moviepy/decorators.py", line 54, in requires_duration
>    return f(clip, *a, **k)
>  File "/usr/local/lib/python3.6/site-packages/moviepy/audio/io/preview.py", line 49, in preview
>    sndarray = clip.to_soundarray(tt,nbytes=nbytes, quantize=True)
>  File "<decorator-gen-72>", line 2, in to_soundarray
>  File "/usr/local/lib/python3.6/site-packages/moviepy/decorators.py", line 54, in requires_duration
>    return f(clip, *a, **k)
>  File "/usr/local/lib/python3.6/site-packages/moviepy/audio/AudioClip.py", line 107, in to_soundarray
>    fps = self.fps
>AttributeError: 'AudioClip' object has no attribute 'fps'

am I missing something?

**Comment by tburrows13** [comment]
Thanks for raising this. It’s either a problem with the docs or the library. I’m pretty sure you can add `fps=x` (replace `x` with a number) when you create the AudioClip, and that will work. However, I just glanced at the source code for `preview`, and it does have a default value for `fps`, which it does someone use. I’m not sure what’s going on there, as you’d expect it to work with that.

**Comment by tommy-mor** [comment]
adding `fps` as an optional argument (or just setting `clip.fps = 44100` after you make the clip) does seem to solve the error I was getting, but it seems to reveal a much more complicated error (at least for me)

in my new code
```
make_frame = lambda t : 2*[ np.sin(404 * 2 * np.pi * t) ]
clip = AudioClip(make_frame, duration=5)
clip.fps = 44100
clip.preview()
```
I am getting this traceback
```
Traceback (most recent call last):
  File "/Users/tommy/programming/video/test.py", line 6, in <module>
    clip.preview()
  File "<decorator-gen-99>", line 2, in preview
  File "/usr/local/lib/python3.6/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.6/site-packages/moviepy/audio/io/preview.py", line 50, in preview
    chunk = pg.sndarray.make_sound(sndarray)
  File "/usr/local/lib/python3.6/site-packages/pygame/sndarray.py", line 80, in make_sound
    return numpysnd.make_sound (array)
  File "/usr/local/lib/python3.6/site-packages/pygame/_numpysndarray.py", line 75, in make_sound
    return mixer.Sound (array=array)
ValueError: Array depth must match number of mixer channels
```
which has proven to be much more complicated to figure out.
Its strange because the "array depth" seems to be 2 (the shape of the first frame is (2, 4000)) and also the pygame mixer is initialized with the channels argument being ``clip.nchannels`` which is 2. (in preview.py line 45). So at first glance it seems like they do match

**Comment by tburrows13** [comment]
That’s very strange. Does it work if you write the clip to a file with `clip.write_audiofile()`  instead of previewing it?

**Comment by tommy-mor** [comment]
it does! I should have tried that... Another thing I noticed is that when it is a mono (just ``[ np.sin(404 * 2 * np.pi * t) ]``, it sounds (and looks) correct, but when it is stereo (``2*[ np.sin(404 * 2 * np.pi * t) ]``) it sounds choppy and looks wrong. Its hard to describe, so here's a screen shot of the spectogram, the top track being the choppy stereo one, the bottom being the normal sounding stereo one. Maybe this is expected behavior, maybe not.
https://imgur.com/a/XInV0Bt


This is the only other mention I could find of audio 'clicks' https://stackoverflow.com/questions/7816294/simple-pygame-audio-at-a-frequency

**Comment by keikoro** [comment]
Was the issue described in here solved, or only partly solved? (Should the issue remain open?)

**Comment by angeAnonyme** [comment]
> Was the issue described in here solved, or only partly solved? (Should the issue remain open?)

I still have the issue, and I installed moviepy today (via PIP).
Python 3.7.6

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
