### ISSUE TITLE
[Errno 3] No such process : on Windows Sub Linux (ubuntu 16.x)

### ISSUE THREAD

**Issue by Max452** [Zulko/moviepy#765]
I have installed Moviepy & ffmpeg:
when I run this : 
```
test_clip = VideoFileClip("test.mp4")
```
I have this error : 
```ProcessLookupError                        Traceback (most recent call last)
<ipython-input-17-6bd6d3ce1adf> in <module>()
----> 1 test_clip = VideoFileClip("test.mp4")

/usr/local/lib/python3.5/dist-packages/moviepy/video/io/VideoFileClip.py in __init__(self, filename, has_mask, audio, audio_buffersize, target_resolution, resize_algorithm, audio_fps, audio_nbytes, verbose, fps_source)
     74                                          target_resolution=target_resolution,
     75                                          resize_algo=resize_algorithm,
---> 76                                          fps_source=fps_source)
     77 
     78         # Make some of the reader's attributes accessible from the clip

/usr/local/lib/python3.5/dist-packages/moviepy/video/io/ffmpeg_reader.py in __init__(self, filename, print_infos, bufsize, pix_fmt, check_duration, target_resolution, resize_algo, fps_source)
     29 
     30         self.filename = filename
---> 31         infos = ffmpeg_parse_infos(filename, print_infos, check_duration, fps_source)
     32         self.fps = infos['video_fps']
     33         self.size = infos['video_size']

/usr/local/lib/python3.5/dist-packages/moviepy/video/io/ffmpeg_reader.py in ffmpeg_parse_infos(filename, print_infos, check_duration, fps_source)
    256 
    257     proc.stdout.readline()
--> 258     proc.terminate()
    259     infos = proc.stderr.read().decode('utf8')
    260     del proc

/usr/lib/python3.5/subprocess.py in terminate(self)
   1780             """Terminate the process with SIGTERM
   1781             """
-> 1782             self.send_signal(signal.SIGTERM)
   1783 
   1784         def kill(self):

/usr/lib/python3.5/subprocess.py in send_signal(self, sig)
   1775             # Skip signalling a process that we know has already died.
   1776             if self.returncode is None:
-> 1777                 os.kill(self.pid, sig)
   1778 
   1779         def terminate(self):

ProcessLookupError: [Errno 3] No such process`

I've tested this  : 
`ffmpeg -i test.mp4`
and the result seems to work
`ffmpeg version 3.1.3-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.1 (Debian 5.4.1-1) 20160803
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libwebp --enable-libspeex --enable-libvorbis --enable-libvpx --enable-libfreetype --enable-fontconfig --enable-libxvid --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvo-amrwbenc --enable-gray --enable-libopenjpeg --enable-libopus --enable-libass --enable-gnutls --enable-libvidstab --enable-libsoxr --enable-frei0r --enable-libfribidi --disable-indev=sndio --disable-outdev=sndio --enable-librtmp --enable-libmfx --enable-libzimg --cc=gcc-5
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'test.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 1
    compatible_brands: mp41mp42isom
    creation_time   : 2016-09-28 18:41:26
  Duration: 00:00:10.04, start: 0.000000, bitrate: 12026 kb/s
    Stream #0:0(eng): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 2 kb/s (default)
    Metadata:
      creation_time   : 2016-09-28 18:41:26
      handler_name    : Core Media Audio
    Stream #0:1(und): Video: h264 (High) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 12020 kb/s, 25 fps, 25 tbr, 25 tbn, 50 tbc (default)
    Metadata:
      creation_time   : 2016-09-28 18:41:26
      handler_name    : Core Media Video
At least one output file must be specified
```

Hope you find why this doesn't work

**Comment by jrmalin** [comment]
I am also having this issue on WSL Ubuntu 16.x.

**Comment by mincaeuro** [comment]
same here:
`Traceback (most recent call last):
  File "test.py", line 7, in <module>
    clip = (VideoFileClip(file)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 33, in __init__
    fps_source)
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 259, in ffmpeg_parse_infos
    proc.terminate()
  File "/usr/lib/python3.5/subprocess.py", line 1782, in terminate
    self.send_signal(signal.SIGTERM)
  File "/usr/lib/python3.5/subprocess.py", line 1777, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process`

**Comment by hakanu** [comment]
Any update on this? I'm having the same problem. Thanks

**Comment by michaeltoohig** [comment]
Same here.

**Comment by cundesi** [comment]
Same here.

**Comment by ryanfox** [comment]
I am seeing the same thing with WSL 18.04, python 3.6, for what it's worth. Looking at a potential fix right now.

**Comment by Overdrivr** [comment]
It looks like this has been fixed by https://github.com/Zulko/moviepy/pull/927, feel free to reopen if you encounter this bug again (please note it's live on master but not released yet on pypi)

**Comment by YingYellow** [comment]
I also have this problem with moviepy-2.0.0.dev1.

Exception ignored in: <function FFMPEG_AudioReader.__del__ at 0x7f8d6f74cee0>
Traceback (most recent call last):
  File "/data/ying/Anaconda3/envs/video_recap/lib/python3.8/site-packages/moviepy/audio/io/readers.py", line 260, in __del__
    self.close_proc()
  File "/data/ying/Anaconda3/envs/video_recap/lib/python3.8/site-packages/moviepy/audio/io/readers.py", line 165, in close_proc
    self.proc.terminate()
  File "/data/ying/Anaconda3/envs/video_recap/lib/python3.8/subprocess.py", line 1954, in terminate
    self.send_signal(signal.SIGTERM)
  File "/data/ying/Anaconda3/envs/video_recap/lib/python3.8/subprocess.py", line 1949, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
