### ISSUE TITLE
fail to install

### ISSUE THREAD

**Issue by AlexeyAM** [Zulko/moviepy#771]
Here is cmd output:

  --------------
n:\moviepy-master>python setup.py
error in moviepy setup command: 'extras_require' must be a dictionary whose valu
es are strings or lists of strings containing valid project/version requirement
specifiers.
   ------------

How to handle this?
I use Python 2.7 on Windows 7

**Comment by tburrows13** [comment]
Are you sure you have the latest version of moviepy from this repo? And what about `pip install moviepy`?

**Comment by AlexeyAM** [comment]
From changelog - ## [v0.2.3.3](
pip (latest version) gives the same error. I've started from it.
Python 2.7.10

**Comment by tburrows13** [comment]
In which case, I'm stuck. We need someone with Windows to try and reproduce the error. I've just tried pip installing moviepy (v0.2.3.3 with Python 2.7) on Mac and it works fine. However, when I do `python setup.py`, it doesn't try to install it, it gives 

```
$ python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

You need `python setup.py install`.

**Comment by AlexeyAM** [comment]
Here is debugging information from Python console called by Visual Studio:

-------------
Traceback (most recent call last):
  File "C:\Program Files\Microsoft Visual Studio 11.0\Common7\IDE\Extensions\Mic
rosoft\Python Tools for Visual Studio\2.1\visualstudio_py_util.py", line 106, in
 exec_file
    exec_code(code, file, global_variables)
  File "C:\Program Files\Microsoft Visual Studio 11.0\Common7\IDE\Extensions\Mic
rosoft\Python Tools for Visual Studio\2.1\visualstudio_py_util.py", line 82, in
exec_code
    exec(code_obj, global_variables)
  File "N:\moviepy-master\setup.py", line 137, in <module>
    extras_require=extra_reqs,
  File "C:\Python27\lib\distutils\core.py", line 115, in setup
    (attrs['name'], msg)
SystemExit: error in moviepy setup command: 'extras_require' must be a dictionar
y whose values are strings or lists of strings containing valid project/version
requirement specifiers.
Press any key to continue . . .

**Comment by AlexeyAM** [comment]
Here is result.
                                ----------------
```
c:\Python27>python
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on wi
n32
Type "help", "copyright", "credits" or "license" for more information.
 >>> pip install --upgrade setuptools
  File "<stdin>", line 1
    pip install --upgrade setuptools
              ^
SyntaxError: invalid syntax
 >>>
```
  -------------
pip is installed, the latest version - 10.0.1

**Comment by tburrows13** [comment]
No, don’t run it inside of the python shell. Just run it in your normal command line.

**Comment by AlexeyAM** [comment]
This worked:

C:\Users\AM>python -m pip install --upgrade setuptools

Indeed I had very old version - upgraded from version 16.0 to 39.0.1
Will continue with moviepy

**Comment by AlexeyAM** [comment]
OK.

``python setup.py install``

run from cmd worked. Thus, the problem was in old setuptools version.
Thanks, everybody.

**Comment by Zulko** [comment]
@AlexeyAM was it the same problem for your colleague on linux mint ? If both are solved, we can close this :)

**Comment by AlexeyAM** [comment]
OK.

``python setup.py install``

run from cmd worked. Thus, the problem was in old setuptools version.
Thanks, everybody.
