### ISSUE TITLE
IndexError: Index Out of Bounds in write_videofile() 

### ISSUE THREAD

**Issue by rohit-malik** [Zulko/moviepy#815]
#I am using latest version of moviepy and it still gives me error.

#vid.video_clip is giving path of video clips to read

```
count = 1
final_clip = None
for vid in videoList:
    clip = VideoFileClip(vid.video_clip).resize((1280,720))
    if count ==1:
        final_clip = clip
    else:
        final_clip = concatenate_videoclips([final_clip , clip])
    count = 0

final_clip.write_videofile("testing_concat.mp4")
```
--------------------------------------------------------------------------------------------

#Error Obtained:
```
[MoviePy] Writing audio in testing_concatTEMP_MPY_wvf_snd.mp3
  0%|          | 0/8541 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\io\readers.py", line 190, in get_frame
    result[in_time] = self.buffer[indices]
IndexError: index -60488 is out of bounds for axis 0 with size 39513

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Nitin Malik/PycharmProjects/video_testing/main.py", line 80, in <module>
    final_clip.write_videofile("testing_concat.mp4")
  File "<decorator-gen-51>", line 2, in write_videofile
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\video\VideoClip.py", line 318, in write_videofile
    progress_bar=progress_bar)
  File "<decorator-gen-73>", line 2, in write_audiofile
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 213, in write_audiofile
    progress_bar=progress_bar)
  File "<decorator-gen-70>", line 2, in ffmpeg_audiowrite
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\io\ffmpeg_audiowriter.py", line 170, in ffmpeg_audiowrite
    progress_bar=progress_bar):
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\tqdm\_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 84, in generator
    fps=fps, buffersize=chunksize)
  File "<decorator-gen-72>", line 2, in to_soundarray
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 130, in to_soundarray
    snd_array = self.get_frame(tt)
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 300, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 301, in <listcomp>
    if (part is not False)]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 300, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 301, in <listcomp>
    if (part is not False)]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 300, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 301, in <listcomp>
    if (part is not False)]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 300, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 301, in <listcomp>
    if (part is not False)]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 300, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 301, in <listcomp>
    if (part is not False)]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 300, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 301, in <listcomp>
    if (part is not False)]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 300, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 301, in <listcomp>
    if (part is not False)]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 300, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 301, in <listcomp>
    if (part is not False)]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 300, in make_frame
    for c, part in zip(self.clips, played_parts)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\AudioClip.py", line 301, in <listcomp>
    if (part is not False)]
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 78, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "C:\Users\Nitin Malik\PycharmProjects\video_testing\venv\lib\site-packages\moviepy\audio\io\readers.py", line 202, in get_frame
    result[in_time] = self.buffer[indices]
IndexError: index -60488 is out of bounds for axis 0 with size 39513
```

**Comment by zamirkhan** [comment]
I experienced a similar issue in production. This is a moviepy script that has not failed like this before (and hasn't changed source code for a while, it's from a docker image). It is not the latest version (I will re-test), but I wanted to add this here as another person experiencing this type of failure. It happens consistently with the series of videos that cause this failure, but hasn't happened in any other runs.

```
...
[MoviePy] >>>> Building video S1aj0dv8V.mp4
[MoviePy] Writing audio in S1aj0dv8VTEMP_MPY_wvf_snd.m4a
Exception Thrown: index -76448 is out of bounds for axis 0 with size 23552
```

**Comment by zamirkhan** [comment]
For what it's worth, I believe I have tracked down the cause of my error. The script was joining a large number of videos and one of them appears to have an incomplete audio track. The video plays fine in any player I try, but the audio cuts out partway through and is completely silent. If I exclude this video, things appear to work. So it's nice to know that isn't just a random failure and there was a (somewhat) detectable cause. It would be nice if moviepy was robust to this scenario, but I realize that may not be a priority. Unfortunately I am unable to share the video, but if anyone has suggestions for tools to use to help diagnose the state of the audio track, let me know.

**Comment by yellowtiramisu** [comment]
I'm having this issue as well. I tried several different videos with different formats and lengths as input but the issue persists, with the only difference from the initial post being the size towards the end. Halp!

**Comment by hustshenl** [comment]
I also encountered this issue.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
