### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (1080,1920,3) (1080,1920) 

### ISSUE THREAD

**Issue by ghost** [Zulko/moviepy#826]
### Expected Behavior
I'm trying to overlay different types of images, gifs, videos on top of each other.

### Actual Behavior
I get an error message:
```
[MoviePy] >>>> Building video dank.mp4
[MoviePy] Writing video dank.mp4
  0%|          | 0/289 [00:00<?, ?it/s]Traceback (most recent call last):
  File "C:\Google Drive\_main\comms\projects\youtube\twiddleMaker\NEWtwiddletest.py", line 211, in <module>
    finalVideo.write_videofile(twiddleName + ".mp4", fps=24)
  File "<decorator-gen-51>", line 2, in write_videofile
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\video\VideoClip.py", line 327, in write_videofile
    progress_bar=progress_bar)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 218, in ffmpeg_write_video
    fps=fps, dtype="uint8"):
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\tqdm\_tqdm.py", line 930, in __iter__
    for obj in iterable:
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\Clip.py", line 475, in generator
    frame = self.get_frame(t)
  File "<decorator-gen-10>", line 2, in get_frame
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\Clip.py", line 94, in get_frame
    return self.make_frame(t)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\video\compositing\CompositeVideoClip.py", line 112, in make_frame
    f = c.blit_on(f, t)
  File "C:\Users\me\AppData\Local\Programs\Python\Python36-32\lib\site-packages\moviepy\video\VideoClip.py", line 545, in blit_on
    return np.minimum(1, picture + self.blit_on(np.zeros(framesize), t))
ValueError: operands could not be broadcast together with shapes (1080,1920,3) (1080,1920)
```

### Steps to Reproduce the Problem

This code builds a list of clips to overlay onto each other. I *think* the ValueError has something to do with the extra RGB/alphachannel/other thing represented by the "3" in the first "shape" in the error.

```
totalClips = []
if not (not still_basesToUse):
    for i in range(len(still_basesToUse)):
        if len(totalClips) < 1:
            tempClip = ImageClip(still_basesFolder + "/" + still_basesToUse[i]).resize((1920,1080)).set_duration(twiddleLength)
            totalClips.append(tempClip)
        else:
            tempClip = ImageClip(still_basesFolder + "/" + still_basesToUse[i]).resize((1920,1080)).set_duration(twiddleLength)
            totalClips.append(tempClip.to_mask())
        print("Just added " + str(still_basesToUse[i]) + " to the mix!")
        print("And sure enough, " + str(totalClips[-1]) + " is in!")
#then base
if not (not basesToUse):
    for i in range(len(basesToUse)):
        if len(totalClips) < 1:
            tempClip = VideoFileClip(basesFolder + "/" + basesToUse[i]).resize((1920,1080)).set_duration(twiddleLength)
            totalClips.append(tempClip)
        else:
            tempClip = VideoFileClip(basesFolder + "/" + basesToUse[i]).resize((1920,1080)).set_duration(twiddleLength)
            totalClips.append(tempClip.to_mask())
        print("Just added " + str(basesToUse[i]) + " to the mix!")
        print("And sure enough, " + str(totalClips[-1]) + " is in!")
#then still overlarges
if not (not still_overlargesToUse):
    for i in range(len(still_overlargesToUse)):
        tempClip = ImageClip(still_overlargesFolder + "/" + still_overlargesToUse[i]).resize((700,700)).set_duration(twiddleLength) #layers on top of base layer(s) get resized to be smaller, so they don't block the lower ones.
        totalClips.append(tempClip.to_mask().set_pos(random.choice(['center', 'top', 'left', 'right'])))
        print("Just added " + str(still_overlargesToUse[i]) + " to the mix!")
        print("And sure enough, " + str(totalClips[-1]) + " is in!")
#then overlarges
if not (not overlargesToUse):
    for i in range(len(overlargesToUse)):
        tempClip = VideoFileClip(overlargesFolder + "/" + overlargesToUse[i]).resize((700,700)).set_duration(twiddleLength)
        totalClips.append(tempClip.to_mask().set_pos(random.choice(['center', 'top', 'left', 'right'])))
        print("Just added " + str(overlargesToUse[i]) + " to the mix!")
        print("And sure enough, " + str(totalClips[-1]) + " is in!")
#then still oversmalls
if not (not still_oversmallsToUse):
    for i in range(len(still_oversmallsToUse)):
        tempClip = ImageClip(still_oversmallsFolder + "/" + still_oversmallsToUse[i]).resize((300,300)).set_duration(twiddleLength)
        totalClips.append(tempClip.to_mask().set_pos(random.choice(['center', 'top', 'left', 'right'])))
        print("Just added " + str(still_oversmallsToUse[i]) + " to the mix!")
        print("And sure enough, " + str(totalClips[-1]) + " is in!")
#then oversmalls
if not (not oversmallsToUse):
    for i in range(len(oversmallsToUse)):
        tempClip = VideoFileClip(oversmallsFolder + "/" + oversmallsToUse[i]).resize((300,300)).set_duration(twiddleLength)
        totalClips.append(tempClip.to_mask().set_pos(random.choice(['center', 'top', 'left', 'right'])))
        print("Just added " + str(oversmallsToUse[i]) + " to the mix!")
        print("And sure enough, " + str(totalClips[-1]) + " is in!")
```
And *this* code renders this out:

```
finalVideo = CompositeVideoClip(totalClips, size=(1920,1080))
finalVideo.write_videofile(twiddleName + ".mp4", fps=24)
```

### Specifications

  - Python Version: 3.6.4
  - Moviepy Version: 0.2.3.2
  - Platform Name: Windows 10 Home
  - Platform Version: Latest

**Comment by smith1302** [comment]
Did you ever figure out a solution to this issue?

**Comment by tburrows13** [comment]
I'm fairly certain that the problem here is that `totalClips` contains a combination of regular clips and masks. Masks need to be added to clips using `clip.set_mask`, not by including them in a `CompositeVideoClip`.
