### ISSUE TITLE
Unable to rotate ImageClip but able to rotate equivalent VideoFileClip

### ISSUE THREAD

**Issue by abissellsiders** [Zulko/moviepy#828]
### Expected Behavior

I believe that moviepy should be able to rotate an ImageClip. If this is incorrect, I have not seen it mentioned anywhere.

### Actual Behavior

moviepy is unable to rotate an ImageClip but is able to rotate an equivalent mp4 file.

### Steps to Reproduce the Problem

If I import an image as an ImageClip and attempt to rotate it, PIL returns a TypeError:

```
# does not work

import moviepy.editor as mp
clip = mp.ImageClip("./temp1.png")
clip_rotated = clip.set_duration(4).fx(mp.vfx.rotate, lambda t: 90*t, expand = False)
clip_rotated.write_videofile("temp1.mp4", fps = 30)
```

Error code returned:

```
Traceback (most recent call last):
  File "C:\Users\theth\Desktop\temp.py", line 5, in <module>
    clip_rotated = clip.set_duration(5).fx(mp.vfx.rotate, lambda t: 90*t, expand = False)
  File "C:\Python362\lib\site-packages\moviepy\Clip.py", line 215, in fx
    return func(self, *args, **kwargs)
  File "C:\Python362\lib\site-packages\moviepy\video\fx\rotate.py", line 71, in rotate
    return clip.fl(fl, apply_to=["mask"])
  File "C:\Python362\lib\site-packages\moviepy\video\VideoClip.py", line 1001, in fl
    keep_duration=keep_duration)
  File "C:\Python362\lib\site-packages\moviepy\Clip.py", line 136, in fl
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "<decorator-gen-57>", line 2, in set_make_frame
  File "C:\Python362\lib\site-packages\moviepy\decorators.py", line 14, in outplace
    f(newclip, *a, **k)
  File "C:\Python362\lib\site-packages\moviepy\video\VideoClip.py", line 694, in set_make_frame
    self.size = self.get_frame(0).shape[:2][::-1]
  File "<decorator-gen-14>", line 2, in get_frame
  File "C:\Python362\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Python362\lib\site-packages\moviepy\Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "C:\Python362\lib\site-packages\moviepy\Clip.py", line 136, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "C:\Python362\lib\site-packages\moviepy\video\fx\rotate.py", line 69, in fl
    return pil_rotater(im, a, resample=resample, expand=expand)
  File "C:\Python362\lib\site-packages\moviepy\video\fx\rotate.py", line 7, in pil_rotater
    return np.array( Image.fromarray(pic).rotate(angle, expand=expand,
  File "C:\Python362\lib\site-packages\PIL\Image.py", line 2419, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
```

However, if I write the image as an mp4 and import that mp4 as the clip, then the rotated clip is produced:

```
# works

import moviepy.editor as mp
image = mp.ImageClip("./temp1.png").set_duration(1/25)
image.write_videofile("temp2.mp4", fps = 25)
clip = mp.VideoFileClip(r"temp2.mp4")
clip_rotated = clip.set_duration(4).fx(mp.vfx.rotate, lambda t: 90*t, expand = False)
clip_rotated.write_videofile("temp3.mp4", fps = 30)
```

I have attempted this with multiple image types (PNG, JPG) with and without transparency and have seen the same problem.

### Specifications

  - Python Version: Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
  - Moviepy Version: 0.2.3.2
  - Platform Name: Windows 10 Home
  - Platform Version: Version 10.0.16299 Build 16299

**Comment by tburrows13** [comment]
I can't replicate this, and it looks like it was fixed in #1139 anyway.
