### ISSUE TITLE
'ffmpeg-linux64-v3.3.1' was not found on your computer; downloading it now.

### ISSUE THREAD

**Issue by cy5e** [Zulko/moviepy#839]
### Expected Behavior

Hi I am having problems similar to issue [#493](https://github.com/Zulko/moviepy/issues/493). I tried to download the FFMPEG manually within python console but got errors as following. 
### Actual Behavior
```
Python 3.6.6 |Anaconda, Inc.| (default, Jun 28 2018, 17:14:51) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import imageio
>>> imageio.plugins.ffmpeg.download()
Imageio: 'ffmpeg-linux64-v3.3.1' was not found on your computer; downloading it now.
Error while fetching file: HTTP Error 502: Bad Gateway.
Error while fetching file: HTTP Error 502: Bad Gateway.
Error while fetching file: HTTP Error 502: Bad Gateway.
Error while fetching file: HTTP Error 502: Bad Gateway.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../anaconda3/envs/py36/lib/python3.6/site-packages/imageio/plugins/ffmpeg.py", line 73, in download
    force_download=force_download)
  File ".../anaconda3/envs/py36/lib/python3.6/site-packages/imageio/core/fetching.py", line 127, in get_remote_file
    _fetch_file(url, filename)
  File ".../anaconda3/envs/py36/lib/python3.6/site-packages/imageio/core/fetching.py", line 183, in _fetch_file
    os.path.basename(file_name))
OSError: Unable to download 'ffmpeg-linux64-v3.3.1'. Perhaps there is a no internet connection? If there is, please report this problem.

```

### Specifications

  - Python Version: 3.6.6 Conda
  - Moviepy Version:
  - Platform Name:
  - Platform Version:

**Comment by KeizerDev** [comment]
As you can see, the server gives a `HTTP Error 502: Bad Gateway` back. This is not your fault or the fault of moviepy. This is probably a fault on the server that provides the ffmpeg binaries so I recommend to retry download it again now or tomorrow.

**Comment by mustfkeskin** [comment]
I have same problem

**Comment by tburrows13** [comment]
This method of installing ffmpeg is no longer supported.
