### ISSUE TITLE
ImageMagick not found.

### ISSUE THREAD

**Issue by element465** [Zulko/moviepy#883]
### Expected Behavior
To create the video in the sample that creates the Knights video.

### Actual Behavior
Get the dreaded ImageMagick is not installed error, even though it is installed and the    has been changed. I have had this issue multiple times after multiple reinstalls of all different versions of Ubuntu, I am running this on a Vultr VPS. Everything is up to date, and ImageMagick 6 is installed.

```
Analyzed the audio, found a period of 0.48 seconds
Analyzed the video, found a period of 1.23 seconds

[MoviePy] This command returned an error !Traceback (most recent call last):
  File "/home/movie/knight.py", line 78, in <module>
    font="Century-Schoolbook-Roman", color="white")
  File "/usr/local/lib/python2.7/dist-packages/moviepy/video/VideoClip.py", line 1173, in __init__
    raise IOError(error)
IOError: MoviePy Error: creation of None failed because of the following error:

convert: unable to read font `Century-Schoolbook-Roman' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Century-Schoolbook-Roman' @ error/annotate.c/RenderFreetype/1127.
convert: not authorized `/tmp/magick-26237HHBVp6dUVpNW' @ error/constitute.c/ReadImage/412.
convert: unable to read font `Century-Schoolbook-Roman' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Century-Schoolbook-Roman' @ error/annotate.c/RenderFreetype/1127.
convert: not authorized `/tmp/magick-26237XtZzKZXcqetx' @ error/constitute.c/ReadImage/412.
convert: unable to read font `Century-Schoolbook-Roman' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Century-Schoolbook-Roman' @ error/annotate.c/RenderFreetype/1127.
convert: not authorized `/tmp/magick-26237bqOuXBGTR687' @ error/constitute.c/ReadImage/412.
convert: unable to read font `Century-Schoolbook-Roman' @ warning/annotate.c/RenderType/872.
convert: unable to read font `Century-Schoolbook-Roman' @ error/annotate.c/RenderFreetype/1127.
convert: not authorized `/tmp/magick-26237HgCa56Rpk2OI' @ error/constitute.c/ReadImage/412.
convert: no images defined `PNG32:/tmp/tmp9JOwXM.png' @ error/convert.c/ConvertImageCommand/3210.
.

.This error can be due to the fact that ImageMagick is not installed on your computer, or (for Windows users) that you didn't specify the path to the ImageMagick binary in file conf.py, or that the path you specified is incorrect
```

### Steps to Reproduce the Problem

Just running the script.

### Specifications

  - Python Version: Python 2.712
  - Moviepy Version:  Latest
  - Platform Name: Ubuntu
  - Platform Version: 16.04

**Comment by tburrows13** [comment]
Moviepy is finding ImageMagick fine. The issue is that either the font 'Century-Schoolbook-Roman' is not found, or there is an issue in your ImageMagick policy file.
