### ISSUE TITLE
OSError: [Errno 12] Cannot allocate memory when creating slideshow

### ISSUE THREAD

**Issue by sdaau** [Zulko/moviepy#903]
I'm trying to create a slideshow in moviepy, following https://stackoverflow.com/questions/44732602/convert-image-sequence-to-video-using-moviepy

I have 249 images from a phone camera, with these properties:

```
$ mediainfo /path/to/test_IMG_11a.jpg
General
Complete name                            : /path/to/test_IMG_11a.jpg
Format                                   : JPEG
File size                                : 1 001 KiB

Image
Format                                   : JPEG
Width                                    : 3 840 pixels
Height                                   : 2 160 pixels
Color space                              : YUV
Chroma subsampling                       : 4:2:2
Bit depth                                : 8 bits
Compression mode                         : Lossy
Stream size                              : 1 001 KiB (100%)
```

I use this script:

```
#!/usr/bin/env python2

# https://stackoverflow.com/questions/44732602/convert-image-sequence-to-video-using-moviepy

import sys,os
import glob
import time
import datetime

# first run: "Imageio: 'ffmpeg-linux64-v3.3.1' was not found on your computer; downloading it now."
# but I have 3.4.4-0ubuntu0.18.04.1 on Ubuntu 18.04, so specify environment variable
os.environ["FFMPEG_BINARY"] = "/usr/bin/ffmpeg"

# moviepy in python2 may complain: ImportError: No module named requests; sudo -H pip2 install requests
from moviepy.editor import *

base_dir = ' /path/to'
file_list = glob.glob( os.path.join(base_dir, 'test_*.jpg') )
file_list_sorted = sorted ( file_list )

print("Starting... {}".format( datetime.datetime.fromtimestamp( time.time() ) ))
clips = []
for m in file_list_sorted:
  clips.append( ImageClip(m).set_duration(0.25) )
  print("  handling {} ({})".format( m, datetime.datetime.fromtimestamp( time.time() ) ))

# this takes a minute and a half for 249 images
print("Before concat... {}".format( datetime.datetime.fromtimestamp( time.time() ) ))
concat_clip = concatenate_videoclips(clips, method="compose")

# http://neiloseman.com/24fps-or-25fps/
fps = 24

print("Before write... {}".format( datetime.datetime.fromtimestamp( time.time() ) ))
# this fails for 249 images with "OSError: [Errno 12] Cannot allocate memory" on ffmpeg_writer.py;self.proc = sp.Popen(cmd, **popen_params)
concat_clip.write_videofile("out.mp4", fps=fps)
```

This is the stack trace (same for python2 or python3):
```
....
Before write... 2019-01-18 11:31:19.815935
[MoviePy] >>>> Building video out.mp4
[MoviePy] Writing video out.mp4
Traceback (most recent call last):
  File "video.py", line 42, in <module>
    concat_clip.write_videofile("out.mp4", fps=fps)
  File "<decorator-gen-51>", line 2, in write_videofile
  File "/usr/local/lib/python3.6/dist-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "/usr/local/lib/python3.6/dist-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "/usr/local/lib/python3.6/dist-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/VideoClip.py", line 327, in write_videofile
    progress_bar=progress_bar)
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 213, in ffmpeg_write_video
    ffmpeg_params=ffmpeg_params) as writer:
  File "/usr/local/lib/python3.6/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 127, in __init__
    self.proc = sp.Popen(cmd, **popen_params)
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1275, in _execute_child
    restore_signals, start_new_session, preexec_fn)
OSError: [Errno 12] Cannot allocate memory
```

### Specifications

  - Python Version: python2 or 3
  - Moviepy Version: `pip show moviepy` -> Version: 0.2.3.5
  - Platform Name: Ubuntu
  - Platform Version: 18.04

**Comment by danmash** [comment]
Hi @Zulko any updates on this?
```
clip.close()
del clip
```
don't help

**Comment by HoiM** [comment]
Same problem. I have a loop generating videos. Each iteration generates one video. When it comes to the third iteration, this error will occur.

**Comment by Kalaschnik** [comment]
I’m having the same issue. I process around 400 video files. I’m getting the Errno 12 at around 100 Videos. Are there any updates/workarounds on this?

**Comment by gdhatric** [comment]
I face the same issue too.

**Comment by TanishSurana** [comment]
I am facing the same issue, to overcome it I turn my vpn on. I have a feeling this is youtube (or whatever site) is blocking your ip address to prevent downloads.

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
