### ISSUE TITLE
Invalid temp file when writing very short videos

### ISSUE THREAD

**Issue by PaperBag42** [Zulko/moviepy#905]
### Expected Behavior
I am trying to split an MP4 video to many short clips, sometimes shorter than 0.1 seconds.

### Actual Behavior
When reaching a specific point in the video, I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 134, in write_frame
    self.proc.stdin.write(img_array.tobytes())
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\test.py", line 18, in <module>
    video.subclip(i, i + step).write_videofile(f'test/{i:.1f}.mp4')
  File "<decorator-gen-51>", line 2, in write_videofile
  File "...\moviepy\decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "<decorator-gen-50>", line 2, in write_videofile
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "<decorator-gen-49>", line 2, in write_videofile
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\VideoClip.py", line 327, in write_videofile
    progress_bar=progress_bar)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 225, in ffmpeg_write_video
    writer.write_frame(frame)
  File "C:\Users\user\AppData\Local\Programs\Python\Python37\lib\site-packages\moviepy\video\io\ffmpeg_writer.py", line 178, in write_frame
    raise IOError(error)
OSError: [Errno 32] Broken pipe

MoviePy error: FFMPEG encountered the following error while writing file test/15.1.mp4:

 b'15.1TEMP_MPY_wvf_snd.mp3: Invalid data found when processing input\r\n'
```
I always get this error at the same point in the video, though the point differs on each video I tried.
I also did not get the error when trying to only write the clip that causes the error.

### Steps to Reproduce the Problem

This sample script should reproduce the error:
```python
from moviepy.video.io.VideoFileClip import VideoFileClip
import youtube_dl

# downloads a normal video
# it should have the same error with any video if it is not too short
with youtube_dl.YoutubeDL({
		'format': 'mp4',
		'outtmpl': 'video.mp4',
	}) as ydl:
	ydl.download(['https://www.youtube.com/watch?v=IXHRyfJ39g4'])

# write 0.1 seconds long clips
with VideoFileClip('video.mp4') as video:
	step = 0.1
	stop = video.duration - step
	i = 0
	while i < stop:
		video.subclip(i, i + step).write_videofile(f'{i:.1f}.mp4')  # fails every time at i = 15.1
		i += step
```

### Specifications
  - Python Version: 3.6, 3.7
  - Moviepy Version: 0.2.3.5
  - Platform Name: Ubuntu, Windows
  - Platform Version: 18.04, 10

**Comment by alexbudin** [comment]
having the same issue

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
