### ISSUE TITLE
vfx.freeze gives error "failed to read the first frame of video"

### ISSUE THREAD

**Issue by brokeharvard** [Zulko/moviepy#956]
I can't get vfx.freeze to work. I've tried updating moviepy, updating ffmpeg, using different video files, etc., but I always get the same error. Can anyone suggest a fix?

### Example code ("savepath" is the path to an mp4 created with moviepy):

```
from moviepy.editor import *

keyword = "ariana grande"
savepath = str(sys.path[0] + "/" + keyword + ".mp4")
clip = VideoFileClip(savepath)
freeze_clip = clip.fx(vfx.freeze, t='end', freeze_duration=4)
freeze_clip.write_videofile(savepath[:-4] + "_Freeze" + ".mp4")
```

### Output:

```
Traceback (most recent call last):
  File "/Users/Colarossi/Desktop/Other/Coding/APG 2.0/handwriting.py", line 6, in <module>
    freeze_clip = clip.fx(vfx.freeze, t='end', freeze_duration=4)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/Clip.py", line 215, in fx
    return func(self, *args, **kwargs)
  File "</Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/decorator.py:decorator-gen-76>", line 2, in freeze
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/video/fx/freeze.py", line 25, in freeze
    freeze = [clip.to_ImageClip(t).set_duration(freeze_duration)]
  File "</Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/decorator.py:decorator-gen-65>", line 2, in to_ImageClip
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/video/VideoClip.py", line 738, in to_ImageClip
    newclip = ImageClip(self.get_frame(t), ismask=self.ismask,
  File "</Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/decorator.py:decorator-gen-10>", line 2, in get_frame
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/video/io/VideoFileClip.py", line 113, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 185, in get_frame
    result = self.read_frame()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/moviepy/video/io/ffmpeg_reader.py", line 139, in read_frame
    self.filename))
OSError: MoviePy error: failed to read the first frame of video file /Users/Colarossi/Desktop/Other/Coding/APG 2.0/ariana grande.mp4. That might mean that the file is corrupted. That may also mean that you are using a deprecated version of FFMPEG. On Ubuntu/Debian for instance the version in the repos is deprecated. Please update to a recent version from the website.
>>> 
```

### Specifications

  - Python Version: 3.6
  - Moviepy Version: Latest (3.0.4)
  - Machine:  MacBook Pro (Retina, 13-inch, Late 2012), running MacOS Mohave 10.14.1 

### EDIT (May 12, 2019):

I forgot to add that I've used many of the other vfx functions without trouble, including the below:

```
# blackwhite
new_clip = clip.fx(vfx.blackwhite, preserve_luminosity=False)

# invert_colors
new_clip = clip.fx(vfx.invert_colors)

# accel_decel
new_clip = clip.fx(vfx.accel_decel, new_duration=8)

# resize
new_clip = clip.fx(vfx.resize, width=1800)
```

As a result, I think the problem is with vfx.freeze (or something that it uses).  I've tried to isolate the problem by trying to execute various of the functions that are within the vfx.freeze function, and I think the issue is:

```
clip.to_ImageClip(t)
```

Running that function gives me the same error (with less traceback).  As you can see from the traceback, the error ultimately is raised by ffmpeg_reader.py.  I'm unsure whether the problem is actually ffmpeg_reader.py or something within ffmpeg itself (or something else). Any suggestions would be greatly appreciated. Would also be helpful to simply know if others are able to run vfx.freeze on the latest versions of moviepy and ffmpeg.

**Comment by tburrows13** [comment]
I think that this has been fixed in #1124. Feel free to reopen if the issue persists.
