### ISSUE TITLE
Mixing Clips Example note working.

### ISSUE THREAD

**Issue by DumbMachine** [Zulko/moviepy#976]
### Expected Behavior
No errors.
[Mixing Clips](http://zulko.github.io/moviepy/getting_started/compositing.html)

### Actual Behavior
```bash
Traceback (most recent call last):
  File "base.py", line 86, in <module>
    clip1 = VideoFileClip("x.mp4-0.mp4")
  File "/home/dumbmachine/anaconda3/lib/python3.7/site-packages/moviepy/video/io/VideoFileClip.py", line 91, in __init__
    fps_source=fps_source)
  File "/home/dumbmachine/anaconda3/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 34, in __init__
    self.fps = infos['video_fps']
KeyError: 'video_fps
```

### Steps to Reproduce the Problem

```python
from moviepy.editor import VideoFileClip, concatenate_videoclips
clip1 = VideoFileClip("x.mp4-0.mp4")
clip2 = VideoFileClip("x.mp4-1.mp4")
clip3 = VideoFileClip("x.mp4-2.mp4")
final_clip = concatenate_videoclips([clip1,clip2,clip3])
final_clip.write_videofile("my_concatenation.mp4")
```
### Specifications

  - Python Version: 3.7
  - Moviepy Version: 1.0.0
  - Platform Name: Ubuntu
  - Platform Version: Bionic

**Comment by CommanderAsdasd** [comment]
On MacOS high sierra not reproducing. Did you tried another videofile? Or just to convert this one through ffmpeg

**Comment by tburrows13** [comment]
Linking #899

**Comment by OsaAjani** [comment]
Thank you for your contributions and for reporting issues in this repository. With the release of v2, which introduces significant changes to the codebase and API, we’ve reviewed the backlog of open PRs and issues. Due to the length of the backlog and the likelihood that many of these are either fixed or no longer applicable, we’ve made the decision to close all previous PRs and issues.

If you believe that any of these are still relevant to the current version or if you'd like to reopen a related discussion, please feel free to create a new issue or pull request, referencing the old one.

Thank you for your understanding and continued support!
