### ISSUE TITLE
write_videofile throwing OSError on compile

### ISSUE THREAD

**Issue by andrew-hossack** [Zulko/moviepy#977]
Hi, I have been using moviepy to concatenate an intro and outtro to an ImageClip. However, sometimes at the end of the video compile (97-99% complete) python throws me an error:
> OSError: [Errno 9] Bad file descriptor

Could it be a dependency issue? Or is there something which I don't see?

Error:
`t:  98%|█████████▊| 4663/4743 [04:01<00:03, 22.03it/s, now=None]Traceback (most recent call last):
  File "/Users/andrew/eclipse-workspace/RedditScraper/src/Main.py", line 52, in <module>
    main()
  File "/Users/andrew/eclipse-workspace/RedditScraper/src/Main.py", line 45, in main
    Scrape.compile_video()
  File "/Users/andrew/eclipse-workspace/RedditScraper/src/Scrape.py", line 56, in compile_video
    concat_images_with_audio_intro.write_videofile("/Users/andrew/eclipse-workspace/RedditScraper/src/out.mp4",fps=18, temp_audiofile="/Users/andrew/eclipse-workspace/RedditScraper/src/output/temp-audio.m4a",remove_temp=True,audio_codec="aac")
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-55>", line 2, in write_videofile
  File "/usr/local/lib/python3.7/site-packages/moviepy/decorators.py", line 54, in requires_duration
    return f(clip, *a, **k)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-54>", line 2, in write_videofile
  File "/usr/local/lib/python3.7/site-packages/moviepy/decorators.py", line 137, in use_clip_fps_by_default
    return f(clip, *new_a, **new_kw)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-53>", line 2, in write_videofile
  File "/usr/local/lib/python3.7/site-packages/moviepy/decorators.py", line 22, in convert_masks_to_RGB
    return f(clip, *a, **k)
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 326, in write_videofile
    logger=logger)
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_writer.py", line 216, in ffmpeg_write_video
    fps=fps, dtype="uint8"):
  File "/usr/local/lib/python3.7/site-packages/moviepy/Clip.py", line 475, in iter_frames
    frame = self.get_frame(t)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-11>", line 2, in get_frame
  File "/usr/local/lib/python3.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.7/site-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/compositing/CompositeVideoClip.py", line 118, in make_frame
    f = c.blit_on(f, t)
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 548, in blit_on
    img = self.get_frame(ct)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-11>", line 2, in get_frame
  File "/usr/local/lib/python3.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.7/site-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.7/site-packages/moviepy/Clip.py", line 138, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 511, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-11>", line 2, in get_frame
  File "/usr/local/lib/python3.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.7/site-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/compositing/CompositeVideoClip.py", line 118, in make_frame
    f = c.blit_on(f, t)
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 548, in blit_on
    img = self.get_frame(ct)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-11>", line 2, in get_frame
  File "/usr/local/lib/python3.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.7/site-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.7/site-packages/moviepy/Clip.py", line 138, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 511, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-11>", line 2, in get_frame
  File "/usr/local/lib/python3.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.7/site-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.7/site-packages/moviepy/Clip.py", line 138, in <lambda>
    newclip = self.set_make_frame(lambda t: fun(self.get_frame, t))
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/VideoClip.py", line 511, in <lambda>
    return self.fl(lambda gf, t: image_func(gf(t)), apply_to)
  File "</usr/local/lib/python3.7/site-packages/decorator.py:decorator-gen-11>", line 2, in get_frame
  File "/usr/local/lib/python3.7/site-packages/moviepy/decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "/usr/local/lib/python3.7/site-packages/moviepy/Clip.py", line 95, in get_frame
    return self.make_frame(t)
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/io/VideoFileClip.py", line 113, in <lambda>
    self.make_frame = lambda t: self.reader.get_frame(t)
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 181, in get_frame
    self.initialize(t)
  File "/usr/local/lib/python3.7/site-packages/moviepy/video/io/ffmpeg_reader.py", line 104, in initialize
    self.proc = sp.Popen(cmd, **popen_params)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 9] Bad file descriptor`

  - Python Version: 3.7
  - Moviepy Version: 1.0.0

**Comment by dbarrett0815** [comment]
currently having the same issue. Cant find a fix

**Comment by andrew-hossack** [comment]
@dbarrett0815 I got around this issue by making sure every concatenated image and video clip had a correct format for filename and file extension. 

For example, if one image was named "foo.JPG" , moviepy would be unhappy because of the uppercase file extension. Also if there is whitespace in any of the image or video clip filenames, you want to get rid of that. 

I may be wrong, as this was a bug I had a while ago, let me know if this works.

**Comment by dbarrett0815** [comment]
@andrew-hossack unfortunately, that didn't work.

**Comment by keikoro** [comment]
@dbarrett0815 I'd ask you to open a new issue for your problem following the issue template if the problem persists. Feel free to link this issue for reference.
